! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cb05_sorg_aq_Monitor.f90
! Time                 : Tue Apr 12 23:42:40 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/cb05_sorg_aq
! Equation file        : cb05_sorg_aq.kpp
! Output root filename : cb05_sorg_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cb05_sorg_aq_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'tolaer1     ','tolaer2     ','cslaer      ', &
     'xylaer1     ','xylaer2     ','isoaer1     ', &
     'isoaer2     ','sulf        ','sulaer      ', &
     'terpaer     ','humaer      ','hum         ', &
     'limaer1     ','limaer2     ','lim         ', &
     'ociaer1     ','ociaer2     ','oci         ', &
     'apinaer1    ','apinaer2    ','apinaer3    ', &
     'apinaer4    ','apin        ','bpinaer1    ', &
     'bpinaer2    ','bpinaer3    ','bpinaer4    ', &
     'bpinaer5    ','bpin        ','teraer1     ', &
     'teraer2     ','ter         ','alkhaer1    ', &
     'alkh        ','pahaer1     ','pahaer2     ', &
     'pah         ','hg2         ','cl2         ', &
     'so2         ','pan         ','hocl        ', &
     'tol         ','h2          ','o1d         ', &
     'n2o5        ','xyl         ','ch4         ', &
     'hg0         ','hono        ','facd        ', &
     'to2         ','pna         ','pacd        ', &
     'aacd        ','panx        ','etha        ', &
     'meoh        ','etoh        ','h2o2        ', &
     'hcl         ','hco3        ','cro         ', &
     'clo         ','rooh        ','mgly        ', &
     'fmcl        ','mepx        ','hno3        ', &
     'co          ','open        ','ror         ', &
     'cres        ','eth         ','terp        ', &
     'iole        ','ole         ','xo2n        ', &
     'par         ','isop        ','ispd        ', &
     'aldx        ','ald2        ','ntr         ', &
     'form        ','o3          ','no2         ', &
     'cl          ','xo2         ','ho2         ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(9) :: SPC_NAMES_1 = (/ &
     'c2o3        ','meo2        ','o           ', &
     'cxo3        ','no          ','oh          ', &
     'no3         ','H2O         ','M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(99) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '           no2 --> o + no                                                                           ', &
     '             o --> o3                                                                               ', &
     '       o3 + no --> no2                                                                              ', &
     '       no2 + o --> no                                                                               ', &
     '       no2 + o --> no3                                                                              ', &
     '        o + no --> no2                                                                              ', &
     '      o3 + no2 --> no3                                                                              ', &
     '            o3 --> o                                                                                ', &
     '            o3 --> o1d                                                                              ', &
     '       o1d + M --> o + M                                                                            ', &
     '     o1d + H2O --> 2 oh                                                                             ', &
     '       o3 + oh --> ho2                                                                              ', &
     '      o3 + ho2 --> oh                                                                               ', &
     '           no3 --> no2 + o                                                                          ', &
     '           no3 --> no                                                                               ', &
     '      no + no3 --> 2 no2                                                                            ', &
     '     no2 + no3 --> no2 + no                                                                         ', &
     '     no2 + no3 --> n2o5                                                                             ', &
     '    n2o5 + H2O --> 2 hno3                                                                           ', &
     '  n2o5 + 2 H2O --> 2 hno3                                                                           ', &
     '          n2o5 --> no2 + no3                                                                        ', &
     '          2 no --> 2 no2                                                                            ', &
     'no2 + no + H2O --> 2 hono                                                                           ', &
     '       no + oh --> hono                                                                             ', &
     '          hono --> no + oh                                                                          ', &
     '     hono + oh --> no2                                                                              ', &
     '        2 hono --> no2 + no                                                                         ', &
     '      no2 + oh --> hno3                                                                             ', &
     '     hno3 + oh --> no3                                                                              ', &
     '      ho2 + no --> no2 + oh                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '     no2 + ho2 --> pna                                                                              ', &
     '           pna --> no2 + ho2                                                                        ', &
     '      pna + oh --> no2                                                                              ', &
     '         2 ho2 --> h2o2                                                                             ', &
     '   2 ho2 + H2O --> h2o2                                                                             ', &
     '          h2o2 --> 2 oh                                                                             ', &
     '     h2o2 + oh --> ho2                                                                              ', &
     '      h2 + o1d --> ho2 + oh                                                                         ', &
     '       h2 + oh --> ho2                                                                              ', &
     '        o + oh --> ho2                                                                              ', &
     '          2 oh --> o                                                                                ', &
     '          2 oh --> h2o2                                                                             ', &
     '      ho2 + oh --> H2O                                                                              ', &
     '       ho2 + o --> oh                                                                               ', &
     '      h2o2 + o --> ho2 + oh                                                                         ', &
     '       o + no3 --> no2                                                                              ', &
     '      oh + no3 --> no2 + ho2                                                                        ', &
     '     ho2 + no3 --> hno3                                                                             ', &
     '      o3 + no3 --> no2                                                                              ', &
     '         2 no3 --> 2 no2                                                                            ', &
     '           pna --> 0.61 no2 + 0.61 ho2 + 0.39 oh + 0.39 no3                                         ', &
     '          hno3 --> no2 + oh                                                                         ', &
     '          n2o5 --> no2 + no3                                                                        ', &
     '      xo2 + no --> no2                                                                              ', &
     '     xo2n + no --> ntr                                                                              ', &
     '     xo2 + ho2 --> rooh                                                                             ', &
     '    xo2n + ho2 --> rooh                                                                             ', &
     '         2 xo2 --> 0.21 M                                                                           ', &
     '        2 xo2n --> 0.21 M                                                                           ', &
     '    xo2n + xo2 --> 0.21 M                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '      ntr + oh --> hno3 - 0.66 par + 0.33 aldx + 0.33 ald2 + 0.33 form + ho2                        ', &
     '           ntr --> - 0.66 par + 0.33 aldx + 0.33 ald2 + 0.33 form + no2 + ho2                       ', &
     '     rooh + oh --> 0.5 aldx + 0.5 ald2 + xo2                                                        ', &
     '          rooh --> 0.5 aldx + 0.5 ald2 + ho2 + oh                                                   ', &
     '       co + oh --> ho2                                                                              ', &
     '      ch4 + oh --> meo2                                                                             ', &
     '     meo2 + no --> form + no2 + ho2                                                                 ', &
     '    ho2 + meo2 --> mepx                                                                             ', &
     '        2 meo2 --> 0.63 meoh + 1.37 form + 0.74 ho2                                                 ', &
     '     mepx + oh --> 0.3 xo2 + 0.3 ho2 + 0.7 meo2                                                     ', &
     '          mepx --> form + ho2 + oh                                                                  ', &
     '     meoh + oh --> form + ho2                                                                       ', &
     '     form + oh --> co + ho2                                                                         ', &
     '          form --> co + 2 ho2                                                                       ', &
     '          form --> co                                                                               ', &
     '      form + o --> co + ho2 + oh                                                                    ', &
     '    form + no3 --> hno3 + co + ho2                                                                  ', &
     '    form + ho2 --> hco3                                                                             ', &
     '          hco3 --> form + ho2                                                                       ', &
     '     hco3 + no --> facd + no2 + ho2                                                                 ', &
     '    hco3 + ho2 --> mepx                                                                             ', &
     '     facd + oh --> ho2                                                                              ', &
     '      ald2 + o --> c2o3 + oh                                                                        ', &
     '     ald2 + oh --> c2o3                                                                             ', &
     '    ald2 + no3 --> hno3 + c2o3                                                                      ', &
     '          ald2 --> co + ho2 + meo2                                                                  ', &
     '     c2o3 + no --> no2 + meo2                                                                       ', &
     '    no2 + c2o3 --> pan                                                                              ', &
     '           pan --> no2 + c2o3                                                                       ', &
     '           pan --> no2 + c2o3                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '    ho2 + c2o3 --> 0.8 pacd + 0.2 aacd + 0.2 o3                                                     ', &
     '   c2o3 + meo2 --> 0.1 aacd + form + 0.9 ho2 + 0.9 meo2                                             ', &
     '    xo2 + c2o3 --> 0.1 aacd + 0.9 meo2                                                              ', &
     '        2 c2o3 --> 2 meo2                                                                           ', &
     '     pacd + oh --> c2o3                                                                             ', &
     '          pacd --> meo2 + oh                                                                        ', &
     '     aacd + oh --> meo2                                                                             ', &
     '      aldx + o --> cxo3 + oh                                                                        ', &
     '     aldx + oh --> cxo3                                                                             ', &
     '    aldx + no3 --> hno3 + cxo3                                                                      ', &
     '          aldx --> co + ho2 + meo2                                                                  ', &
     '     cxo3 + no --> ald2 + no2 + xo2 + ho2                                                           ', &
     '    no2 + cxo3 --> panx                                                                             ', &
     '          panx --> no2 + cxo3                                                                       ', &
     '          panx --> no2 + cxo3                                                                       ', &
     '     panx + oh --> ald2 + no2                                                                       ', &
     '    ho2 + cxo3 --> 0.8 pacd + 0.2 aacd + 0.2 o3                                                     ', &
     '   meo2 + cxo3 --> 0.1 aacd + 0.9 ald2 + 0.1 form + 0.9 xo2 + ho2                                   ', &
     '    xo2 + cxo3 --> 0.1 aacd + 0.9 ald2                                                              ', &
     '        2 cxo3 --> 2 ald2 + 2 xo2 + 2 ho2                                                           ', &
     '   c2o3 + cxo3 --> ald2 + xo2 + ho2 + meo2                                                          ', &
     '      par + oh --> 0.76 ror + 0.13 xo2n - 0.11 par + 0.05 aldx + 0.06 ald2 + 0.87 xo2 + 0.11 ho2    ', &
     '           ror --> 0.02 ror + 0.04 xo2n - 2.1 par + 0.5 aldx + 0.6 ald2 + 0.96 xo2 + 0.94 ho2       ', &
     '           ror --> ho2                                                                              ', &
     '     ror + no2 --> ntr                                                                              ', &
     '       ole + o --> 0.2 co + 0.01 xo2n + 0.2 par + 0.3 aldx + 0.2 ald2 + 0.2 form + 0.2 xo2 + 0.3 ho2', &
     '      ole + oh --> - 0.7 par + 0.62 aldx + 0.33 ald2 + 0.8 form + 0.8 xo2 + 0.95 ho2                ', &
     '      ole + o3 --> 0.33 co - par + 0.32 aldx + 0.18 ald2 + 0.74 form + 0.22 xo2 + 0.44 ho2 + 0.1 oh ', &
     '     ole + no3 --> 0.09 xo2n - par + 0.56 aldx + 0.35 ald2 + form + no2 + 0.91 xo2                  ', &
     '       eth + o --> co + form + 0.7 xo2 + 1.7 ho2 + 0.3 oh                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '      eth + oh --> 0.22 aldx + 1.56 form + xo2 + ho2                                                ', &
     '      eth + o3 --> 0.37 facd + 0.63 co + form + 0.13 ho2 + 0.13 oh                                  ', &
     '     eth + no3 --> 2 form + no2 + xo2                                                               ', &
     '      iole + o --> 0.1 co + 0.1 par + 0.66 aldx + 1.24 ald2 + 0.1 xo2 + 0.1 ho2                     ', &
     '     iole + oh --> 0.7 aldx + 1.3 ald2 + xo2 + ho2                                                  ', &
     '     iole + o3 --> 0.25 co + 0.35 aldx + 0.65 ald2 + 0.25 form + 0.5 ho2 + 0.5 o + 0.5 oh           ', &
     '    iole + no3 --> 0.64 aldx + 1.18 ald2 + no2 + ho2                                                ', &
     '      tol + oh --> 0.071 tolaer1 + 0.138 tolaer2 + 0.56 to2 + 0.36 cres + 0.08 xo2 + 0.44 ho2       ', &
     '      to2 + no --> 0.9 open + 0.1 ntr + 0.9 no2 + 0.9 ho2                                           ', &
     '           to2 --> cres + ho2                                                                       ', &
     '     cres + oh --> cslaer + 0.4 cro + 0.3 open + 0.6 xo2 + 0.6 ho2                                  ', &
     '    cres + no3 --> cslaer + cro + hno3                                                              ', &
     '     cro + no2 --> ntr                                                                              ', &
     '     cro + ho2 --> cres                                                                             ', &
     '          open --> co + ho2 + c2o3                                                                  ', &
     '     open + oh --> 2 co + form + xo2 + 2 ho2 + c2o3                                                 ', &
     '     open + o3 --> 0.2 mgly + 0.69 co + 0.03 aldx + 0.7 form + 0.03 xo2 + 0.76 ho2 + 0.62 c2o3 + 0.0', &
     '      xyl + oh --> 0.038 xylaer1 + 0.167 xylaer2 + 0.3 to2 + 0.8 mgly + 0.2 cres + 1.1 par + 0.5 xo2', &
     '     mgly + oh --> xo2 + c2o3                                                                       ', &
     '          mgly --> co + ho2 + c2o3                                                                  ', &
     '      isop + o --> 0.232 isoaer1 + 0.0228 isoaer2 + 0.75 ispd + 0.5 form + 0.25 xo2 + 0.25 ho2 + 0.2', &
     '     isop + oh --> 0.232 isoaer1 + 0.0288 isoaer2 + 0.088 xo2n + 0.912 ispd + 0.629 form + 0.991 xo2', &
     '     isop + o3 --> 0.232 isoaer1 + 0.0288 isoaer2 + 0.066 co + 0.35 par + 0.65 ispd + 0.15 aldx + 0.', &
     '    isop + no3 --> 0.232 isoaer1 + 0.0288 isoaer2 + 0.2 ispd + 0.8 aldx + 0.8 ntr + 0.2 no2 + xo2 + ', &
     '     ispd + oh --> 0.168 mgly + 0.334 co + 1.565 par + 0.12 aldx + 0.252 ald2 + 0.167 form + 0.713 x', &
     '     ispd + o3 --> 0.85 mgly + 0.225 co + 0.36 par + 0.02 ald2 + 0.15 form + 0.064 xo2 + 0.154 ho2 +', &
     '    ispd + no3 --> 0.15 hno3 + 0.643 co + 1.282 par + 0.357 aldx + 0.85 ntr + 0.282 form + 0.075 xo2', &
     '          ispd --> 0.333 co + 0.832 par + 0.067 ald2 + 0.9 form + 0.7 xo2 + 1.033 ho2 + 0.967 c2o3  ', &
     '      terp + o --> terpaer + 5.12 par + 0.15 oh                                                     ', &
     '     terp + oh --> terpaer + 0.25 xo2n + 1.66 par + 0.47 aldx + 0.28 form + 1.25 xo2 + 0.75 ho2     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '     terp + o3 --> terpaer + 0.001 co + 0.18 xo2n + 7 par + 0.21 aldx + 0.24 form + 0.76 xo2 + 0.07 ', &
     '    terp + no3 --> terpaer + 0.25 xo2n + 0.47 aldx + 0.53 ntr + 0.47 no2 + 1.03 xo2 + 0.28 ho2      ', &
     '      so2 + oh --> sulf + sulaer + ho2                                                              ', &
     '     etoh + oh --> 0.05 aldx + 0.9 ald2 + 0.1 form + 0.1 xo2 + ho2                                  ', &
     '     etha + oh --> 0.009 xo2n + 0.991 ald2 + 0.991 xo2 + ho2                                        ', &
     '    isop + no2 --> 2.4 par + 0.2 ispd + 0.8 aldx + 0.8 ntr + xo2 + 0.8 ho2 + 0.2 no                 ', &
     '           cl2 --> 2 cl                                                                             ', &
     '          hocl --> cl + oh                                                                          ', &
     '       o3 + cl --> clo                                                                              ', &
     '         2 clo --> 0.3 cl2 + 1.4 cl                                                                 ', &
     '      clo + no --> no2 + cl                                                                         ', &
     '     clo + ho2 --> hocl                                                                             ', &
     '     fmcl + oh --> co + cl                                                                          ', &
     '          fmcl --> co + cl + ho2                                                                    ', &
     '      ch4 + cl --> hcl + meo2                                                                       ', &
     '      par + cl --> hcl + 0.76 ror + 0.13 xo2n - 0.11 par + 0.05 aldx + 0.06 ald2 + 0.87 xo2 + 0.11 h', &
     '     etha + cl --> hcl + 0.009 xo2n + 0.991 ald2 + 0.991 xo2 + ho2                                  ', &
     '      eth + cl --> fmcl + form + 2 xo2 + ho2                                                        ', &
     '      ole + cl --> fmcl - par + 0.67 aldx + 0.33 ald2 + 2 xo2 + ho2                                 ', &
     '     iole + cl --> 0.3 hcl + 0.7 fmcl + 0.3 ole + 0.3 par + 0.55 aldx + 0.45 ald2 + 1.7 xo2 + ho2   ', &
     '     isop + cl --> 0.15 hcl + 0.85 fmcl + ispd + xo2 + ho2                                          ', &
     '     form + cl --> hcl + co + ho2                                                                   ', &
     '     ald2 + cl --> hcl + c2o3                                                                       ', &
     '     aldx + cl --> hcl + cxo3                                                                       ', &
     '     meoh + cl --> hcl + form + ho2                                                                 ', &
     '     etoh + cl --> hcl + ald2 + ho2                                                                 ', &
     '      hcl + oh --> cl                                                                               ', &
     '      hg0 + o3 --> hg2                                                                              ', &
     '      hg0 + oh --> hg2                                                                              ', &
     '    hg0 + h2o2 --> hg2                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(11) :: EQN_NAMES_6 = (/ &
     '      hum + oh --> humaer + oh                                                                      ', &
     '      lim + oh --> 0.239 limaer1 + 0.363 limaer2 + oh                                               ', &
     '      oci + oh --> 0.045 ociaer1 + 0.149 ociaer2 + oh                                               ', &
     '     apin + oh --> 0.038 apinaer1 + 0.326 apinaer2 + oh                                             ', &
     '     apin + o3 --> 0.125 apinaer3 + 0.102 apinaer4 + o3                                             ', &
     '     bpin + oh --> 0.13 bpinaer1 + 0.0406 bpinaer2 + oh                                             ', &
     '     bpin + o3 --> 0.026 bpinaer3 + 0.485 bpinaer4 + o3                                             ', &
     '    bpin + no3 --> bpinaer5 + no3                                                                   ', &
     '      ter + oh --> 0.091 teraer1 + 0.367 teraer2 + oh                                               ', &
     '     alkh + oh --> 1.173 alkhaer1 + oh                                                              ', &
     '      pah + oh --> 0.156 pahaer1 + 0.777 pahaer2 + oh                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(191) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6 /)

! INLINED global variables

! End INLINED global variables


END MODULE cb05_sorg_aq_Monitor
