! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mozart_mosaic_4bin_aq_Monitor.f90
! Time                 : Tue Apr 12 23:43:03 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/mozart_mosaic_4bin_aq
! Equation file        : mozart_mosaic_4bin_aq.kpp
! Output root filename : mozart_mosaic_4bin_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mozart_mosaic_4bin_aq_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'HONO        ','SO4         ','NUME        ', &
     'DEN         ','CVASOAX     ','CVASOA1     ', &
     'CVASOA2     ','CVASOA3     ','CVASOA4     ', &
     'CVBSOAX     ','CVBSOA1     ','CVBSOA2     ', &
     'CVBSOA3     ','CVBSOA4     ','NH3         ', &
     'C2H6        ','C3H8        ','BIGENE      ', &
     'N2O         ','SO2         ','PBZNIT      ', &
     'H2O2        ','C2H2        ','BENZENE     ', &
     'BEPOMUC     ','PHENOL      ','TOLUENE     ', &
     'CRESOL      ','XOOH        ','EO          ', &
     'PHENOOH     ','C6H5OOH     ','BENZOOH     ', &
     'BIGALD2     ','TEPOMUC     ','BZOOH       ', &
     'BZALD       ','XYLOLOOH    ','XYLENOOH    ', &
     'N2O5        ','XYLENES     ','XYLOL       ', &
     'DMS         ','BIGALD4     ','C2H5OH      ', &
     'BIGALD3     ','BIGALD1     ','C2H5OOH     ', &
     'C3H7OOH     ','ROOH        ','ENEO2       ', &
     'MEKOOH      ','CH3OOH      ','MACROOH     ', &
     'H2          ','HO2NO2      ','HYDRALD     ', &
     'BIGALK      ','C2H4        ','EO2         ', &
     'TOLOOH      ','PHENO2      ','PHENO       ', &
     'BZOO        ','HOCH2OO     ','MEK         ', &
     'CH3COOH     ','CH3COOOH    ','TERPOOH     ', &
     'BENZO2      ','ONIT        ','POOH        ', &
     'PAN         ','XYLOLO2     ','HNO3        ', &
     'HMPROPO2    ','CH4         ','ACBZO2      ', &
     'MBOOOH      ','ISOPOOH     ','MPAN        ', &
     'HCOOH       ','TERP2OOH    ','O1D_CB4     ', &
     'C6H5O2      ','BPIN        ','APIN        ', &
     'ALKOOH      ','MEKO2       ','PO2         ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(52) :: SPC_NAMES_1 = (/ &
     'MALO2       ','MBO         ','TOLO2       ', &
     'XYLENO2     ','DICARBO2    ','O           ', &
     'C3H7O2      ','MDIALO2     ','GLYOXAL     ', &
     'CH3OH       ','BIGALD      ','C2H5O2      ', &
     'ISOPNO3     ','LIMON       ','MBONO3O2    ', &
     'HMPROP      ','MYRC        ','ISOP        ', &
     'BCARY       ','CH3COCH3    ','CO          ', &
     'GLYALD      ','C3H6        ','CH3CHO      ', &
     'TERPROD2    ','MBOO2       ','ALKO2       ', &
     'TERP2O2     ','TERPO2      ','ONITR       ', &
     'RO2         ','NTERPO2     ','MACR        ', &
     'TERPROD1    ','HYAC        ','CH3COCHO    ', &
     'XO2         ','MVK         ','MACRO2      ', &
     'CH2O        ','ISOPO2      ','MCO3        ', &
     'NO3         ','OH          ','HO2         ', &
     'O3          ','CH3CO3      ','NO2         ', &
     'NO          ','CH3O2       ','H2O         ', &
     'M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(142) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              M --> 2 O                                                                             ', &
     '             O3 --> O1D_CB4                                                                         ', &
     '             O3 --> O                                                                               ', &
     '            N2O --> O1D_CB4                                                                         ', &
     '            NO2 --> O + NO                                                                          ', &
     '           N2O5 --> NO3 + NO2                                                                       ', &
     '           HNO3 --> OH + NO2                                                                        ', &
     '            NO3 --> 0.89 O3 + 0.89 NO2 + 0.11 NO                                                    ', &
     '         HO2NO2 --> 0.33 NO3 + 0.33 OH + 0.66 HO2 + 0.66 NO2                                        ', &
     '         CH3OOH --> CH2O + OH + HO2                                                                 ', &
     '           CH2O --> CO + 2 HO2                                                                      ', &
     '           CH2O --> H2 + CO                                                                         ', &
     '           H2O2 --> 2 OH                                                                            ', &
     '         CH3CHO --> CO + HO2 + CH3O2                                                                ', &
     '           POOH --> CH3CHO + CH2O + OH + HO2                                                        ', &
     '       CH3COOOH --> OH + CH3O2                                                                      ', &
     '            PAN --> 0.4 NO3 + 0.6 CH3CO3 + 0.6 NO2 + 0.4 CH3O2                                      ', &
     '           MPAN --> MCO3 + NO2                                                                      ', &
     '           MACR --> 0.67 CO + 0.67 CH2O + 0.33 MCO3 + 0.33 OH + 0.67 HO2 + 0.67 CH3CO3              ', &
     '            MVK --> 0.7 CO + 0.7 C3H6 + 0.3 CH3CO3 + 0.3 CH3O2                                      ', &
     '        C2H5OOH --> CH3CHO + OH + HO2                                                               ', &
     '        C3H7OOH --> 0.82 CH3COCH3 + OH + HO2                                                        ', &
     '           ROOH --> CH2O + OH + CH3CO3                                                              ', &
     '       CH3COCH3 --> CH3CO3 + CH3O2                                                                  ', &
     '       CH3COCHO --> CO + HO2 + CH3CO3                                                               ', &
     '           XOOH --> OH                                                                              ', &
     '          ONITR --> CO + CH2O + HO2 + NO2                                                           ', &
     '        ISOPOOH --> 0.288 MACR + 0.402 MVK + 0.69 CH2O + HO2                                        ', &
     '           HYAC --> CH2O + HO2 + CH3CO3                                                             ', &
     '         GLYALD --> CO + CH2O + 2 HO2                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '            MEK --> C2H5O2 + CH3CO3                                                                 ', &
     '         BIGALD --> 0.13 GLYOXAL + 0.45 CO + 0.18 CH3COCHO + 0.56 HO2 + 0.13 CH3CO3                 ', &
     '        GLYOXAL --> 2 CO + 2 HO2                                                                    ', &
     '         ALKOOH --> 0.8 MEK + 0.25 CH3COCH3 + 0.4 CH3CHO + 0.1 CH2O + OH + 0.9 HO2                  ', &
     '         MEKOOH --> CH3CHO + OH + CH3CO3                                                            ', &
     '         TOLOOH --> 0.45 GLYOXAL + 0.9 BIGALD + 0.45 CH3COCHO + OH                                  ', &
     '        BIGALD1 --> 0.6 MALO2 + HO2                                                                 ', &
     '        BEPOMUC --> BIGALD1 + 1.5 CO + 1.5 HO2                                                      ', &
     '        TEPOMUC --> 1.5 CO + HO2 + 0.5 CH3CO3                                                       ', &
     '        BIGALD2 --> 0.6 DICARBO2 + 0.6 HO2                                                          ', &
     '        BIGALD3 --> 0.6 MDIALO2 + 0.6 CO + 0.6 HO2                                                  ', &
     '        BIGALD4 --> CO + CH3COCHO + HO2 + CH3CO3                                                    ', &
     '         MBOOOH --> 0.33 HMPROP + 0.67 CH3COCH3 + 0.67 GLYALD + 0.33 CH2O + OH + HO2                ', &
     '         HMPROP --> CH3COCH3 + CO + 2 HO2                                                           ', &
     '       TERPROD1 --> CO + TERPROD2 + HO2                                                             ', &
     '       TERPROD2 --> 0.5 CH3COCH3 + 1.7 CO + 0.15 RO2 + 0.68 CH2O + 1.2 HO2 + 0.65 CH3CO3            ', &
     '        TERPOOH --> 0.05 CH3COCH3 + TERPROD1 + 0.4 CH2O + OH + HO2                                  ', &
     '       TERP2OOH --> 0.3 CH3COCH3 + 0.25 CO + 0.25 GLYALD + TERPROD2 + 0.375 CH2O + OH + HO2         ', &
     '           HONO --> OH + NO                                                                         ', &
     '          O + M --> O3                                                                              ', &
     '         O + O3 --> M                                                                               ', &
     '    O1D_CB4 + M --> O                                                                               ', &
     '  O1D_CB4 + H2O --> 2 OH                                                                            ', &
     '   H2 + O1D_CB4 --> OH + HO2                                                                        ', &
     '        H2 + OH --> HO2 + H2O                                                                       ', &
     '         O + OH --> HO2                                                                             ', &
     '        O + HO2 --> OH                                                                              ', &
     '        OH + O3 --> HO2                                                                             ', &
     '       HO2 + O3 --> OH                                                                              ', &
     '    2 HO2 + H2O --> H2O2                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '      H2O2 + OH --> HO2 + H2O                                                                       ', &
     '       OH + HO2 --> H2O                                                                             ', &
     '           2 OH --> O + H2O                                                                         ', &
     '           2 OH --> H2O2                                                                            ', &
     '  N2O + O1D_CB4 --> 2 NO                                                                            ', &
     '  N2O + O1D_CB4 --> M                                                                               ', &
     '       HO2 + NO --> OH + NO2                                                                        ', &
     '        O3 + NO --> NO2                                                                             ', &
     '        O + NO2 --> NO                                                                              ', &
     '       O3 + NO2 --> NO3                                                                             ', &
     '      NO3 + HO2 --> OH + NO2                                                                        ', &
     '      NO3 + NO2 --> N2O5                                                                            ', &
     '           N2O5 --> NO3 + NO2                                                                       ', &
     '       OH + NO2 --> HNO3                                                                            ', &
     '      HNO3 + OH --> NO3 + H2O                                                                       ', &
     '       NO3 + NO --> 2 NO2                                                                           ', &
     '      HO2 + NO2 --> HO2NO2                                                                          ', &
     '    HO2NO2 + OH --> NO2 + H2O                                                                       ', &
     '         HO2NO2 --> HO2 + NO2                                                                       ', &
     '       N2O5 + M --> 2 HNO3                                                                          ', &
     '            NO3 --> HNO3                                                                            ', &
     '            NO2 --> 0.5 HNO3 + 0.5 OH + 0.5 NO                                                      ', &
     '       CH4 + OH --> CH3O2 + H2O                                                                     ', &
     '  CH4 + O1D_CB4 --> 0.05 H2 + 0.25 CH2O + 0.75 OH + 0.4 HO2 + 0.75 CH3O2                            ', &
     '     NO + CH3O2 --> NUME + CH2O + HO2 + NO2                                                         ', &
     '        2 CH3O2 --> DEN + 2 CH2O + 2 HO2                                                            ', &
     '        2 CH3O2 --> DEN + CH3OH + CH2O                                                              ', &
     '    HO2 + CH3O2 --> DEN + CH3OOH                                                                    ', &
     '    CH3OOH + OH --> 0.3 CH2O + 0.3 OH + 0.7 CH3O2 + H2O                                             ', &
     '     CH2O + NO3 --> HNO3 + CO + HO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '      CH2O + OH --> CO + HO2 + H2O                                                                  ', &
     '        CO + OH --> HO2                                                                             ', &
     '      C2H4 + OH --> 0.75 EO2 + 0.5 CH2O + 0.25 HO2                                                  ', &
     '      C2H4 + O3 --> 0.5 HCOOH + 0.5 CO + CH2O + 0.12 OH + 0.12 HO2                                  ', &
     '       SO2 + OH --> SO4                                                                             ', &
     '   GLYOXAL + OH --> CO + HO2                                                                        ', &
     '       EO2 + NO --> NUME + EO + NO2                                                                 ', &
     '         EO + M --> GLYALD + HO2                                                                    ', &
     '             EO --> 2 CH2O + HO2                                                                    ', &
     '      C2H6 + OH --> C2H5O2                                                                          ', &
     '    C2H5O2 + NO --> NUME + CH3CHO + HO2 + NO2                                                       ', &
     '   C2H5O2 + HO2 --> DEN + C2H5OOH                                                                   ', &
     ' C2H5O2 + CH3O2 --> DEN + 0.2 C2H5OH + 0.3 CH3OH + 0.8 CH3CHO + 0.7 CH2O + HO2                      ', &
     '   C2H5OOH + OH --> 0.5 C2H5O2 + 0.5 CH3CHO + 0.5 OH                                                ', &
     '      C3H6 + OH --> PO2                                                                             ', &
     '      C3H6 + O3 --> 0.25 CH3COOH + 0.08 CH4 + 0.56 CO + 0.5 CH3CHO + 0.54 CH2O + 0.33 OH + 0.19 HO2 ', &
     '     C3H6 + NO3 --> ONIT                                                                            ', &
     '       PO2 + NO --> NUME + CH3CHO + CH2O + HO2 + NO2                                                ', &
     '      PO2 + HO2 --> DEN + POOH                                                                      ', &
     '      POOH + OH --> 0.5 PO2 + 0.5 HYAC + 0.5 OH                                                     ', &
     '    CH3CHO + OH --> CH3CO3                                                                          ', &
     '   CH3CHO + NO3 --> HNO3 + CH3CO3                                                                   ', &
     '    CH3CO3 + NO --> NUME + NO2 + CH3O2                                                              ', &
     '   CH3CO3 + NO2 --> PAN                                                                             ', &
     '   HO2 + CH3CO3 --> DEN + 0.25 CH3COOH + 0.75 CH3COOOH + 0.25 O3                                    ', &
     ' CH3CO3 + CH3O2 --> DEN + 0.1 CH3COOH + CH2O + 0.9 HO2 + 0.9 CH3O2                                  ', &
     '  CH3COOOH + OH --> 0.5 CH2O + 0.5 CH3CO3                                                           ', &
     '            PAN --> CH3CO3 + NO2                                                                    ', &
     '       2 CH3CO3 --> DEN + 2 CH3O2                                                                   ', &
     '      C3H8 + OH --> C3H7O2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    C3H7O2 + NO --> NUME + 0.82 CH3COCH3 + 0.27 CH3CHO + HO2 + NO2                                  ', &
     '   C3H7O2 + HO2 --> DEN + C3H7OOH                                                                   ', &
     ' C3H7O2 + CH3O2 --> DEN + 0.82 CH3COCH3 + CH2O + HO2                                                ', &
     '   C3H7OOH + OH --> C3H7O2                                                                          ', &
     '  CH3COCH3 + OH --> RO2                                                                             ', &
     '       RO2 + NO --> NUME + CH2O + CH3CO3 + NO2                                                      ', &
     '      RO2 + HO2 --> DEN + ROOH                                                                      ', &
     '    RO2 + CH3O2 --> DEN + 0.5 CH3OH + 0.2 HYAC + 0.5 CH3COCHO + 0.8 CH2O + 0.3 HO2 + 0.3 CH3CO3     ', &
     '      ROOH + OH --> RO2                                                                             ', &
     '    BIGENE + OH --> ENEO2                                                                           ', &
     '    BIGENE + OH --> CVASOA4 + BIGENE + OH                                                           ', &
     '    BIGENE + OH --> CVASOA3 + BIGENE + OH                                                           ', &
     '    BIGENE + OH --> CVASOA2 + BIGENE + OH                                                           ', &
     '    BIGENE + OH --> CVASOA1 + BIGENE + OH                                                           ', &
     '     ENEO2 + NO --> NUME + 0.5 CH3COCH3 + CH3CHO + 0.5 CH2O + HO2 + NO2                             ', &
     '    BIGALK + OH --> ALKO2                                                                           ', &
     '    BIGALK + OH --> CVASOA4 + BIGALK + OH                                                           ', &
     '    BIGALK + OH --> CVASOA3 + BIGALK + OH                                                           ', &
     '    BIGALK + OH --> CVASOA2 + BIGALK + OH                                                           ', &
     '    BIGALK + OH --> CVASOA1 + BIGALK + OH                                                           ', &
     '     ALKO2 + NO --> NUME + 0.75 MEK + 0.1 ONIT + 0.25 CH3COCH3 + 0.4 CH3CHO + 0.1 CH2O + 0.9 HO2 + 0', &
     '    ALKO2 + HO2 --> DEN + ALKOOH                                                                    ', &
     '    ALKOOH + OH --> ALKO2                                                                           ', &
     '      ONIT + OH --> CH3COCHO + NO2                                                                  ', &
     '       MEK + OH --> MEKO2                                                                           ', &
     '     MEKO2 + NO --> NUME + CH3CHO + CH3CO3 + NO2                                                    ', &
     '    MEKO2 + HO2 --> DEN + MEKOOH                                                                    ', &
     '    MEKOOH + OH --> MEKO2                                                                           ', &
     '    TOLO2 + HO2 --> DEN + TOLOOH                                                                    ', &
     '    TOLOOH + OH --> TOLO2                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '      ISOP + OH --> ISOPO2                                                                          ', &
     '      ISOP + OH --> CVBSOA4 + ISOP + OH                                                             ', &
     '      ISOP + OH --> CVBSOA3 + ISOP + OH                                                             ', &
     '      ISOP + OH --> CVBSOA2 + ISOP + OH                                                             ', &
     '      ISOP + OH --> CVBSOA1 + ISOP + OH                                                             ', &
     '      ISOP + O3 --> 0.2 CH3COOH + 0.3 CO + 0.07 C3H6 + 0.4 MACR + 0.2 MVK + 0.6 CH2O + 0.2 MCO3 + 0.', &
     '      ISOP + O3 --> CVBSOA4 + ISOP + O3                                                             ', &
     '      ISOP + O3 --> CVBSOA3 + ISOP + O3                                                             ', &
     '      ISOP + O3 --> CVBSOA2 + ISOP + O3                                                             ', &
     '      ISOP + O3 --> CVBSOA1 + ISOP + O3                                                             ', &
     '    ISOPO2 + NO --> NUME + 0.33 HYDRALD + 0.02 GLYOXAL + 0.02 GLYALD + 0.08 ONITR + 0.23 MACR + 0.02', &
     '   ISOPO2 + NO3 --> 0.36 HYDRALD + 0.02 GLYOXAL + 0.02 GLYALD + 0.25 MACR + 0.02 HYAC + 0.02 CH3COCH', &
     '   ISOPO2 + HO2 --> DEN + ISOPOOH                                                                   ', &
     '   ISOPOOH + OH --> 0.5 XO2 + 0.5 ISOPO2                                                            ', &
     ' ISOPO2 + CH3O2 --> DEN + 0.3 HYDRALD + 0.25 CH3OH + 0.19 MACR + 0.26 MVK + 1.2 CH2O + HO2          ', &
     'ISOPO2 + CH3CO3 --> DEN + 0.4 HYDRALD + 0.25 MACR + 0.35 MVK + 0.6 CH2O + HO2 + CH3O2               ', &
     '       MVK + OH --> MACRO2                                                                          ', &
     '       MVK + O3 --> 0.05 CO + 0.04 CH3CHO + 0.95 CH3COCHO + 0.8 CH2O + 0.08 OH + 0.06 HO2 + 0.2 O3  ', &
     '      MACR + OH --> 0.5 MACRO2 + 0.5 MCO3                                                           ', &
     '      MACR + O3 --> 0.2 CO + 0.8 CH3COCHO + 0.7 CH2O + 0.215 OH + 0.275 HO2 + 0.2 O3                ', &
     '    MACRO2 + NO --> NUME + 0.22 CO + 0.53 GLYALD + 0.22 HYAC + 0.25 CH3COCHO + 0.25 CH2O + 0.47 HO2 ', &
     '    MACRO2 + NO --> NUME + 0.8 ONITR                                                                ', &
     '   MACRO2 + NO3 --> 0.22 CO + 0.53 GLYALD + 0.22 HYAC + 0.25 CH3COCHO + 0.25 CH2O + 0.47 HO2 + 0.53 ', &
     '   MACRO2 + HO2 --> DEN + MACROOH                                                                   ', &
     ' MACRO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.11 CO + 0.26 GLYALD + 0.23 HYAC + 0.24 CH3COCHO + 0.88 CH2O', &
     'MACRO2 + CH3CO3 --> DEN + 0.22 CO + 0.53 GLYALD + 0.22 HYAC + 0.25 CH3COCHO + 0.25 CH2O + 0.47 HO2 +', &
     '   MACROOH + OH --> 0.2 MACRO2 + 0.5 MCO3 + 0.1 OH + 0.2 HO2                                        ', &
     '      MCO3 + NO --> NUME + CH2O + CH3CO3 + NO2                                                      ', &
     '     MCO3 + NO3 --> CH2O + CH3CO3 + NO2                                                             ', &
     '     MCO3 + HO2 --> DEN + 0.25 CH3COOH + 0.75 CH3COOOH + 0.25 O3                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '   MCO3 + CH3O2 --> DEN + 2 CH2O + HO2 + CH3CO3                                                     ', &
     '  MCO3 + CH3CO3 --> DEN + CH2O + CH3CO3 + CH3O2                                                     ', &
     '         2 MCO3 --> DEN + 2 CH2O + 2 CH3CO3                                                         ', &
     ' MCO3 + NO2 + M --> MPAN                                                                            ', &
     '       MPAN + M --> MCO3 + NO2                                                                      ', &
     '   BENZENE + OH --> 0.12 BEPOMUC + 0.53 PHENOL + 0.35 BENZO2 + 0.65 HO2                             ', &
     '   BENZENE + OH --> CVASOA4 + BENZENE + OH                                                          ', &
     '   BENZENE + OH --> CVASOA3 + BENZENE + OH                                                          ', &
     '   BENZENE + OH --> CVASOA2 + BENZENE + OH                                                          ', &
     '   BENZENE + OH --> CVASOA1 + BENZENE + OH                                                          ', &
     '    PHENOL + OH --> 0.14 PHENO2 + 0.06 PHENO + 0.8 HO2                                              ', &
     '    PHENO2 + NO --> NUME + 0.7 GLYOXAL + HO2 + NO2                                                  ', &
     '   PHENO2 + HO2 --> DEN + PHENOOH                                                                   ', &
     '   PHENOOH + OH --> PHENO2                                                                          ', &
     '    PHENO + NO2 --> M                                                                               ', &
     '     PHENO + O3 --> C6H5O2                                                                          ', &
     '    C6H5O2 + NO --> NUME + PHENO + NO2                                                              ', &
     '   C6H5O2 + HO2 --> DEN + C6H5OOH                                                                   ', &
     '   C6H5OOH + OH --> C6H5O2                                                                          ', &
     '    BENZO2 + NO --> NUME + 0.5 BIGALD1 + GLYOXAL + HO2 + NO2                                        ', &
     '   BENZO2 + HO2 --> DEN + BENZOOH                                                                   ', &
     '   BENZOOH + OH --> BENZO2                                                                          ', &
     '    MALO2 + NO2 --> M                                                                               ', &
     '     MALO2 + NO --> NUME + 0.4 GLYOXAL + 0.4 CO + 0.4 HO2                                           ', &
     '    MALO2 + HO2 --> DEN + 0.16 GLYOXAL + 0.16 CO + 0.16 HO2                                         ', &
     '   TOLUENE + OH --> 0.18 CRESOL + 0.1 TEPOMUC + 0.07 BZOO + 0.65 TOLO2 + 0.28 HO2                   ', &
     '   TOLUENE + OH --> CVASOA4 + TOLUENE + OH                                                          ', &
     '   TOLUENE + OH --> CVASOA3 + TOLUENE + OH                                                          ', &
     '   TOLUENE + OH --> CVASOA2 + TOLUENE + OH                                                          ', &
     '   TOLUENE + OH --> CVASOA1 + TOLUENE + OH                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '    CRESOL + OH --> 0.2 PHENO2 + 0.07 PHENO + 0.73 HO2                                              ', &
     '     BZOO + HO2 --> DEN + BZOOH                                                                     ', &
     '     BZOOH + OH --> BZOO                                                                            ', &
     '      BZOO + NO --> NUME + BZALD + HO2 + NO2                                                        ', &
     '     BZALD + OH --> ACBZO2                                                                          ', &
     '   ACBZO2 + NO2 --> PBZNIT                                                                          ', &
     '         PBZNIT --> ACBZO2 + NO2                                                                    ', &
     '    ACBZO2 + NO --> NUME + C6H5O2 + NO2                                                             ', &
     '   ACBZO2 + HO2 --> DEN + 0.4 C6H5O2 + 0.4 OH                                                       ', &
     '     TOLO2 + NO --> NUME + 0.2 BIGALD2 + 0.2 BIGALD3 + 0.2 BIGALD1 + 0.6 GLYOXAL + 0.4 CH3COCHO + HO', &
     ' DICARBO2 + HO2 --> DEN + 0.07 CO + 0.07 CH3COCHO + 0.4 OH + 0.07 HO2 + 0.33 CH3O2                  ', &
     '  DICARBO2 + NO --> NUME + 0.17 CO + 0.17 CH3COCHO + 0.17 HO2 + NO2 + 0.83 CH3O2                    ', &
     '  MDIALO2 + HO2 --> DEN + 0.07 GLYOXAL + 0.14 CO + 0.07 CH3COCHO + 0.4 OH + 0.33 HO2 + 0.07 CH3O2   ', &
     '   MDIALO2 + NO --> NUME + 0.17 GLYOXAL + 0.35 CO + 0.17 CH3COCHO + 0.83 HO2 + NO2 + 0.17 CH3O2     ', &
     ' DICARBO2 + NO2 --> M                                                                               ', &
     '  MDIALO2 + NO2 --> M                                                                               ', &
     '   XYLENES + OH --> 0.23 TEPOMUC + 0.15 XYLOL + 0.06 BZOO + 0.56 XYLENO2 + 0.38 HO2                 ', &
     '   XYLENES + OH --> CVASOA4 + XYLENES + OH                                                          ', &
     '   XYLENES + OH --> CVASOA3 + XYLENES + OH                                                          ', &
     '   XYLENES + OH --> CVASOA2 + XYLENES + OH                                                          ', &
     '   XYLENES + OH --> CVASOA1 + XYLENES + OH                                                          ', &
     '     XYLOL + OH --> 0.07 PHENO + 0.3 XYLOLO2 + 0.63 HO2                                             ', &
     '   XYLOLO2 + NO --> NUME + 0.17 GLYOXAL + 0.51 CH3COCHO + HO2 + NO2                                 ', &
     '  XYLOLO2 + HO2 --> DEN + XYLOLOOH                                                                  ', &
     '  XYLOLOOH + OH --> XYLOLO2                                                                         ', &
     '  XYLENO2 + HO2 --> DEN + XYLENOOH                                                                  ', &
     '  XYLENOOH + OH --> XYLENO2                                                                         ', &
     '   XYLENO2 + NO --> NUME + 0.2 BIGALD2 + 0.21 BIGALD4 + 0.15 BIGALD3 + 0.06 BIGALD1 + 0.34 GLYOXAL +', &
     '      APIN + OH --> TERPO2                                                                          ', &
     '      APIN + OH --> CVBSOA4 + APIN + OH                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '      APIN + OH --> CVBSOA3 + APIN + OH                                                             ', &
     '      APIN + OH --> CVBSOA2 + APIN + OH                                                             ', &
     '      APIN + OH --> CVBSOA1 + APIN + OH                                                             ', &
     '      BPIN + OH --> TERPO2                                                                          ', &
     '      BPIN + OH --> CVBSOA4 + BPIN + OH                                                             ', &
     '      BPIN + OH --> CVBSOA3 + BPIN + OH                                                             ', &
     '      BPIN + OH --> CVBSOA2 + BPIN + OH                                                             ', &
     '      BPIN + OH --> CVBSOA1 + BPIN + OH                                                             ', &
     '     LIMON + OH --> TERPO2                                                                          ', &
     '     LIMON + OH --> CVBSOA4 + LIMON + OH                                                            ', &
     '     LIMON + OH --> CVBSOA3 + LIMON + OH                                                            ', &
     '     LIMON + OH --> CVBSOA2 + LIMON + OH                                                            ', &
     '     LIMON + OH --> CVBSOA1 + LIMON + OH                                                            ', &
     '      MYRC + OH --> TERPO2                                                                          ', &
     '     BCARY + OH --> TERPO2                                                                          ', &
     '      APIN + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.3 TERPROD2 +', &
     '      APIN + O3 --> CVBSOA4 + APIN + O3                                                             ', &
     '      APIN + O3 --> CVBSOA3 + APIN + O3                                                             ', &
     '      APIN + O3 --> CVBSOA2 + APIN + O3                                                             ', &
     '      APIN + O3 --> CVBSOA1 + APIN + O3                                                             ', &
     '      BPIN + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.3 TERPROD2 +', &
     '      BPIN + O3 --> CVBSOA4 + BPIN + O3                                                             ', &
     '      BPIN + O3 --> CVBSOA3 + BPIN + O3                                                             ', &
     '      BPIN + O3 --> CVBSOA2 + BPIN + O3                                                             ', &
     '      BPIN + O3 --> CVBSOA1 + BPIN + O3                                                             ', &
     '     LIMON + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.3 TERPROD2 +', &
     '     LIMON + O3 --> CVBSOA4 + LIMON + O3                                                            ', &
     '     LIMON + O3 --> CVBSOA3 + LIMON + O3                                                            ', &
     '     LIMON + O3 --> CVBSOA2 + LIMON + O3                                                            ', &
     '     LIMON + O3 --> CVBSOA1 + LIMON + O3                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '      MYRC + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.3 TERPROD2 +', &
     '     BCARY + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.3 TERPROD2 +', &
     '    LIMON + NO3 --> NTERPO2                                                                         ', &
     '     MYRC + NO3 --> NTERPO2                                                                         ', &
     '    BCARY + NO3 --> NTERPO2                                                                         ', &
     '    TERPO2 + NO --> NUME + 0.045 CH3COCH3 + 0.1 ONITR + 0.9 TERPROD1 + 0.36 CH2O + 0.9 HO2 + 0.9 NO2', &
     '   TERPO2 + HO2 --> DEN + TERPOOH                                                                   ', &
     ' TERPO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.025 CH3COCH3 + TERPROD1 + 0.95 CH2O + HO2                  ', &
     '   TERPOOH + OH --> TERPO2                                                                          ', &
     '  TERP2OOH + OH --> TERP2O2                                                                         ', &
     '  TERPROD1 + OH --> TERP2O2                                                                         ', &
     ' TERPROD1 + NO3 --> 0.5 TERP2O2 + 0.5 NTERPO2                                                       ', &
     '   TERP2O2 + NO --> NUME + 0.27 CH3COCH3 + 0.225 CO + 0.225 GLYALD + 0.9 TERPROD2 + 0.1 ONITR + 0.34', &
     '  TERP2O2 + HO2 --> DEN + TERP2OOH                                                                  ', &
     'TERP2O2 + CH3O2 --> DEN + 0.25 CH3OH + 0.15 CH3COCH3 + 0.125 CO + 0.125 GLYALD + TERPROD2 + 0.93 CH2', &
     '  TERPROD2 + OH --> 0.5 CH3COCH3 + 0.7 CO + 0.15 RO2 + 0.68 CH2O + 0.2 HO2 + 0.65 CH3CO3            ', &
     '   NTERPO2 + NO --> NUME + 0.1 ONITR + 0.9 TERPROD1 + 1.9 NO2                                       ', &
     '  NTERPO2 + HO2 --> DEN + ONITR                                                                     ', &
     'NTERPO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.5 ONITR + 0.5 TERPROD1 + 0.75 CH2O + 0.5 HO2 + 0.5 NO2     ', &
     '  NTERPO2 + NO3 --> TERPROD1 + 2 NO2                                                                ', &
     '   CH3COOH + OH --> CH3O2                                                                           ', &
     '     ISOP + NO3 --> ISOPNO3                                                                         ', &
     '   ISOPNO3 + NO --> NUME + 0.794 ONITR + 0.167 MACR + 0.039 MVK + 0.072 CH2O + 0.794 HO2 + 1.206 NO2', &
     '  ISOPNO3 + NO3 --> 0.794 ONITR + 0.167 MACR + 0.039 MVK + 0.072 CH2O + 0.794 HO2 + 1.206 NO2       ', &
     '  ISOPNO3 + HO2 --> DEN + 0.794 ONITR + 0.167 MACR + 0.039 MVK + 0.206 CH2O + 0.206 OH + 0.206 NO2  ', &
     '  CH3COCHO + OH --> CO + CH3CO3                                                                     ', &
     ' CH3COCHO + NO3 --> HNO3 + CO + CH3CO3                                                              ', &
     '     ONITR + OH --> HYDRALD + HO2 + 0.4 NO2                                                         ', &
     '    ONITR + NO3 --> HYDRALD + HO2 + NO2                                                             ', &
     '   HYDRALD + OH --> XO2                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '       XO2 + NO --> NUME + 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 HYAC + 0.25 CH3COCHO + 0.25 C', &
     '      XO2 + NO3 --> 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 HYAC + 0.25 CH3COCHO + 0.25 CH2O + H', &
     '      XO2 + HO2 --> DEN + XOOH                                                                      ', &
     '    XO2 + CH3O2 --> DEN + 0.1 GLYOXAL + 0.3 CH3OH + 0.2 CO + 0.1 GLYALD + 0.1 HYAC + 0.1 CH3COCHO + ', &
     '   XO2 + CH3CO3 --> DEN + 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 HYAC + 0.25 CH3COCHO + 0.25 CH', &
     '      XOOH + OH --> XO2                                                                             ', &
     '      XOOH + OH --> OH                                                                              ', &
     '     CH3OH + OH --> CH2O + HO2                                                                      ', &
     '    C2H5OH + OH --> CH3CHO + HO2                                                                    ', &
     '      MPAN + OH --> 0.5 HYAC + 0.5 CH2O + 0.5 NO3 + 0.5 HO2                                         ', &
     '       PAN + OH --> CH2O + NO3                                                                      ', &
     '      HYAC + OH --> CH3COCHO + HO2                                                                  ', &
     '    GLYALD + OH --> 0.2 GLYOXAL + 0.8 CH2O + HO2                                                    ', &
     '       DMS + OH --> SO2                                                                             ', &
     '       DMS + OH --> 0.5 SO2 + 0.5 HO2                                                               ', &
     '      DMS + NO3 --> SO2 + HNO3                                                                      ', &
     '       NH3 + OH --> M                                                                               ', &
     '            HO2 --> 0.5 H2O2                                                                        ', &
     '       2 C2H5O2 --> DEN + 0.4 C2H5OH + 1.6 CH3CHO + 1.2 HO2                                         ', &
     '       MBO + OH --> MBOO2                                                                           ', &
     '     MBOO2 + NO --> NUME + 0.33 HMPROP + 0.67 CH3COCH3 + 0.67 GLYALD + 0.33 CH2O + HO2 + NO2        ', &
     '  MBOO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.167 HMPROP + 0.333 CH3COCH3 + 0.333 GLYALD + 0.917 CH2O + H', &
     '    HMPROP + OH --> HMPROPO2                                                                        ', &
     '  HMPROPO2 + NO --> NUME + CH3COCH3 + HO2 + NO2                                                     ', &
     ' HMPROPO2 + HO2 --> DEN + 0.4 CH3COCH3 + 0.4 OH + 0.4 HO2                                           ', &
     '    MBOO2 + HO2 --> DEN + MBOOOH                                                                    ', &
     '    MBOOOH + OH --> 0.5 MBOO2 + 0.5 OH                                                              ', &
     '       MBO + O3 --> 0.25 HCOOH + 0.9 HMPROP + 0.1 CH3COCH3 + 0.35 CO + 0.5 CH2O + 0.06 OH + 0.06 HO2', &
     '      MBO + NO3 --> MBONO3O2                                                                        ', &
     ' MBONO3O2 + HO2 --> DEN                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(16) :: EQN_NAMES_11 = (/ &
     '  MBONO3O2 + NO --> NUME + 0.75 ONIT + 0.25 HMPROP + 0.75 CH3COCH3 + 0.25 CH2O + 0.75 HO2 + 1.25 NO2', &
     ' MBONO3O2 + NO3 --> 0.75 ONIT + 0.25 HMPROP + 0.75 CH3COCH3 + 0.25 CH2O + 0.75 HO2 + 1.25 NO2       ', &
     '      C2H2 + OH --> 0.35 HCOOH + 0.65 GLYOXAL + 0.35 CO + 0.65 OH + 0.35 HO2                        ', &
     '     HCOOH + OH --> HO2 + H2O                                                                       ', &
     '     CH2O + HO2 --> HOCH2OO                                                                         ', &
     '        HOCH2OO --> CH2O + HO2                                                                      ', &
     '   HOCH2OO + NO --> NUME + HCOOH + HO2 + NO2                                                        ', &
     '  HOCH2OO + HO2 --> DEN + HCOOH                                                                     ', &
     '   CVASOA4 + OH --> 1.075 CVASOA3 + OH                                                              ', &
     '   CVASOA3 + OH --> 1.075 CVASOA2 + OH                                                              ', &
     '   CVASOA2 + OH --> 1.075 CVASOA1 + OH                                                              ', &
     '   CVASOA1 + OH --> 1.075 CVASOAX + OH                                                              ', &
     '   CVBSOA4 + OH --> 1.075 CVBSOA3 + OH                                                              ', &
     '   CVBSOA3 + OH --> 1.075 CVBSOA2 + OH                                                              ', &
     '   CVBSOA2 + OH --> 1.075 CVBSOA1 + OH                                                              ', &
     '   CVBSOA1 + OH --> 1.075 CVBSOAX + OH                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(346) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11 /)

! INLINED global variables

! End INLINED global variables


END MODULE mozart_mosaic_4bin_aq_Monitor
