! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbmz_mosaic_LinearAlgebra.f90
! Time                 : Thu Apr 14 13:13:32 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/cbmz_mosaic
! Equation file        : cbmz_mosaic.kpp
! Output root filename : cbmz_mosaic
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbmz_mosaic_LinearAlgebra

  USE cbmz_mosaic_Parameters
  USE cbmz_mosaic_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(4)
  XX(3) = X(3)/JVS(5)
  XX(4) = X(4)/JVS(6)
  XX(5) = X(5)/JVS(10)
  XX(6) = X(6)/JVS(18)
  XX(7) = X(7)/JVS(24)
  XX(8) = X(8)/JVS(30)
  XX(9) = X(9)/JVS(33)
  XX(10) = X(10)/JVS(39)
  XX(11) = X(11)/JVS(43)
  XX(12) = X(12)/JVS(47)
  XX(13) = X(13)/JVS(51)
  XX(14) = (X(14)-JVS(2)*XX(1))/(JVS(55))
  XX(15) = X(15)/JVS(57)
  XX(16) = X(16)/JVS(59)
  XX(17) = X(17)/JVS(61)
  XX(18) = X(18)/JVS(64)
  XX(19) = (X(19)-JVS(19)*XX(6)-JVS(25)*XX(7))/(JVS(67))
  XX(20) = X(20)/JVS(69)
  XX(21) = (X(21)-JVS(20)*XX(6)-JVS(26)*XX(7))/(JVS(72))
  XX(22) = X(22)/JVS(74)
  XX(23) = X(23)/JVS(79)
  XX(24) = (X(24)-JVS(40)*XX(10)-JVS(44)*XX(11))/(JVS(84))
  XX(25) = (X(25)-JVS(48)*XX(12)-JVS(52)*XX(13))/(JVS(88))
  XX(26) = X(26)/JVS(92)
  XX(27) = X(27)/JVS(98)
  XX(28) = X(28)/JVS(101)
  XX(29) = X(29)/JVS(107)
  XX(30) = X(30)/JVS(119)
  XX(31) = X(31)/JVS(123)
  XX(32) = X(32)/JVS(128)
  XX(33) = (X(33)-JVS(7)*XX(4))/(JVS(132))
  XX(34) = X(34)/JVS(135)
  XX(35) = (X(35)-JVS(21)*XX(6)-JVS(27)*XX(7)-JVS(80)*XX(23))/(JVS(143))
  XX(36) = X(36)/JVS(147)
  XX(37) = X(37)/JVS(154)
  XX(38) = X(38)/JVS(164)
  XX(39) = X(39)/JVS(178)
  XX(40) = (X(40)-JVS(31)*XX(8)-JVS(108)*XX(29))/(JVS(186))
  XX(41) = (X(41)-JVS(165)*XX(38))/(JVS(203))
  XX(42) = (X(42)-JVS(187)*XX(40))/(JVS(208))
  XX(43) = (X(43)-JVS(166)*XX(38))/(JVS(213))
  XX(44) = (X(44)-JVS(8)*XX(4)-JVS(11)*XX(5)-JVS(34)*XX(9)-JVS(75)*XX(22)-JVS(102)*XX(28)-JVS(109)*XX(29)-JVS(136)&
             &*XX(34)-JVS(167)*XX(38)-JVS(188)*XX(40))/(JVS(218))
  XX(45) = (X(45)-JVS(12)*XX(5)-JVS(168)*XX(38)-JVS(179)*XX(39)-JVS(189)*XX(40)-JVS(209)*XX(42))/(JVS(222))
  XX(46) = (X(46)-JVS(155)*XX(37)-JVS(169)*XX(38))/(JVS(234))
  XX(47) = X(47)/JVS(252)
  XX(48) = X(48)/JVS(265)
  XX(49) = (X(49)-JVS(13)*XX(5)-JVS(35)*XX(9)-JVS(76)*XX(22)-JVS(103)*XX(28)-JVS(110)*XX(29)-JVS(137)*XX(34)-JVS(170)&
             &*XX(38)-JVS(190)*XX(40)-JVS(235)*XX(46)-JVS(253)*XX(47)-JVS(266)*XX(48))/(JVS(277))
  XX(50) = (X(50)-JVS(156)*XX(37)-JVS(171)*XX(38)-JVS(254)*XX(47))/(JVS(286))
  XX(51) = (X(51)-JVS(104)*XX(28)-JVS(120)*XX(30))/(JVS(299))
  XX(52) = (X(52)-JVS(111)*XX(29)-JVS(191)*XX(40)-JVS(236)*XX(46))/(JVS(310))
  XX(53) = (X(53)-JVS(157)*XX(37)-JVS(172)*XX(38))/(JVS(328))
  XX(54) = (X(54)-JVS(129)*XX(32)-JVS(138)*XX(34)-JVS(237)*XX(46))/(JVS(344))
  XX(55) = (X(55)-JVS(14)*XX(5)-JVS(158)*XX(37)-JVS(173)*XX(38)-JVS(192)*XX(40)-JVS(214)*XX(43)-JVS(238)*XX(46)-JVS(255)&
             &*XX(47)-JVS(267)*XX(48)-JVS(287)*XX(50)-JVS(329)*XX(53)-JVS(345)*XX(54))/(JVS(359))
  XX(56) = (X(56)-JVS(112)*XX(29)-JVS(193)*XX(40)-JVS(256)*XX(47)-JVS(268)*XX(48)-JVS(288)*XX(50)-JVS(300)*XX(51)&
             &-JVS(330)*XX(53)-JVS(346)*XX(54))/(JVS(369))
  XX(57) = (X(57)-JVS(239)*XX(46)-JVS(269)*XX(48)-JVS(289)*XX(50)-JVS(347)*XX(54)-JVS(370)*XX(56))/(JVS(381))
  XX(58) = (X(58)-JVS(113)*XX(29)-JVS(194)*XX(40)-JVS(257)*XX(47)-JVS(270)*XX(48)-JVS(301)*XX(51)-JVS(331)*XX(53)&
             &-JVS(348)*XX(54)-JVS(371)*XX(56)-JVS(382)*XX(57))/(JVS(398))
  XX(59) = (X(59)-JVS(114)*XX(29)-JVS(195)*XX(40)-JVS(258)*XX(47)-JVS(271)*XX(48)-JVS(302)*XX(51)-JVS(311)*XX(52)&
             &-JVS(332)*XX(53)-JVS(349)*XX(54)-JVS(383)*XX(57)-JVS(399)*XX(58))/(JVS(414))
  XX(60) = (X(60)-JVS(22)*XX(6)-JVS(28)*XX(7)-JVS(36)*XX(9)-JVS(70)*XX(20)-JVS(81)*XX(23)-JVS(85)*XX(24)-JVS(89)*XX(25)&
             &-JVS(115)*XX(29)-JVS(144)*XX(35)-JVS(148)*XX(36)-JVS(159)*XX(37)-JVS(174)*XX(38)-JVS(180)*XX(39)-JVS(196)&
             &*XX(40)-JVS(204)*XX(41)-JVS(219)*XX(44)-JVS(223)*XX(45)-JVS(240)*XX(46)-JVS(259)*XX(47)-JVS(272)*XX(48)&
             &-JVS(278)*XX(49)-JVS(290)*XX(50)-JVS(303)*XX(51)-JVS(312)*XX(52)-JVS(333)*XX(53)-JVS(350)*XX(54)-JVS(360)&
             &*XX(55)-JVS(372)*XX(56)-JVS(384)*XX(57)-JVS(400)*XX(58)-JVS(415)*XX(59))/(JVS(442))
  XX(61) = (X(61)-JVS(99)*XX(27)-JVS(116)*XX(29)-JVS(124)*XX(31)-JVS(149)*XX(36)-JVS(175)*XX(38)-JVS(181)*XX(39)&
             &-JVS(197)*XX(40)-JVS(205)*XX(41)-JVS(210)*XX(42)-JVS(215)*XX(43)-JVS(241)*XX(46)-JVS(260)*XX(47)-JVS(273)&
             &*XX(48)-JVS(291)*XX(50)-JVS(304)*XX(51)-JVS(313)*XX(52)-JVS(334)*XX(53)-JVS(351)*XX(54)-JVS(361)*XX(55)&
             &-JVS(373)*XX(56)-JVS(385)*XX(57)-JVS(401)*XX(58)-JVS(416)*XX(59)-JVS(443)*XX(60))/(JVS(468))
  XX(62) = (X(62)-JVS(65)*XX(18)-JVS(71)*XX(20)-JVS(82)*XX(23)-JVS(93)*XX(26)-JVS(125)*XX(31)-JVS(150)*XX(36)-JVS(160)&
             &*XX(37)-JVS(417)*XX(59)-JVS(444)*XX(60)-JVS(469)*XX(61))/(JVS(502))
  XX(63) = (X(63)-JVS(3)*XX(1)-JVS(23)*XX(6)-JVS(29)*XX(7)-JVS(32)*XX(8)-JVS(37)*XX(9)-JVS(41)*XX(10)-JVS(45)*XX(11)&
             &-JVS(49)*XX(12)-JVS(53)*XX(13)-JVS(56)*XX(14)-JVS(60)*XX(16)-JVS(62)*XX(17)-JVS(68)*XX(19)-JVS(73)*XX(21)&
             &-JVS(77)*XX(22)-JVS(83)*XX(23)-JVS(86)*XX(24)-JVS(90)*XX(25)-JVS(94)*XX(26)-JVS(100)*XX(27)-JVS(105)*XX(28)&
             &-JVS(117)*XX(29)-JVS(121)*XX(30)-JVS(126)*XX(31)-JVS(130)*XX(32)-JVS(133)*XX(33)-JVS(139)*XX(34)-JVS(145)&
             &*XX(35)-JVS(161)*XX(37)-JVS(176)*XX(38)-JVS(198)*XX(40)-JVS(206)*XX(41)-JVS(211)*XX(42)-JVS(216)*XX(43)&
             &-JVS(220)*XX(44)-JVS(224)*XX(45)-JVS(242)*XX(46)-JVS(261)*XX(47)-JVS(274)*XX(48)-JVS(279)*XX(49)-JVS(292)&
             &*XX(50)-JVS(305)*XX(51)-JVS(314)*XX(52)-JVS(335)*XX(53)-JVS(352)*XX(54)-JVS(362)*XX(55)-JVS(374)*XX(56)&
             &-JVS(386)*XX(57)-JVS(402)*XX(58)-JVS(418)*XX(59)-JVS(445)*XX(60)-JVS(470)*XX(61)-JVS(503)*XX(62))/(JVS(548))
  XX(64) = (X(64)-JVS(9)*XX(4)-JVS(15)*XX(5)-JVS(38)*XX(9)-JVS(42)*XX(10)-JVS(46)*XX(11)-JVS(50)*XX(12)-JVS(54)*XX(13)&
             &-JVS(58)*XX(15)-JVS(78)*XX(22)-JVS(87)*XX(24)-JVS(91)*XX(25)-JVS(106)*XX(28)-JVS(118)*XX(29)-JVS(134)*XX(33)&
             &-JVS(140)*XX(34)-JVS(151)*XX(36)-JVS(177)*XX(38)-JVS(199)*XX(40)-JVS(207)*XX(41)-JVS(221)*XX(44)-JVS(225)&
             &*XX(45)-JVS(243)*XX(46)-JVS(262)*XX(47)-JVS(275)*XX(48)-JVS(280)*XX(49)-JVS(293)*XX(50)-JVS(306)*XX(51)&
             &-JVS(315)*XX(52)-JVS(336)*XX(53)-JVS(353)*XX(54)-JVS(363)*XX(55)-JVS(375)*XX(56)-JVS(387)*XX(57)-JVS(403)&
             &*XX(58)-JVS(419)*XX(59)-JVS(446)*XX(60)-JVS(471)*XX(61)-JVS(504)*XX(62)-JVS(549)*XX(63))/(JVS(565))
  XX(65) = (X(65)-JVS(16)*XX(5)-JVS(63)*XX(17)-JVS(95)*XX(26)-JVS(122)*XX(30)-JVS(127)*XX(31)-JVS(131)*XX(32)-JVS(162)&
             &*XX(37)-JVS(182)*XX(39)-JVS(200)*XX(40)-JVS(212)*XX(42)-JVS(217)*XX(43)-JVS(244)*XX(46)-JVS(263)*XX(47)&
             &-JVS(276)*XX(48)-JVS(294)*XX(50)-JVS(307)*XX(51)-JVS(316)*XX(52)-JVS(337)*XX(53)-JVS(354)*XX(54)-JVS(364)&
             &*XX(55)-JVS(376)*XX(56)-JVS(388)*XX(57)-JVS(404)*XX(58)-JVS(420)*XX(59)-JVS(447)*XX(60)-JVS(472)*XX(61)&
             &-JVS(505)*XX(62)-JVS(550)*XX(63)-JVS(566)*XX(64))/(JVS(605))
  XX(66) = (X(66)-JVS(17)*XX(5)-JVS(66)*XX(18)-JVS(355)*XX(54)-JVS(448)*XX(60)-JVS(473)*XX(61)-JVS(506)*XX(62)-JVS(551)&
             &*XX(63)-JVS(567)*XX(64)-JVS(606)*XX(65))/(JVS(626))
  XX(66) = XX(66)
  XX(65) = XX(65)-JVS(625)*XX(66)
  XX(64) = XX(64)-JVS(604)*XX(65)-JVS(624)*XX(66)
  XX(63) = XX(63)-JVS(564)*XX(64)-JVS(603)*XX(65)-JVS(623)*XX(66)
  XX(62) = XX(62)-JVS(547)*XX(63)-JVS(563)*XX(64)-JVS(602)*XX(65)-JVS(622)*XX(66)
  XX(61) = XX(61)-JVS(501)*XX(62)-JVS(546)*XX(63)-JVS(562)*XX(64)-JVS(601)*XX(65)-JVS(621)*XX(66)
  XX(60) = XX(60)-JVS(467)*XX(61)-JVS(500)*XX(62)-JVS(545)*XX(63)-JVS(561)*XX(64)-JVS(600)*XX(65)-JVS(620)*XX(66)
  XX(59) = XX(59)-JVS(441)*XX(60)-JVS(466)*XX(61)-JVS(499)*XX(62)-JVS(544)*XX(63)-JVS(599)*XX(65)-JVS(619)*XX(66)
  XX(58) = XX(58)-JVS(413)*XX(59)-JVS(440)*XX(60)-JVS(465)*XX(61)-JVS(498)*XX(62)-JVS(543)*XX(63)-JVS(598)*XX(65)&
             &-JVS(618)*XX(66)
  XX(57) = XX(57)-JVS(397)*XX(58)-JVS(439)*XX(60)-JVS(464)*XX(61)-JVS(497)*XX(62)-JVS(542)*XX(63)-JVS(597)*XX(65)&
             &-JVS(617)*XX(66)
  XX(56) = XX(56)-JVS(380)*XX(57)-JVS(396)*XX(58)-JVS(438)*XX(60)-JVS(463)*XX(61)-JVS(496)*XX(62)-JVS(541)*XX(63)&
             &-JVS(596)*XX(65)-JVS(616)*XX(66)
  XX(55) = XX(55)-JVS(368)*XX(56)-JVS(379)*XX(57)-JVS(395)*XX(58)-JVS(412)*XX(59)-JVS(437)*XX(60)-JVS(462)*XX(61)&
             &-JVS(495)*XX(62)-JVS(540)*XX(63)-JVS(560)*XX(64)-JVS(595)*XX(65)-JVS(615)*XX(66)
  XX(54) = XX(54)-JVS(436)*XX(60)-JVS(461)*XX(61)-JVS(494)*XX(62)-JVS(539)*XX(63)-JVS(594)*XX(65)
  XX(53) = XX(53)-JVS(343)*XX(54)-JVS(435)*XX(60)-JVS(493)*XX(62)-JVS(538)*XX(63)-JVS(593)*XX(65)-JVS(614)*XX(66)
  XX(52) = XX(52)-JVS(327)*XX(53)-JVS(394)*XX(58)-JVS(411)*XX(59)-JVS(434)*XX(60)-JVS(460)*XX(61)-JVS(492)*XX(62)&
             &-JVS(537)*XX(63)-JVS(592)*XX(65)
  XX(51) = XX(51)-JVS(326)*XX(53)-JVS(433)*XX(60)-JVS(459)*XX(61)-JVS(491)*XX(62)-JVS(536)*XX(63)-JVS(591)*XX(65)
  XX(50) = XX(50)-JVS(432)*XX(60)-JVS(458)*XX(61)-JVS(490)*XX(62)-JVS(535)*XX(63)-JVS(590)*XX(65)-JVS(613)*XX(66)
  XX(49) = XX(49)-JVS(285)*XX(50)-JVS(298)*XX(51)-JVS(309)*XX(52)-JVS(325)*XX(53)-JVS(342)*XX(54)-JVS(378)*XX(57)&
             &-JVS(393)*XX(58)-JVS(431)*XX(60)-JVS(457)*XX(61)-JVS(489)*XX(62)-JVS(534)*XX(63)-JVS(559)*XX(64)-JVS(589)&
             &*XX(65)-JVS(612)*XX(66)
  XX(48) = XX(48)-JVS(341)*XX(54)-JVS(377)*XX(57)-JVS(533)*XX(63)-JVS(611)*XX(66)
  XX(47) = XX(47)-JVS(430)*XX(60)-JVS(456)*XX(61)-JVS(488)*XX(62)-JVS(588)*XX(65)
  XX(46) = XX(46)-JVS(429)*XX(60)-JVS(487)*XX(62)-JVS(532)*XX(63)-JVS(587)*XX(65)
  XX(45) = XX(45)-JVS(233)*XX(46)-JVS(251)*XX(47)-JVS(324)*XX(53)-JVS(358)*XX(55)-JVS(367)*XX(56)-JVS(392)*XX(58)&
             &-JVS(410)*XX(59)-JVS(428)*XX(60)-JVS(455)*XX(61)-JVS(486)*XX(62)-JVS(531)*XX(63)-JVS(558)*XX(64)-JVS(586)&
             &*XX(65)-JVS(610)*XX(66)
  XX(44) = XX(44)-JVS(232)*XX(46)-JVS(250)*XX(47)-JVS(284)*XX(50)-JVS(297)*XX(51)-JVS(308)*XX(52)-JVS(323)*XX(53)&
             &-JVS(340)*XX(54)-JVS(391)*XX(58)-JVS(427)*XX(60)-JVS(530)*XX(63)-JVS(557)*XX(64)-JVS(585)*XX(65)-JVS(609)&
             &*XX(66)
  XX(43) = XX(43)-JVS(231)*XX(46)-JVS(264)*XX(48)-JVS(283)*XX(50)-JVS(322)*XX(53)-JVS(366)*XX(56)-JVS(454)*XX(61)&
             &-JVS(485)*XX(62)-JVS(529)*XX(63)-JVS(584)*XX(65)
  XX(42) = XX(42)-JVS(230)*XX(46)-JVS(357)*XX(55)-JVS(365)*XX(56)-JVS(390)*XX(58)-JVS(409)*XX(59)-JVS(453)*XX(61)&
             &-JVS(484)*XX(62)-JVS(528)*XX(63)-JVS(583)*XX(65)
  XX(41) = XX(41)-JVS(229)*XX(46)-JVS(249)*XX(47)-JVS(282)*XX(50)-JVS(321)*XX(53)-JVS(527)*XX(63)-JVS(556)*XX(64)&
             &-JVS(582)*XX(65)-JVS(608)*XX(66)
  XX(40) = XX(40)-JVS(389)*XX(58)-JVS(526)*XX(63)
  XX(39) = XX(39)-JVS(185)*XX(40)-JVS(320)*XX(53)-JVS(356)*XX(55)-JVS(408)*XX(59)-JVS(452)*XX(61)-JVS(483)*XX(62)&
             &-JVS(581)*XX(65)
  XX(38) = XX(38)-JVS(525)*XX(63)-JVS(580)*XX(65)
  XX(37) = XX(37)-JVS(426)*XX(60)-JVS(482)*XX(62)-JVS(524)*XX(63)
  XX(36) = XX(36)-JVS(425)*XX(60)-JVS(451)*XX(61)-JVS(481)*XX(62)-JVS(555)*XX(64)
  XX(35) = XX(35)-JVS(153)*XX(37)-JVS(202)*XX(41)-JVS(248)*XX(47)-JVS(407)*XX(59)-JVS(424)*XX(60)-JVS(480)*XX(62)&
             &-JVS(523)*XX(63)-JVS(579)*XX(65)
  XX(34) = XX(34)-JVS(228)*XX(46)-JVS(522)*XX(63)-JVS(578)*XX(65)
  XX(33) = XX(33)-JVS(163)*XX(38)-JVS(227)*XX(46)-JVS(247)*XX(47)-JVS(319)*XX(53)-JVS(521)*XX(63)-JVS(554)*XX(64)&
             &-JVS(577)*XX(65)
  XX(32) = XX(32)-JVS(226)*XX(46)-JVS(339)*XX(54)-JVS(520)*XX(63)-JVS(576)*XX(65)
  XX(31) = XX(31)-JVS(450)*XX(61)-JVS(479)*XX(62)-JVS(519)*XX(63)
  XX(30) = XX(30)-JVS(296)*XX(51)-JVS(318)*XX(53)-JVS(518)*XX(63)-JVS(575)*XX(65)
  XX(29) = XX(29)-JVS(184)*XX(40)
  XX(28) = XX(28)-JVS(295)*XX(51)-JVS(517)*XX(63)
  XX(27) = XX(27)-JVS(201)*XX(41)-JVS(406)*XX(59)-JVS(449)*XX(61)-JVS(478)*XX(62)-JVS(574)*XX(65)
  XX(26) = XX(26)-JVS(477)*XX(62)-JVS(516)*XX(63)-JVS(573)*XX(65)
  XX(25) = XX(25)-JVS(423)*XX(60)-JVS(515)*XX(63)-JVS(553)*XX(64)
  XX(24) = XX(24)-JVS(422)*XX(60)-JVS(514)*XX(63)-JVS(552)*XX(64)
  XX(23) = XX(23)-JVS(405)*XX(59)-JVS(476)*XX(62)
  XX(22) = XX(22)-JVS(338)*XX(54)-JVS(513)*XX(63)
  XX(21) = XX(21)-JVS(97)*XX(27)-JVS(142)*XX(35)-JVS(183)*XX(40)-JVS(246)*XX(47)-JVS(281)*XX(50)-JVS(512)*XX(63)&
             &-JVS(572)*XX(65)
  XX(20) = XX(20)-JVS(152)*XX(37)-JVS(421)*XX(60)-JVS(475)*XX(62)
  XX(19) = XX(19)-JVS(96)*XX(27)-JVS(141)*XX(35)-JVS(245)*XX(47)-JVS(511)*XX(63)-JVS(571)*XX(65)
  XX(18) = XX(18)-JVS(474)*XX(62)-JVS(607)*XX(66)
  XX(17) = XX(17)-JVS(510)*XX(63)-JVS(570)*XX(65)
  XX(16) = XX(16)-JVS(317)*XX(53)-JVS(509)*XX(63)-JVS(569)*XX(65)
  XX(15) = XX(15)-JVS(146)*XX(36)-JVS(508)*XX(63)
  XX(14) = XX(14)-JVS(507)*XX(63)-JVS(568)*XX(65)
  XX(13) = XX(13)
  XX(12) = XX(12)
  XX(11) = XX(11)
  XX(10) = XX(10)
  XX(9) = XX(9)
  XX(8) = XX(8)
  XX(7) = XX(7)
  XX(6) = XX(6)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cbmz_mosaic_LinearAlgebra

