! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cri_mosaic_4bin_aq_Monitor.f90
! Time                 : Thu Apr 14 13:13:37 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/cri_mosaic_4bin_aq
! Equation file        : cri_mosaic_4bin_aq.kpp
! Output root filename : cri_mosaic_4bin_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cri_mosaic_4bin_aq_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'HCl         ','NH3         ','ClNO2       ', &
     'H2SO4       ','SO3         ','MSA         ', &
     'DMSO2       ','O1D         ','C2H6        ', &
     'HSO3        ','NC4H10      ','CH3CL       ', &
     'CH2CL2      ','CHCL3       ','CH3CCL3     ', &
     'CDICLETH    ','TDICLETH    ','TRICLETH    ', &
     'TCE         ','CH4         ','TM135B      ', &
     'OETHTOL     ','METHTOL     ','PETHTOL     ', &
     'DIME35EB    ','C3H8        ','OXYL        ', &
     'TM123B      ','TM124B      ','BENZENE     ', &
     'TOLUENE     ','N2O5        ','MEK         ', &
     'TNCARB15    ','CH3O2NO2    ','C2H2        ', &
     'CH3OH       ','CARB15      ','CCARB12     ', &
     'RCOOH25     ','HONO        ','DMSO        ', &
     'C2H5OH      ','IPROPOL     ','CARB12      ', &
     'HCOOH       ','AROH14      ','RAROH14     ', &
     'AROH17      ','RAROH17     ','NPROPOL     ', &
     'CH3CO2H     ','CH3SO3      ','RN9NO3      ', &
     'RN12NO3     ','RN10OOH     ','RN19OOH     ', &
     'RN8OOH      ','RN11OOH     ','NRN6OOH     ', &
     'NRN12OOH    ','C2H5CO3H    ','HNO4        ', &
     'RU14NO3     ','NRU14OOH    ','HOC2H4NO3   ', &
     'RTN28NO3    ','RTN28OOH    ','RTN26OOH    ', &
     'NRTN28OOH   ','RTN25OOH    ','RTN24OOH    ', &
     'C2H5OOH     ','IC3H7OOH    ','RTX24OOH    ', &
     'CH3CO3H     ','ANHY        ','TNCARB12    ', &
     'RN16NO3     ','RN16OOH     ','RN17OOH     ', &
     'RN12OOH     ','NRN9OOH     ','IC3H7NO3    ', &
     'HOCH2CO3H   ','RU10OOH     ','RU12PAN     ', &
     'NRU12OOH    ','RA13OOH     ','CH3NO3      ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_1 = (/ &
     'C2H5NO3     ','RA16OOH     ','CH3OOH      ', &
     'RN10NO3     ','RTN23OOH    ','RTN10OOH    ', &
     'RTN25NO3    ','RN19NO3     ','RTX28NO3    ', &
     'RTX24NO3    ','HOC2H4OOH   ','RTX22NO3    ', &
     'RTX22OOH    ','RN15NO3     ','RN18NO3     ', &
     'RA25OOH     ','H2O2        ','TXCARB22    ', &
     'DMS         ','MSIA        ','CH3SCH2OO   ', &
     'PPN         ','PHAN        ','RU14OOH     ', &
     'RU12OOH     ','RN14OOH     ','MPAN        ', &
     'RN9OOH      ','RA13NO3     ','ARNOH14     ', &
     'RA16NO3     ','ARNOH17     ','RTN26PAN    ', &
     'RTN14OOH    ','RTX28OOH    ','NRTX28OOH   ', &
     'SO2         ','RA25NO3     ','PAN         ', &
     'RN18OOH     ','RA19OOH     ','CARB17      ', &
     'TXCARB24    ','RA22OOH     ','RN13NO3     ', &
     'TNCARB11    ','RN15OOH     ','CARB14      ', &
     'RA19NO3     ','CARB10      ','CARB11A     ', &
     'RA22NO3     ','CH3S        ','NRU14O2     ', &
     'NRN12O2     ','NRTN28O2    ','CARB9       ', &
     'NRN6O2      ','RN13AO2     ','C3H6        ', &
     'CARB3       ','NUCARB12    ','UDCARB17    ', &
     'C2H4        ','UDCARB8     ','IC3H7O2     ', &
     'RA22AO2     ','RTN24O2     ','BPINENE     ', &
     'TNCARB10    ','TBUT2ENE    ','RTN23NO3    ', &
     'NOA         ','RA13O2      ','APINENE     ', &
     'TNCARB26    ','NRN9O2      ','CARB13      ', &
     'NRTX28O2    ','UDCARB14    ','CH3SO2      ', &
     'CH3SO       ','O3P         ','RN18O2      ', &
     'RN13OOH     ','RA25O2      ','C5H8        ', &
     'RN16AO2     ','CARB7       ','RU14O2      ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(55) :: SPC_NAMES_2 = (/ &
     'CARB16      ','RA16O2      ','UDCARB11    ', &
     'RTN10O2     ','RTX28O2     ','NRU12O2     ', &
     'CO          ','HOCH2CO3    ','RA19AO2     ', &
     'CARB6       ','UCARB12     ','HNO3        ', &
     'RTN28O2     ','RTN14O2     ','CH3COCH3    ', &
     'RA19CO2     ','RA22BO2     ','HOCH2CH2O2  ', &
     'HOCH2CHO    ','RU10O2      ','RU12O2      ', &
     'RN18AO2     ','UCARB10     ','C2H5CO3     ', &
     'RTN23O2     ','RN19O2      ','HCHO        ', &
     'RN11O2      ','RN15O2      ','CH3OO       ', &
     'RTX22O2     ','RTN25O2     ','RN12O2      ', &
     'C2H5O2      ','RTX24O2     ','RN10O2      ', &
     'RN14O2      ','RN9O2       ','CH3CO3      ', &
     'RN17O2      ','RN8O2       ','RTN26O2     ', &
     'O3          ','RN16O2      ','RN15AO2     ', &
     'RN13O2      ','C2H5CHO     ','HO2         ', &
     'NO          ','NO3         ','OH          ', &
     'NO2         ','CH3CHO      ','H2O         ', &
     'M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(235) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1, SPC_NAMES_2 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              O3 --> O1D                                                                            ', &
     '              O3 --> O3P                                                                            ', &
     '            H2O2 --> 2 OH                                                                           ', &
     '             NO2 --> O3P + NO                                                                       ', &
     '             NO3 --> NO                                                                             ', &
     '             NO3 --> O3P + NO2                                                                      ', &
     '            HONO --> NO + OH                                                                        ', &
     '            HNO3 --> OH + NO2                                                                       ', &
     '            HCHO --> CO + 2 HO2                                                                     ', &
     '            HCHO --> CO                                                                             ', &
     '          CH3CHO --> CO + CH3OO + HO2                                                               ', &
     '         C2H5CHO --> CO + C2H5O2 + HO2                                                              ', &
     '        CH3COCH3 --> CH3OO + CH3CO3                                                                 ', &
     '             MEK --> C2H5O2 + CH3CO3                                                                ', &
     '          CARB14 --> RN10O2 + CH3CO3                                                                ', &
     '          CARB17 --> RN10O2 + RN8O2                                                                 ', &
     '         CARB11A --> C2H5O2 + CH3CO3                                                                ', &
     '           CARB7 --> HCHO + CH3CO3 + HO2                                                            ', &
     '          CARB10 --> CH3CO3 + HO2 + CH3CHO                                                          ', &
     '          CARB13 --> RN8O2 + HO2 + CH3CHO                                                           ', &
     '          CARB16 --> RN8O2 + C2H5CHO + HO2                                                          ', &
     '        HOCH2CHO --> CO + HCHO + 2 HO2                                                              ', &
     '         UCARB10 --> HCHO + CH3CO3 + HO2                                                            ', &
     '           CARB3 --> 2 CO + 2 HO2                                                                   ', &
     '           CARB6 --> CO + CH3CO3 + HO2                                                              ', &
     '           CARB9 --> 2 CH3CO3                                                                       ', &
     '          CARB12 --> CH3CO3 + RN8O2                                                                 ', &
     '          CARB15 --> 2 RN8O2                                                                        ', &
     '         UCARB12 --> CO + HOCH2CHO + CH3CO3 + HO2                                                   ', &
     '        NUCARB12 --> NOA + 2 CO + 2 HO2                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '             NOA --> HCHO + CH3CO3 + NO2                                                            ', &
     '         UDCARB8 --> C2H5O2 + HO2                                                                   ', &
     '        UDCARB11 --> RN10O2 + HO2                                                                   ', &
     '        UDCARB14 --> RN13O2 + HO2                                                                   ', &
     '        TNCARB26 --> RTN26O2 + HO2                                                                  ', &
     '        TNCARB10 --> CO + 2 CH3CO3                                                                  ', &
     '          CH3NO3 --> HCHO + HO2 + NO2                                                               ', &
     '         C2H5NO3 --> HO2 + NO2 + CH3CHO                                                             ', &
     '         RN10NO3 --> C2H5CHO + HO2 + NO2                                                            ', &
     '        IC3H7NO3 --> CH3COCH3 + HO2 + NO2                                                           ', &
     '         RN13NO3 --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '         RN13NO3 --> CARB11A + HO2 + NO2                                                            ', &
     '         RN16NO3 --> RN15O2 + NO2                                                                   ', &
     '         RN19NO3 --> RN18O2 + NO2                                                                   ', &
     '         RA13NO3 --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '         RA16NO3 --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '         RA19NO3 --> UDCARB11 + CARB6 + HO2 + NO2                                                   ', &
     '        RTX24NO3 --> TXCARB22 + HO2 + NO2                                                           ', &
     '          CH3OOH --> HCHO + HO2 + OH                                                                ', &
     '         C2H5OOH --> HO2 + OH + CH3CHO                                                              ', &
     '         RN10OOH --> C2H5CHO + HO2 + OH                                                             ', &
     '        IC3H7OOH --> CH3COCH3 + HO2 + OH                                                            ', &
     '         RN13OOH --> C2H5O2 + OH + CH3CHO                                                           ', &
     '         RN13OOH --> CARB11A + HO2 + OH                                                             ', &
     '         RN16OOH --> RN15AO2 + OH                                                                   ', &
     '         RN19OOH --> RN18AO2 + OH                                                                   ', &
     '         CH3CO3H --> CH3OO + OH                                                                     ', &
     '        C2H5CO3H --> C2H5O2 + OH                                                                    ', &
     '       HOCH2CO3H --> HCHO + HO2 + OH                                                                ', &
     '          RN8OOH --> C2H5O2 + OH                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '         RN11OOH --> RN10O2 + OH                                                                    ', &
     '         RN14OOH --> RN13O2 + OH                                                                    ', &
     '         RN17OOH --> RN16O2 + OH                                                                    ', &
     '         RU14OOH --> UCARB12 + HO2 + OH                                                             ', &
     '         RU14OOH --> UCARB10 + HCHO + HO2 + OH                                                      ', &
     '         RU12OOH --> CARB6 + HOCH2CHO + HO2 + OH                                                    ', &
     '         RU10OOH --> HOCH2CHO + CH3CO3 + OH                                                         ', &
     '        NRU14OOH --> NUCARB12 + HO2 + OH                                                            ', &
     '        NRU12OOH --> NOA + CO + HO2 + OH                                                            ', &
     '       HOC2H4OOH --> 2 HCHO + HO2 + OH                                                              ', &
     '          RN9OOH --> HCHO + HO2 + OH + CH3CHO                                                       ', &
     '         RN12OOH --> HO2 + OH + 2 CH3CHO                                                            ', &
     '         RN15OOH --> C2H5CHO + HO2 + OH + CH3CHO                                                    ', &
     '         RN18OOH --> 2 C2H5CHO + HO2 + OH                                                           ', &
     '         NRN6OOH --> 2 HCHO + OH + NO2                                                              ', &
     '         NRN9OOH --> HCHO + OH + NO2 + CH3CHO                                                       ', &
     '        NRN12OOH --> OH + NO2 + 2 CH3CHO                                                            ', &
     '         RA13OOH --> CARB3 + UDCARB8 + HO2 + OH                                                     ', &
     '         RA16OOH --> CARB3 + UDCARB11 + HO2 + OH                                                    ', &
     '         RA19OOH --> UDCARB11 + CARB6 + HO2 + OH                                                    ', &
     '        RTN28OOH --> TNCARB26 + HO2 + OH                                                            ', &
     '       NRTN28OOH --> TNCARB26 + OH + NO2                                                            ', &
     '        RTN26OOH --> RTN25O2 + OH                                                                   ', &
     '        RTN25OOH --> RTN24O2 + OH                                                                   ', &
     '        RTN24OOH --> RTN23O2 + OH                                                                   ', &
     '        RTN23OOH --> RTN14O2 + CH3COCH3 + OH                                                        ', &
     '        RTN14OOH --> TNCARB10 + HCHO + HO2 + OH                                                     ', &
     '        RTN10OOH --> CO + RN8O2 + OH                                                                ', &
     '        RTX28OOH --> TXCARB24 + HCHO + HO2 + OH                                                     ', &
     '        RTX24OOH --> TXCARB22 + HO2 + OH                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '        RTX22OOH --> CH3COCH3 + RN13O2 + OH                                                         ', &
     '       NRTX28OOH --> TXCARB24 + HCHO + OH + NO2                                                     ', &
     '         UDCARB8 --> ANHY + 2 HO2                                                                   ', &
     '        UDCARB11 --> ANHY + CH3OO + HO2                                                             ', &
     '        UDCARB14 --> ANHY + C2H5O2 + HO2                                                            ', &
     '         O3P + M --> O3                                                                             ', &
     '        CH3O2NO2 --> CH3OO + NO2                                                                    ', &
     '        O3P + O3 --> M                                                                              ', &
     '        O3P + NO --> NO2                                                                            ', &
     '       O3P + NO2 --> NO                                                                             ', &
     '       O3P + NO2 --> NO3                                                                            ', &
     '         O1D + M --> O3P                                                                            ', &
     '         O3 + NO --> NO2                                                                            ', &
     '        O3 + NO2 --> NO3                                                                            ', &
     '        2 NO + M --> 2 NO2                                                                          ', &
     '        NO + NO3 --> 2 NO2                                                                          ', &
     '       NO3 + NO2 --> NO + NO2                                                                       ', &
     '       NO3 + NO2 --> N2O5                                                                           ', &
     '            N2O5 --> NO3 + NO2                                                                      ', &
     '       O1D + H2O --> 2 OH                                                                           ', &
     '         O3 + OH --> HO2                                                                            ', &
     '          OH + M --> HO2 + H2O                                                                      ', &
     '         CO + OH --> HO2                                                                            ', &
     '       H2O2 + OH --> HO2                                                                            ', &
     '        O3 + HO2 --> OH                                                                             ', &
     '        HO2 + OH --> H2O                                                                            ', &
     '           2 HO2 --> H2O2                                                                           ', &
     '     2 HO2 + H2O --> H2O2                                                                           ', &
     '         NO + OH --> HONO                                                                           ', &
     '        OH + NO2 --> HNO3                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '        NO3 + OH --> HO2 + NO2                                                                      ', &
     '        HO2 + NO --> OH + NO2                                                                       ', &
     '       HO2 + NO2 --> HNO4                                                                           ', &
     '            HNO4 --> HO2 + NO2                                                                      ', &
     '       HNO4 + OH --> NO2                                                                            ', &
     '       HO2 + NO3 --> OH + NO2                                                                       ', &
     '       HONO + OH --> NO2                                                                            ', &
     '       HNO3 + OH --> NO3                                                                            ', &
     '       SO2 + O3P --> SO3                                                                            ', &
     '        SO2 + OH --> HSO3                                                                           ', &
     '        HSO3 + M --> SO3 + HO2                                                                      ', &
     '     SO3 + 2 H2O --> H2SO4                                                                          ', &
     '        CH4 + OH --> CH3OO                                                                          ', &
     '       C2H6 + OH --> C2H5O2                                                                         ', &
     '       C3H8 + OH --> IC3H7O2                                                                        ', &
     '       C3H8 + OH --> RN10O2                                                                         ', &
     '     NC4H10 + OH --> RN13O2                                                                         ', &
     '       C2H4 + OH --> HOCH2CH2O2                                                                     ', &
     '       C3H6 + OH --> RN9O2                                                                          ', &
     '   TBUT2ENE + OH --> RN12O2                                                                         ', &
     '      C2H4 + NO3 --> NRN6O2                                                                         ', &
     '      C3H6 + NO3 --> NRN9O2                                                                         ', &
     '  TBUT2ENE + NO3 --> NRN12O2                                                                        ', &
     '       C2H4 + O3 --> CO + HCHO + HO2 + OH                                                           ', &
     '       C2H4 + O3 --> HCOOH + HCHO                                                                   ', &
     '       C3H6 + O3 --> CO + HCHO + CH3OO + OH                                                         ', &
     '       C3H6 + O3 --> CH3CO2H + HCHO                                                                 ', &
     '   TBUT2ENE + O3 --> CO + CH3OO + OH + CH3CHO                                                       ', &
     '   TBUT2ENE + O3 --> CH3CO2H + CH3CHO                                                               ', &
     '       C5H8 + OH --> RU14O2                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '      C5H8 + NO3 --> NRU14O2                                                                        ', &
     '       C5H8 + O3 --> CO + UCARB10 + HO2 + OH                                                        ', &
     '       C5H8 + O3 --> HCOOH + UCARB10                                                                ', &
     '    APINENE + OH --> RTN28O2                                                                        ', &
     '   APINENE + NO3 --> NRTN28O2                                                                       ', &
     '    APINENE + O3 --> CH3COCH3 + RN18AO2 + OH                                                        ', &
     '    APINENE + O3 --> H2O2 + TNCARB26                                                                ', &
     '    APINENE + O3 --> RCOOH25                                                                        ', &
     '    BPINENE + OH --> RTX28O2                                                                        ', &
     '   BPINENE + NO3 --> NRTX28O2                                                                       ', &
     '    BPINENE + O3 --> RTX24O2 + OH                                                                   ', &
     '    BPINENE + O3 --> H2O2 + TXCARB24 + HCHO                                                         ', &
     '    BPINENE + O3 --> TXCARB22 + HCHO                                                                ', &
     '    BPINENE + O3 --> TXCARB24 + CO                                                                  ', &
     '       C2H2 + OH --> HCOOH + CO + HO2                                                               ', &
     '       C2H2 + OH --> CARB3 + OH                                                                     ', &
     '    BENZENE + OH --> RA13O2                                                                         ', &
     '    BENZENE + OH --> AROH14 + HO2                                                                   ', &
     '    TOLUENE + OH --> RA16O2                                                                         ', &
     '    TOLUENE + OH --> AROH17 + HO2                                                                   ', &
     '       OXYL + OH --> RA19AO2                                                                        ', &
     '       OXYL + OH --> RA19CO2                                                                        ', &
     '       HCHO + OH --> CO + HO2                                                                       ', &
     '     OH + CH3CHO --> CH3CO3                                                                         ', &
     '    C2H5CHO + OH --> C2H5CO3                                                                        ', &
     '      HCHO + NO3 --> CO + HNO3 + HO2                                                                ', &
     '    NO3 + CH3CHO --> HNO3 + CH3CO3                                                                  ', &
     '   C2H5CHO + NO3 --> HNO3 + C2H5CO3                                                                 ', &
     '   CH3COCH3 + OH --> RN8O2                                                                          ', &
     '        MEK + OH --> RN11O2                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '      CH3OH + OH --> HCHO + HO2                                                                     ', &
     '     C2H5OH + OH --> HO2 + CH3CHO                                                                   ', &
     '     C2H5OH + OH --> HOCH2CH2O2                                                                     ', &
     '    NPROPOL + OH --> C2H5CHO + HO2                                                                  ', &
     '    NPROPOL + OH --> RN9O2                                                                          ', &
     '    IPROPOL + OH --> CH3COCH3 + HO2                                                                 ', &
     '    IPROPOL + OH --> RN9O2                                                                          ', &
     '      HCOOH + OH --> HO2                                                                            ', &
     '    CH3CO2H + OH --> CH3OO                                                                          ', &
     '      CH3OO + NO --> HCHO + HO2 + NO2                                                               ', &
     '     C2H5O2 + NO --> HO2 + NO2 + CH3CHO                                                             ', &
     '     RN10O2 + NO --> C2H5CHO + HO2 + NO2                                                            ', &
     '    IC3H7O2 + NO --> CH3COCH3 + HO2 + NO2                                                           ', &
     '     RN13O2 + NO --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '     RN13O2 + NO --> CARB11A + HO2 + NO2                                                            ', &
     '     RN16O2 + NO --> RN15AO2 + NO2                                                                  ', &
     '     RN19O2 + NO --> RN18AO2 + NO2                                                                  ', &
     '    RN13AO2 + NO --> RN12O2 + NO2                                                                   ', &
     '    RN16AO2 + NO --> RN15O2 + NO2                                                                   ', &
     '     RA13O2 + NO --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '     RA16O2 + NO --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '     RA16O2 + NO --> UDCARB8 + CARB6 + HO2 + NO2                                                    ', &
     '    RA19AO2 + NO --> CARB3 + UDCARB14 + HO2 + NO2                                                   ', &
     '    RA19CO2 + NO --> CARB9 + UDCARB8 + HO2 + NO2                                                    ', &
     ' HOCH2CH2O2 + NO --> 2 HCHO + HO2 + NO2                                                             ', &
     ' HOCH2CH2O2 + NO --> HOCH2CHO + HO2 + NO2                                                           ', &
     '      RN9O2 + NO --> HCHO + HO2 + NO2 + CH3CHO                                                      ', &
     '     RN12O2 + NO --> HO2 + NO2 + 2 CH3CHO                                                           ', &
     '     RN15O2 + NO --> C2H5CHO + HO2 + NO2 + CH3CHO                                                   ', &
     '     RN18O2 + NO --> 2 C2H5CHO + HO2 + NO2                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '    RN15AO2 + NO --> CARB13 + HO2 + NO2                                                             ', &
     '    RN18AO2 + NO --> CARB16 + HO2 + NO2                                                             ', &
     '     CH3CO3 + NO --> CH3OO + NO2                                                                    ', &
     '    C2H5CO3 + NO --> C2H5O2 + NO2                                                                   ', &
     '   HOCH2CO3 + NO --> HCHO + HO2 + NO2                                                               ', &
     '      RN8O2 + NO --> HCHO + CH3CO3 + NO2                                                            ', &
     '     RN11O2 + NO --> CH3CO3 + NO2 + CH3CHO                                                          ', &
     '     RN14O2 + NO --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '     RN17O2 + NO --> RN16AO2 + NO2                                                                  ', &
     '     RU14O2 + NO --> UCARB12 + HO2 + NO2                                                            ', &
     '     RU14O2 + NO --> UCARB10 + HCHO + HO2 + NO2                                                     ', &
     '     RU12O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '     RU12O2 + NO --> CARB7 + CO + HO2 + NO2                                                         ', &
     '     RU10O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '     RU10O2 + NO --> CARB6 + HCHO + HO2 + NO2                                                       ', &
     '     RU10O2 + NO --> CARB7 + HCHO + HO2 + NO2                                                       ', &
     '     NRN6O2 + NO --> 2 HCHO + 2 NO2                                                                 ', &
     '     NRN9O2 + NO --> HCHO + 2 NO2 + CH3CHO                                                          ', &
     '    NRN12O2 + NO --> 2 NO2 + 2 CH3CHO                                                               ', &
     '    NRU14O2 + NO --> NUCARB12 + HO2 + NO2                                                           ', &
     '    NRU12O2 + NO --> NOA + CO + HO2 + NO2                                                           ', &
     '    RTN28O2 + NO --> TNCARB26 + HO2 + NO2                                                           ', &
     '    RTN28O2 + NO --> CH3COCH3 + RN19O2 + NO2                                                        ', &
     '   NRTN28O2 + NO --> TNCARB26 + 2 NO2                                                               ', &
     '    RTN26O2 + NO --> RTN25O2 + NO2                                                                  ', &
     '    RTN25O2 + NO --> RTN24O2 + NO2                                                                  ', &
     '    RTN24O2 + NO --> RTN23O2 + NO2                                                                  ', &
     '    RTN23O2 + NO --> RTN14O2 + CH3COCH3 + NO2                                                       ', &
     '    RTN14O2 + NO --> TNCARB10 + HCHO + HO2 + NO2                                                    ', &
     '    RTN10O2 + NO --> CO + RN8O2 + NO2                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '    RTX28O2 + NO --> TXCARB24 + HCHO + HO2 + NO2                                                    ', &
     '    RTX28O2 + NO --> CH3COCH3 + RN19O2 + NO2                                                        ', &
     '   NRTX28O2 + NO --> TXCARB24 + HCHO + 2 NO2                                                        ', &
     '    RTX24O2 + NO --> TXCARB22 + HO2 + NO2                                                           ', &
     '    RTX24O2 + NO --> RN13AO2 + CH3COCH3 + HCHO + NO2                                                ', &
     '    RTX22O2 + NO --> CH3COCH3 + RN13O2 + NO2                                                        ', &
     '      CH3OO + NO --> CH3NO3                                                                         ', &
     '     C2H5O2 + NO --> C2H5NO3                                                                        ', &
     '     RN10O2 + NO --> RN10NO3                                                                        ', &
     '    IC3H7O2 + NO --> IC3H7NO3                                                                       ', &
     '     RN13O2 + NO --> RN13NO3                                                                        ', &
     '     RN16O2 + NO --> RN16NO3                                                                        ', &
     '     RN19O2 + NO --> RN19NO3                                                                        ', &
     ' HOCH2CH2O2 + NO --> HOC2H4NO3                                                                      ', &
     '      RN9O2 + NO --> RN9NO3                                                                         ', &
     '     RN12O2 + NO --> RN12NO3                                                                        ', &
     '     RN15O2 + NO --> RN15NO3                                                                        ', &
     '     RN18O2 + NO --> RN18NO3                                                                        ', &
     '    RN15AO2 + NO --> RN15NO3                                                                        ', &
     '    RN18AO2 + NO --> RN18NO3                                                                        ', &
     '     RU14O2 + NO --> RU14NO3                                                                        ', &
     '     RA13O2 + NO --> RA13NO3                                                                        ', &
     '     RA16O2 + NO --> RA16NO3                                                                        ', &
     '    RA19AO2 + NO --> RA19NO3                                                                        ', &
     '    RA19CO2 + NO --> RA19NO3                                                                        ', &
     '    RTN28O2 + NO --> RTN28NO3                                                                       ', &
     '    RTN25O2 + NO --> RTN25NO3                                                                       ', &
     '    RTX28O2 + NO --> RTX28NO3                                                                       ', &
     '    RTX24O2 + NO --> RTX24NO3                                                                       ', &
     '    RTX22O2 + NO --> RTX22NO3                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '     CH3OO + NO3 --> HCHO + HO2 + NO2                                                               ', &
     '    C2H5O2 + NO3 --> HO2 + NO2 + CH3CHO                                                             ', &
     '    RN10O2 + NO3 --> C2H5CHO + HO2 + NO2                                                            ', &
     '   IC3H7O2 + NO3 --> CH3COCH3 + HO2 + NO2                                                           ', &
     '    RN13O2 + NO3 --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '    RN13O2 + NO3 --> CARB11A + HO2 + NO2                                                            ', &
     '    RN16O2 + NO3 --> RN15AO2 + NO2                                                                  ', &
     '    RN19O2 + NO3 --> RN18AO2 + NO2                                                                  ', &
     '   RN13AO2 + NO3 --> RN12O2 + NO2                                                                   ', &
     '   RN16AO2 + NO3 --> RN15O2 + NO2                                                                   ', &
     '    RA13O2 + NO3 --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '    RA16O2 + NO3 --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '    RA16O2 + NO3 --> UDCARB8 + CARB6 + HO2 + NO2                                                    ', &
     '   RA19AO2 + NO3 --> CARB3 + UDCARB14 + HO2 + NO2                                                   ', &
     '   RA19CO2 + NO3 --> CARB9 + UDCARB8 + HO2 + NO2                                                    ', &
     'HOCH2CH2O2 + NO3 --> 2 HCHO + HO2 + NO2                                                             ', &
     'HOCH2CH2O2 + NO3 --> HOCH2CHO + HO2 + NO2                                                           ', &
     '     RN9O2 + NO3 --> HCHO + HO2 + NO2 + CH3CHO                                                      ', &
     '    RN12O2 + NO3 --> HO2 + NO2 + 2 CH3CHO                                                           ', &
     '    RN15O2 + NO3 --> C2H5CHO + HO2 + NO2 + CH3CHO                                                   ', &
     '    RN18O2 + NO3 --> 2 C2H5CHO + HO2 + NO2                                                          ', &
     '   RN15AO2 + NO3 --> CARB13 + HO2 + NO2                                                             ', &
     '   RN18AO2 + NO3 --> CARB16 + HO2 + NO2                                                             ', &
     '    CH3CO3 + NO3 --> CH3OO + NO2                                                                    ', &
     '   C2H5CO3 + NO3 --> C2H5O2 + NO2                                                                   ', &
     '  HOCH2CO3 + NO3 --> HCHO + HO2 + NO2                                                               ', &
     '     RN8O2 + NO3 --> HCHO + CH3CO3 + NO2                                                            ', &
     '    RN11O2 + NO3 --> CH3CO3 + NO2 + CH3CHO                                                          ', &
     '    RN14O2 + NO3 --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '    RN17O2 + NO3 --> RN16AO2 + NO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '    RU14O2 + NO3 --> UCARB12 + HO2 + NO2                                                            ', &
     '    RU14O2 + NO3 --> UCARB10 + HCHO + HO2 + NO2                                                     ', &
     '    RU12O2 + NO3 --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '    RU12O2 + NO3 --> CARB7 + CO + HO2 + NO2                                                         ', &
     '    RU10O2 + NO3 --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '    RU10O2 + NO3 --> CARB6 + HCHO + HO2 + NO2                                                       ', &
     '    RU10O2 + NO3 --> CARB7 + HCHO + HO2 + NO2                                                       ', &
     '    NRN6O2 + NO3 --> 2 HCHO + 2 NO2                                                                 ', &
     '    NRN9O2 + NO3 --> HCHO + 2 NO2 + CH3CHO                                                          ', &
     '   NRN12O2 + NO3 --> 2 NO2 + 2 CH3CHO                                                               ', &
     '   NRU14O2 + NO3 --> NUCARB12 + HO2 + NO2                                                           ', &
     '   NRU12O2 + NO3 --> NOA + CO + HO2 + NO2                                                           ', &
     '   RTN28O2 + NO3 --> TNCARB26 + HO2 + NO2                                                           ', &
     '  NRTN28O2 + NO3 --> TNCARB26 + 2 NO2                                                               ', &
     '   RTN26O2 + NO3 --> RTN25O2 + NO2                                                                  ', &
     '   RTN25O2 + NO3 --> RTN24O2 + NO2                                                                  ', &
     '   RTN24O2 + NO3 --> RTN23O2 + NO2                                                                  ', &
     '   RTN23O2 + NO3 --> RTN14O2 + CH3COCH3 + NO2                                                       ', &
     '   RTN14O2 + NO3 --> TNCARB10 + HCHO + HO2 + NO2                                                    ', &
     '   RTN10O2 + NO3 --> CO + RN8O2 + NO2                                                               ', &
     '   RTX28O2 + NO3 --> TXCARB24 + HCHO + HO2 + NO2                                                    ', &
     '   RTX24O2 + NO3 --> TXCARB22 + HO2 + NO2                                                           ', &
     '   RTX22O2 + NO3 --> CH3COCH3 + RN13O2 + NO2                                                        ', &
     '  NRTX28O2 + NO3 --> TXCARB24 + HCHO + 2 NO2                                                        ', &
     '     CH3OO + HO2 --> CH3OOH                                                                         ', &
     '    C2H5O2 + HO2 --> C2H5OOH                                                                        ', &
     '    RN10O2 + HO2 --> RN10OOH                                                                        ', &
     '   IC3H7O2 + HO2 --> IC3H7OOH                                                                       ', &
     '    RN13O2 + HO2 --> RN13OOH                                                                        ', &
     '    RN16O2 + HO2 --> RN16OOH                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '    RN19O2 + HO2 --> RN19OOH                                                                        ', &
     '   RN13AO2 + HO2 --> RN13OOH                                                                        ', &
     '   RN16AO2 + HO2 --> RN16OOH                                                                        ', &
     '    RA13O2 + HO2 --> RA13OOH                                                                        ', &
     '    RA16O2 + HO2 --> RA16OOH                                                                        ', &
     '   RA19AO2 + HO2 --> RA19OOH                                                                        ', &
     '   RA19CO2 + HO2 --> RA19OOH                                                                        ', &
     'HOCH2CH2O2 + HO2 --> HOC2H4OOH                                                                      ', &
     '     RN9O2 + HO2 --> RN9OOH                                                                         ', &
     '    RN12O2 + HO2 --> RN12OOH                                                                        ', &
     '    RN15O2 + HO2 --> RN15OOH                                                                        ', &
     '    RN18O2 + HO2 --> RN18OOH                                                                        ', &
     '   RN15AO2 + HO2 --> RN15OOH                                                                        ', &
     '   RN18AO2 + HO2 --> RN18OOH                                                                        ', &
     '    CH3CO3 + HO2 --> CH3CO3H                                                                        ', &
     '   C2H5CO3 + HO2 --> C2H5CO3H                                                                       ', &
     '  HOCH2CO3 + HO2 --> HOCH2CO3H                                                                      ', &
     '     RN8O2 + HO2 --> RN8OOH                                                                         ', &
     '    RN11O2 + HO2 --> RN11OOH                                                                        ', &
     '    RN14O2 + HO2 --> RN14OOH                                                                        ', &
     '    RN17O2 + HO2 --> RN17OOH                                                                        ', &
     '    RU14O2 + HO2 --> RU14OOH                                                                        ', &
     '    RU12O2 + HO2 --> RU12OOH                                                                        ', &
     '    RU10O2 + HO2 --> RU10OOH                                                                        ', &
     '    NRN6O2 + HO2 --> NRN6OOH                                                                        ', &
     '    NRN9O2 + HO2 --> NRN9OOH                                                                        ', &
     '   NRN12O2 + HO2 --> NRN12OOH                                                                       ', &
     '   NRU14O2 + HO2 --> NRU14OOH                                                                       ', &
     '   NRU12O2 + HO2 --> NRU12OOH                                                                       ', &
     '   RTN28O2 + HO2 --> RTN28OOH                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '  NRTN28O2 + HO2 --> NRTN28OOH                                                                      ', &
     '   RTN26O2 + HO2 --> RTN26OOH                                                                       ', &
     '   RTN25O2 + HO2 --> RTN25OOH                                                                       ', &
     '   RTN24O2 + HO2 --> RTN24OOH                                                                       ', &
     '   RTN23O2 + HO2 --> RTN23OOH                                                                       ', &
     '   RTN14O2 + HO2 --> RTN14OOH                                                                       ', &
     '   RTN10O2 + HO2 --> RTN10OOH                                                                       ', &
     '   RTX28O2 + HO2 --> RTX28OOH                                                                       ', &
     '   RTX24O2 + HO2 --> RTX24OOH                                                                       ', &
     '   RTX22O2 + HO2 --> RTX22OOH                                                                       ', &
     '  NRTX28O2 + HO2 --> NRTX28OOH                                                                      ', &
     '           CH3OO --> HCHO + HO2                                                                     ', &
     '           CH3OO --> HCHO                                                                           ', &
     '           CH3OO --> CH3OH                                                                          ', &
     '          C2H5O2 --> HO2 + CH3CHO                                                                   ', &
     '          C2H5O2 --> CH3CHO                                                                         ', &
     '          C2H5O2 --> C2H5OH                                                                         ', &
     '          RN10O2 --> C2H5CHO + HO2                                                                  ', &
     '          RN10O2 --> C2H5CHO                                                                        ', &
     '          RN10O2 --> NPROPOL                                                                        ', &
     '         IC3H7O2 --> CH3COCH3 + HO2                                                                 ', &
     '         IC3H7O2 --> CH3COCH3                                                                       ', &
     '         IC3H7O2 --> IPROPOL                                                                        ', &
     '          RN13O2 --> C2H5O2 + CH3CHO                                                                ', &
     '          RN13O2 --> CARB11A + HO2                                                                  ', &
     '         RN13AO2 --> RN12O2                                                                         ', &
     '         RN16AO2 --> RN15O2                                                                         ', &
     '          RA13O2 --> CARB3 + UDCARB8 + HO2                                                          ', &
     '          RA16O2 --> CARB3 + UDCARB11 + HO2                                                         ', &
     '          RA16O2 --> UDCARB8 + CARB6 + HO2                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '         RA19AO2 --> CARB3 + UDCARB14 + HO2                                                         ', &
     '         RA19CO2 --> CARB3 + UDCARB14 + HO2                                                         ', &
     '          RN16O2 --> RN15AO2                                                                        ', &
     '          RN19O2 --> RN18AO2                                                                        ', &
     '      HOCH2CH2O2 --> 2 HCHO + HO2                                                                   ', &
     '      HOCH2CH2O2 --> HOCH2CHO + HO2                                                                 ', &
     '           RN9O2 --> HCHO + HO2 + CH3CHO                                                            ', &
     '          RN12O2 --> HO2 + 2 CH3CHO                                                                 ', &
     '          RN15O2 --> C2H5CHO + HO2 + CH3CHO                                                         ', &
     '          RN18O2 --> 2 C2H5CHO + HO2                                                                ', &
     '         RN15AO2 --> CARB13 + HO2                                                                   ', &
     '         RN18AO2 --> CARB16 + HO2                                                                   ', &
     '          CH3CO3 --> CH3OO                                                                          ', &
     '         C2H5CO3 --> C2H5O2                                                                         ', &
     '        HOCH2CO3 --> HCHO + HO2                                                                     ', &
     '           RN8O2 --> HCHO + CH3CO3                                                                  ', &
     '          RN11O2 --> CH3CO3 + CH3CHO                                                                ', &
     '          RN14O2 --> C2H5CO3 + CH3CHO                                                               ', &
     '          RN17O2 --> RN16AO2                                                                        ', &
     '          RU14O2 --> UCARB12 + HO2                                                                  ', &
     '          RU14O2 --> UCARB10 + HCHO + HO2                                                           ', &
     '          RU12O2 --> HOCH2CHO + CH3CO3                                                              ', &
     '          RU12O2 --> CARB7 + HOCH2CHO + HO2                                                         ', &
     '          RU10O2 --> HOCH2CHO + CH3CO3                                                              ', &
     '          RU10O2 --> CARB6 + HCHO + HO2                                                             ', &
     '          RU10O2 --> CARB7 + HCHO + HO2                                                             ', &
     '          NRN6O2 --> 2 HCHO + NO2                                                                   ', &
     '          NRN9O2 --> HCHO + NO2 + CH3CHO                                                            ', &
     '         NRN12O2 --> NO2 + 2 CH3CHO                                                                 ', &
     '         NRU14O2 --> NUCARB12 + HO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '         NRU12O2 --> NOA + CO + HO2                                                                 ', &
     '         RTN28O2 --> TNCARB26 + HO2                                                                 ', &
     '        NRTN28O2 --> TNCARB26 + NO2                                                                 ', &
     '         RTN26O2 --> RTN25O2                                                                        ', &
     '         RTN25O2 --> RTN24O2                                                                        ', &
     '         RTN24O2 --> RTN23O2                                                                        ', &
     '         RTN23O2 --> RTN14O2 + CH3COCH3                                                             ', &
     '         RTN14O2 --> TNCARB10 + HCHO + HO2                                                          ', &
     '         RTN10O2 --> CO + RN8O2                                                                     ', &
     '         RTX28O2 --> TXCARB24 + HCHO + HO2                                                          ', &
     '         RTX24O2 --> TXCARB22 + HO2                                                                 ', &
     '         RTX22O2 --> CH3COCH3 + RN13O2                                                              ', &
     '        NRTX28O2 --> TXCARB24 + HCHO + NO2                                                          ', &
     '     CARB14 + OH --> RN14O2                                                                         ', &
     '     CARB17 + OH --> RN17O2                                                                         ', &
     '    CARB11A + OH --> RN11O2                                                                         ', &
     '      CARB7 + OH --> CARB6 + HO2                                                                    ', &
     '     CARB10 + OH --> CARB9 + HO2                                                                    ', &
     '     CARB13 + OH --> RN13O2                                                                         ', &
     '     CARB16 + OH --> RN16O2                                                                         ', &
     '    UCARB10 + OH --> RU10O2                                                                         ', &
     '   UCARB10 + NO3 --> HNO3 + RU10O2                                                                  ', &
     '    UCARB10 + O3 --> CO + HCHO + CH3CO3 + OH                                                        ', &
     '    UCARB10 + O3 --> H2O2 + CARB6 + HCHO                                                            ', &
     '   HOCH2CHO + OH --> HOCH2CO3                                                                       ', &
     '  HOCH2CHO + NO3 --> HOCH2CO3 + HNO3                                                                ', &
     '      CARB3 + OH --> 2 CO + HO2                                                                     ', &
     '      CARB6 + OH --> CO + CH3CO3                                                                    ', &
     '      CARB9 + OH --> RN9O2                                                                          ', &
     '     CARB12 + OH --> RN12O2                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '     CARB15 + OH --> RN15O2                                                                         ', &
     '    CCARB12 + OH --> RN12O2                                                                         ', &
     '    UCARB12 + OH --> RU12O2                                                                         ', &
     '   UCARB12 + NO3 --> HNO3 + RU12O2                                                                  ', &
     '    UCARB12 + O3 --> CO + HOCH2CHO + CH3CO3 + OH                                                    ', &
     '    UCARB12 + O3 --> H2O2 + CARB6 + HOCH2CHO                                                        ', &
     '   NUCARB12 + OH --> NRU12O2                                                                        ', &
     '        NOA + OH --> CARB6 + NO2                                                                    ', &
     '    UDCARB8 + OH --> C2H5O2                                                                         ', &
     '   UDCARB11 + OH --> RN10O2                                                                         ', &
     '   UDCARB14 + OH --> RN13O2                                                                         ', &
     '   TNCARB26 + OH --> RTN26O2                                                                        ', &
     '   TNCARB15 + OH --> RN15AO2                                                                        ', &
     '   TNCARB10 + OH --> RTN10O2                                                                        ', &
     '  TNCARB26 + NO3 --> HNO3 + RTN26O2                                                                 ', &
     '  TNCARB10 + NO3 --> RTN10O2 + HNO3                                                                 ', &
     '    RCOOH25 + OH --> RTN25O2                                                                        ', &
     '   TXCARB24 + OH --> RTX24O2                                                                        ', &
     '   TXCARB22 + OH --> RTX22O2                                                                        ', &
     '     CH3NO3 + OH --> HCHO + NO2                                                                     ', &
     '    C2H5NO3 + OH --> NO2 + CH3CHO                                                                   ', &
     '    RN10NO3 + OH --> C2H5CHO + NO2                                                                  ', &
     '   IC3H7NO3 + OH --> CH3COCH3 + NO2                                                                 ', &
     '    RN13NO3 + OH --> CARB11A + NO2                                                                  ', &
     '    RN16NO3 + OH --> CARB14 + NO2                                                                   ', &
     '    RN19NO3 + OH --> CARB17 + NO2                                                                   ', &
     '  HOC2H4NO3 + OH --> HOCH2CHO + NO2                                                                 ', &
     '     RN9NO3 + OH --> CARB7 + NO2                                                                    ', &
     '    RN12NO3 + OH --> CARB10 + NO2                                                                   ', &
     '    RN15NO3 + OH --> CARB13 + NO2                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '    RN18NO3 + OH --> CARB16 + NO2                                                                   ', &
     '    RU14NO3 + OH --> UCARB12 + NO2                                                                  ', &
     '    RA13NO3 + OH --> CARB3 + UDCARB8 + NO2                                                          ', &
     '    RA16NO3 + OH --> CARB3 + UDCARB11 + NO2                                                         ', &
     '    RA19NO3 + OH --> UDCARB11 + CARB6 + NO2                                                         ', &
     '   RTN28NO3 + OH --> TNCARB26 + NO2                                                                 ', &
     '   RTN25NO3 + OH --> TNCARB15 + CH3COCH3 + NO2                                                      ', &
     '   RTX28NO3 + OH --> TXCARB24 + HCHO + NO2                                                          ', &
     '   RTX24NO3 + OH --> TXCARB22 + NO2                                                                 ', &
     '   RTX22NO3 + OH --> CCARB12 + CH3COCH3 + NO2                                                       ', &
     '     AROH14 + OH --> RAROH14                                                                        ', &
     '    AROH14 + NO3 --> RAROH14 + HNO3                                                                 ', &
     '   RAROH14 + NO2 --> ARNOH14                                                                        ', &
     '    ARNOH14 + OH --> CARB13 + NO2                                                                   ', &
     '   ARNOH14 + NO3 --> CARB13 + HNO3 + NO2                                                            ', &
     '     AROH17 + OH --> RAROH17                                                                        ', &
     '    AROH17 + NO3 --> RAROH17 + HNO3                                                                 ', &
     '   RAROH17 + NO2 --> ARNOH17                                                                        ', &
     '    ARNOH17 + OH --> CARB16 + NO2                                                                   ', &
     '   ARNOH17 + NO3 --> CARB16 + HNO3 + NO2                                                            ', &
     '     CH3OOH + OH --> CH3OO                                                                          ', &
     '     CH3OOH + OH --> HCHO + OH                                                                      ', &
     '    C2H5OOH + OH --> OH + CH3CHO                                                                    ', &
     '    RN10OOH + OH --> C2H5CHO + OH                                                                   ', &
     '   IC3H7OOH + OH --> CH3COCH3 + OH                                                                  ', &
     '    RN13OOH + OH --> CARB11A + OH                                                                   ', &
     '    RN16OOH + OH --> CARB14 + OH                                                                    ', &
     '    RN19OOH + OH --> CARB17 + OH                                                                    ', &
     '    CH3CO3H + OH --> CH3CO3                                                                         ', &
     '   C2H5CO3H + OH --> C2H5CO3                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_17 = (/ &
     '  HOCH2CO3H + OH --> HOCH2CO3                                                                       ', &
     '     RN8OOH + OH --> CARB6 + OH                                                                     ', &
     '    RN11OOH + OH --> CARB9 + OH                                                                     ', &
     '    RN14OOH + OH --> CARB12 + OH                                                                    ', &
     '    RN17OOH + OH --> CARB15 + OH                                                                    ', &
     '    RU14OOH + OH --> UCARB12 + OH                                                                   ', &
     '    RU12OOH + OH --> RU12O2                                                                         ', &
     '    RU10OOH + OH --> RU10O2                                                                         ', &
     '   NRU14OOH + OH --> NUCARB12 + OH                                                                  ', &
     '   NRU12OOH + OH --> NOA + CO + OH                                                                  ', &
     '  HOC2H4OOH + OH --> HOCH2CHO + OH                                                                  ', &
     '     RN9OOH + OH --> CARB7 + OH                                                                     ', &
     '    RN12OOH + OH --> CARB10 + OH                                                                    ', &
     '    RN15OOH + OH --> CARB13 + OH                                                                    ', &
     '    RN18OOH + OH --> CARB16 + OH                                                                    ', &
     '    NRN6OOH + OH --> 2 HCHO + OH + NO2                                                              ', &
     '    NRN9OOH + OH --> HCHO + OH + NO2 + CH3CHO                                                       ', &
     '   NRN12OOH + OH --> OH + NO2 + 2 CH3CHO                                                            ', &
     '    RA13OOH + OH --> CARB3 + UDCARB8 + OH                                                           ', &
     '    RA16OOH + OH --> CARB3 + UDCARB11 + OH                                                          ', &
     '    RA19OOH + OH --> UDCARB11 + CARB6 + OH                                                          ', &
     '   RTN28OOH + OH --> TNCARB26 + OH                                                                  ', &
     '   RTN26OOH + OH --> RTN26O2                                                                        ', &
     '  NRTN28OOH + OH --> TNCARB26 + OH + NO2                                                            ', &
     '   RTN25OOH + OH --> RTN25O2                                                                        ', &
     '   RTN24OOH + OH --> RTN24O2                                                                        ', &
     '   RTN23OOH + OH --> RTN23O2                                                                        ', &
     '   RTN14OOH + OH --> RTN14O2                                                                        ', &
     '   RTN10OOH + OH --> RTN10O2                                                                        ', &
     '   RTX28OOH + OH --> RTX28O2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_18 = (/ &
     '   RTX24OOH + OH --> TXCARB22 + OH                                                                  ', &
     '   RTX22OOH + OH --> CCARB12 + CH3COCH3 + OH                                                        ', &
     '  NRTX28OOH + OH --> NRTX28O2                                                                       ', &
     '    CH3CO3 + NO2 --> PAN                                                                            ', &
     '             PAN --> CH3CO3 + NO2                                                                   ', &
     '   C2H5CO3 + NO2 --> PPN                                                                            ', &
     '             PPN --> C2H5CO3 + NO2                                                                  ', &
     '  HOCH2CO3 + NO2 --> PHAN                                                                           ', &
     '            PHAN --> HOCH2CO3 + NO2                                                                 ', &
     '        PAN + OH --> CO + HCHO + NO2                                                                ', &
     '        PPN + OH --> CO + NO2 + CH3CHO                                                              ', &
     '       PHAN + OH --> CO + HCHO + NO2                                                                ', &
     '    RU12O2 + NO2 --> RU12PAN                                                                        ', &
     '         RU12PAN --> RU12O2 + NO2                                                                   ', &
     '    RU10O2 + NO2 --> MPAN                                                                           ', &
     '            MPAN --> RU10O2 + NO2                                                                   ', &
     '       MPAN + OH --> CARB7 + CO + NO2                                                               ', &
     '    RU12PAN + OH --> UCARB10 + NO2                                                                  ', &
     '   RTN26O2 + NO2 --> RTN26PAN                                                                       ', &
     '        RTN26PAN --> RTN26O2 + NO2                                                                  ', &
     '   RTN26PAN + OH --> CARB16 + CH3COCH3 + NO2                                                        ', &
     '       ANHY + OH --> HOCH2CH2O2                                                                     ', &
     '    UDCARB8 + OH --> ANHY + HO2                                                                     ', &
     '   UDCARB11 + OH --> ANHY + CH3OO                                                                   ', &
     '   UDCARB14 + OH --> ANHY + C2H5O2                                                                  ', &
     '      CH3CL + OH --> CH3OO                                                                          ', &
     '     CH2CL2 + OH --> CH3OO                                                                          ', &
     '      CHCL3 + OH --> CH3OO                                                                          ', &
     '    CH3CCL3 + OH --> C2H5O2                                                                         ', &
     '        TCE + OH --> HOCH2CH2O2                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_19 = (/ &
     '   TRICLETH + OH --> HOCH2CH2O2                                                                     ', &
     '   CDICLETH + OH --> HOCH2CH2O2                                                                     ', &
     '   TDICLETH + OH --> HOCH2CH2O2                                                                     ', &
     '     CH3OO + NO2 --> CH3O2NO2                                                                       ', &
     '        TNCARB12 --> HOCH2CO3 + RN9O2                                                               ', &
     '        TNCARB11 --> RTN10O2 + CO + HO2                                                             ', &
     '         RA22NO3 --> UDCARB14 + CARB6 + HO2 + NO2                                                   ', &
     '         RA22OOH --> UDCARB14 + CARB6 + HO2 + OH                                                    ', &
     '         RA25NO3 --> UDCARB17 + CARB6 + HO2 + NO2                                                   ', &
     '         RA25OOH --> UDCARB17 + CARB6 + HO2 + OH                                                    ', &
     '        UDCARB17 --> ANHY + RN10O2 + HO2                                                            ', &
     '        UDCARB17 --> RN16O2 + HO2                                                                   ', &
     '    RTN23O2 + NO --> RTN23NO3                                                                       ', &
     '   RTN23NO3 + OH --> TNCARB12 + CH3COCH3 + NO2                                                      ', &
     '   TNCARB12 + OH --> TNCARB11 + HO2                                                                 ', &
     '   TNCARB11 + OH --> RTN10O2 + CO                                                                   ', &
     '  TNCARB11 + NO3 --> RTN10O2 + CO + HNO3                                                            ', &
     '     TM123B + OH --> RA22AO2                                                                        ', &
     '     TM123B + OH --> RA22BO2                                                                        ', &
     '     TM124B + OH --> RA22AO2                                                                        ', &
     '     TM124B + OH --> RA22BO2                                                                        ', &
     '     TM135B + OH --> RA22AO2                                                                        ', &
     '    OETHTOL + OH --> RA22AO2                                                                        ', &
     '    METHTOL + OH --> RA22AO2                                                                        ', &
     '    PETHTOL + OH --> RA22AO2                                                                        ', &
     '    RA22AO2 + NO --> UDCARB14 + CARB6 + HO2 + NO2                                                   ', &
     '    RA22BO2 + NO --> CARB9 + UDCARB11 + HO2 + NO2                                                   ', &
     '    RA22AO2 + NO --> RA22NO3                                                                        ', &
     '    RA22BO2 + NO --> RA22NO3                                                                        ', &
     '   RA22AO2 + NO3 --> UDCARB14 + CARB6 + HO2 + NO2                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_20 = (/ &
     '   RA22BO2 + NO3 --> CARB9 + UDCARB11 + HO2 + NO2                                                   ', &
     '   RA22AO2 + HO2 --> RA22OOH                                                                        ', &
     '   RA22BO2 + HO2 --> RA22OOH                                                                        ', &
     '         RA22AO2 --> UDCARB14 + CARB6 + HO2                                                         ', &
     '         RA22BO2 --> CARB9 + UDCARB11 + HO2                                                         ', &
     '    RA22NO3 + OH --> UDCARB14 + CARB6 + NO2                                                         ', &
     '    RA22OOH + OH --> UDCARB14 + CARB6 + OH                                                          ', &
     '   DIME35EB + OH --> RA25O2                                                                         ', &
     '     RA25O2 + NO --> UDCARB17 + CARB6 + HO2 + NO2                                                   ', &
     '     RA25O2 + NO --> RA25NO3                                                                        ', &
     '    RA25O2 + NO3 --> UDCARB17 + CARB6 + HO2 + NO2                                                   ', &
     '    RA25O2 + HO2 --> RA25OOH                                                                        ', &
     '          RA25O2 --> UDCARB17 + CARB6 + HO2                                                         ', &
     '    RA25NO3 + OH --> UDCARB17 + CARB6 + NO2                                                         ', &
     '    RA25OOH + OH --> UDCARB17 + CARB6 + OH                                                          ', &
     '   UDCARB17 + OH --> RN16O2                                                                         ', &
     '   UDCARB17 + OH --> ANHY + RN10O2                                                                  ', &
     '             HCl --> HCl                                                                            ', &
     '             NH3 --> NH3                                                                            ', &
     '           ClNO2 --> ClNO2                                                                          ', &
     '        DMS + OH --> CH3SCH2OO + H2O                                                                ', &
     '        DMS + OH --> DMSO + HO2                                                                     ', &
     '       DMS + NO3 --> CH3SCH2OO + HNO3                                                               ', &
     '  CH3SCH2OO + NO --> CH3S + HCHO + NO2                                                              ', &
     '     2 CH3SCH2OO --> 2 CH3S + 2 HCHO                                                                ', &
     '       CH3S + O3 --> CH3SO                                                                          ', &
     '      CH3S + NO2 --> CH3SO + NO                                                                     ', &
     '     CH3SO + NO2 --> 0.18 SO2 + 0.82 CH3SO2 + 0.18 CH3OO + NO                                       ', &
     '      CH3SO + O3 --> CH3SO2                                                                         ', &
     '          CH3SO2 --> SO2 + CH3OO                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(7) :: EQN_NAMES_21 = (/ &
     '    CH3SO2 + NO2 --> CH3SO3 + NO                                                                    ', &
     '     CH3SO2 + O3 --> CH3SO3                                                                         ', &
     '    CH3SO3 + HO2 --> MSA                                                                            ', &
     '          CH3SO3 --> H2SO4 + CH3OO                                                                  ', &
     '       DMSO + OH --> 0.05 DMSO2 + 0.95 MSIA + 0.95 CH3OO                                            ', &
     '       MSIA + OH --> 0.05 MSA + 0.95 CH3SO2 + 0.05 HO2 + H2O                                        ', &
     '      MSIA + NO3 --> CH3SO2 + HNO3                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(637) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17, EQN_NAMES_18, EQN_NAMES_19, &
    EQN_NAMES_20, EQN_NAMES_21 /)

! INLINED global variables

! End INLINED global variables


END MODULE cri_mosaic_4bin_aq_Monitor
