! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : nmhc9_Monitor.f90
! Time                 : Thu Apr 14 13:13:56 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/nmhc9
! Equation file        : nmhc9.kpp
! Output root filename : nmhc9
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE nmhc9_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(59) :: SPC_NAMES = (/ &
     'C2H6        ','C4H10       ','MeCOCO      ', &
     'C3H8        ','N2O5        ','MeO2NO2     ', &
     'NACA        ','H2O2        ','PAA         ', &
     'CH3COOH     ','ISOOH       ','MeOOH       ', &
     'PAN         ','MPAN        ','HCOOH       ', &
     'EtOOH       ','PrOOH       ','PrONO2      ', &
     'C2H4        ','MEKOOH      ','O1D         ', &
     'HNO4        ','ACETP       ','CH4         ', &
     'HNO3        ','C3H6OOH     ','C4H9OOH     ', &
     'ACET        ','MVKOOH      ','MEK         ', &
     'CO          ','MeOH        ','ISON        ', &
     'PrO2        ','MGLO        ','ACETO2      ', &
     'C3H6        ','ISOP        ','ACETOL      ', &
     'C3H6O2      ','MVK         ','MEKO2       ', &
     'C4H9O2      ','ONIT        ','HCHO        ', &
     'ALD         ','EtO2        ','ISO2        ', &
     'MVKO2       ','MeO2        ','PA          ', &
     'NO3         ','O3          ','NO2         ', &
     'OH          ','NO          ','HO2         ', &
     'H2O         ','M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '           O3 --> O1D                                                                               ', &
     '      O1D + M --> O3                                                                                ', &
     '    O1D + H2O --> 2 OH                                                                              ', &
     '            M --> 2 O3                                                                              ', &
     '      O3 + OH --> HO2                                                                               ', &
     '     O3 + HO2 --> OH                                                                                ', &
     '     OH + HO2 --> H2O                                                                               ', &
     '        2 HO2 --> H2O2                                                                              ', &
     '         H2O2 --> 2 OH                                                                              ', &
     '    H2O2 + OH --> HO2                                                                               ', &
     '      CO + OH --> HO2                                                                               ', &
     '     CH4 + OH --> MeO2 + H2O                                                                        ', &
     '    O1D + CH4 --> 0.25 HCHO + 0.75 MeO2 + 0.75 OH + 0.4 HO2                                         ', &
     '   MeO2 + HO2 --> MeOOH                                                                             ', &
     '   MeO2 + HO2 --> HCHO + H2O                                                                        ', &
     '    MeO2 + NO --> HCHO + NO2 + HO2                                                                  ', &
     '       2 MeO2 --> 2 HCHO + 2 HO2                                                                    ', &
     '       2 MeO2 --> MeOH + HCHO                                                                       ', &
     '   MeO2 + NO3 --> HCHO + NO2 + HO2                                                                  ', &
     '        MeOOH --> HCHO + OH + HO2                                                                   ', &
     '   MeOOH + OH --> 0.3 HCHO + 0.7 MeO2 + 0.3 OH                                                      ', &
     '         HCHO --> CO + 2 HO2                                                                        ', &
     '         HCHO --> CO                                                                                ', &
     '    HCHO + OH --> CO + HO2 + H2O                                                                    ', &
     '   HCHO + NO3 --> HNO3 + CO + HO2                                                                   ', &
     '      O3 + NO --> NO2                                                                               ', &
     '     NO + HO2 --> NO2 + OH                                                                          ', &
     '          NO2 --> O3 + NO                                                                           ', &
     '     O3 + NO2 --> NO3                                                                               ', &
     '     NO2 + OH --> HNO3                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '    NO2 + HO2 --> HNO4                                                                              ', &
     '         HNO3 --> NO2 + OH                                                                          ', &
     '    HNO3 + OH --> NO3                                                                               ', &
     '          NO3 --> O3 + NO2                                                                          ', &
     '          NO3 --> NO                                                                                ', &
     '     NO3 + NO --> 2 NO2                                                                             ', &
     '    NO3 + NO2 --> N2O5                                                                              ', &
     '    NO3 + HO2 --> NO2 + OH                                                                          ', &
     '         N2O5 --> NO3 + NO2                                                                         ', &
     '         N2O5 --> NO3 + NO2                                                                         ', &
     '         N2O5 --> 2 HNO3                                                                            ', &
     '   N2O5 + H2O --> 2 HNO3                                                                            ', &
     '         HNO4 --> 0.39 NO3 + 0.61 NO2 + 0.39 OH + 0.61 HO2                                          ', &
     '         HNO4 --> NO2 + HO2                                                                         ', &
     '    HNO4 + OH --> NO2 + H2O                                                                         ', &
     '       OH + M --> HO2 + H2O                                                                         ', &
     '    MeOH + OH --> HCHO + HO2                                                                        ', &
     '   MeO2 + NO2 --> MeO2NO2                                                                           ', &
     '      MeO2NO2 --> MeO2 + NO2                                                                        ', &
     '      MeO2NO2 --> 0.39 HCHO + 0.61 MeO2 + 0.39 NO3 + 0.61 NO2                                       ', &
     '    ISOP + OH --> ISO2                                                                              ', &
     '   ISOP + NO3 --> ISON                                                                              ', &
     '    ISOP + O3 --> 0.09 H2O2 + 0.28 HCOOH + 0.14 CO + 0.65 MVK + 0.58 HCHO + 0.1 MVKO2 + 0.08 MeO2 + ', &
     '   ISO2 + HO2 --> ISOOH                                                                             ', &
     '    ISO2 + NO --> 0.12 ISON + 0.88 MVK + 0.88 HCHO + 0.88 NO2 + 0.88 HO2                            ', &
     '        ISOOH --> MVK + HCHO + OH + HO2                                                             ', &
     '   ISOOH + OH --> MVK + OH                                                                          ', &
     '     MVK + OH --> MVKO2                                                                             ', &
     '          MVK --> CO + HCHO + PA + HO2                                                              ', &
     '     MVK + O3 --> 0.45 HCOOH + 0.22 CO + 0.9 MGLO + 0.1 PA + 0.19 OH + 0.32 HO2                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '   MVKO2 + NO --> 0.25 CO + 0.5 MGLO + 0.25 ACETOL + 0.75 HCHO + 0.25 PA + NO2 + 0.75 HO2           ', &
     '  MVKO2 + HO2 --> MVKOOH                                                                            ', &
     '       MVKOOH --> 0.25 CO + 0.5 MGLO + 0.25 ACETOL + 0.75 HCHO + 0.25 PA + OH + 0.75 HO2            ', &
     '  MVKOOH + OH --> MVKO2                                                                             ', &
     '    ISON + OH --> NACA + ACETOL                                                                     ', &
     '         ISON --> MVK + HCHO + NO2 + HO2                                                            ', &
     '  MVKO2 + NO2 --> MPAN                                                                              ', &
     '       2 ISO2 --> 2 MVK + HCHO + HO2                                                                ', &
     '      2 MVKO2 --> 0.5 CO + MGLO + ACETOL + 0.5 HCHO + HO2                                           ', &
     '  ISO2 + MeO2 --> 0.25 MeOH + 0.25 MGLO + 0.25 ACETOL + 0.5 MVK + 1.25 HCHO + HO2                   ', &
     ' MVKO2 + MeO2 --> 0.125 CO + 0.25 MeOH + 0.5 MGLO + 0.375 ACETOL + 1.125 HCHO + 0.125 PA + 0.875 HO2', &
     '    MGLO + OH --> CO + PA                                                                           ', &
     '         MGLO --> CO + PA + HO2                                                                     ', &
     '  ACETOL + OH --> MGLO + HO2                                                                        ', &
     '       ACETOL --> HCHO + PA + HO2                                                                   ', &
     '     PA + HO2 --> PAA                                                                               ', &
     '     PA + HO2 --> CH3COOH + O3                                                                      ', &
     '      PA + NO --> MeO2 + NO2                                                                        ', &
     '     PA + NO2 --> PAN                                                                               ', &
     '    MeO2 + PA --> HCHO + MeO2 + HO2                                                                 ', &
     '    MeO2 + PA --> CH3COOH + HCHO                                                                    ', &
     '         2 PA --> 2 MeO2                                                                            ', &
     '     PA + NO3 --> MeO2 + NO2                                                                        ', &
     '          PAA --> MeO2 + OH                                                                         ', &
     '     PAA + OH --> PA                                                                                ', &
     '     PAN + OH --> HCHO + NO2                                                                        ', &
     '          PAN --> PA + NO2                                                                          ', &
     '          PAN --> PA + NO2                                                                          ', &
     '    MPAN + OH --> ACETOL + NO2                                                                      ', &
     '         MPAN --> MVKO2 + NO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '         MPAN --> ACETOL + NO2                                                                      ', &
     ' CH3COOH + OH --> MeO2 + H2O                                                                        ', &
     '   HCOOH + OH --> HO2                                                                               ', &
     '    NACA + OH --> CO + HCHO + NO2                                                                   ', &
     '         NACA --> CO + HCHO + NO2                                                                   ', &
     '    C2H6 + OH --> EtO2 + H2O                                                                        ', &
     '   EtO2 + HO2 --> EtOOH                                                                             ', &
     '  EtO2 + MeO2 --> 0.25 MeOH + 0.75 HCHO + 0.75 ALD + HO2                                            ', &
     '    EtO2 + PA --> 0.18 CH3COOH + ALD + 0.82 MeO2 + 0.82 HO2                                         ', &
     '    EtO2 + NO --> ALD + NO2 + HO2                                                                   ', &
     '   EtO2 + NO3 --> ALD + NO2 + HO2                                                                   ', &
     '     ALD + OH --> PA + H2O                                                                          ', &
     '          ALD --> CO + MeO2 + HO2                                                                   ', &
     '    ALD + NO3 --> HNO3 + PA                                                                         ', &
     '        EtOOH --> ALD + OH + HO2                                                                    ', &
     '   EtOOH + OH --> 0.7 ALD + 0.3 EtO2 + 0.7 OH                                                       ', &
     '    C3H8 + OH --> 0.82 PrO2 + 0.18 EtO2 + H2O                                                       ', &
     '    PrO2 + NO --> 0.04 PrONO2 + 0.96 ACET + 0.96 NO2 + 0.96 HO2                                     ', &
     '   PrO2 + HO2 --> PrOOH                                                                             ', &
     '  PrO2 + MeO2 --> ACET + 0.2 MeOH + 0.8 HCHO + 0.8 HO2                                              ', &
     '        PrOOH --> ACET + OH + HO2                                                                   ', &
     '   PrOOH + OH --> 0.7 ACET + 0.3 PrO2 + 0.7 OH                                                      ', &
     '       PrONO2 --> ACET + NO2 + HO2                                                                  ', &
     '  PrONO2 + OH --> ACET + NO2                                                                        ', &
     '    ACET + OH --> ACETO2 + H2O                                                                      ', &
     '         ACET --> MeO2 + PA                                                                         ', &
     '  ACETO2 + NO --> HCHO + PA + NO2                                                                   ', &
     ' ACETO2 + HO2 --> ACETP                                                                             ', &
     'ACETO2 + MeO2 --> 0.5 MeOH + 0.5 MGLO + 0.2 ACETOL + 0.8 HCHO + 0.3 PA + 0.3 HO2                    ', &
     '   ACETP + OH --> 0.7 MGLO + 0.3 ACETO2 + 0.7 OH                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(25) :: EQN_NAMES_4 = (/ &
     '        ACETP --> PA + OH + HO2                                                                     ', &
     '    C3H6 + OH --> C3H6O2                                                                            ', &
     '    C3H6 + O3 --> 0.22 HCOOH + 0.06 CH4 + 0.31 CO + 0.03 MeOH + 0.04 MGLO + 0.57 HCHO + 0.47 ALD + 0', &
     '   C3H6 + NO3 --> ONIT                                                                              ', &
     '  C3H6O2 + NO --> 0.02 ONIT + 0.98 HCHO + 0.98 ALD + 0.98 NO2 + 0.98 HO2                            ', &
     ' C3H6O2 + HO2 --> C3H6OOH                                                                           ', &
     ' C3H6OOH + OH --> 0.5 ACETOL + 0.5 C3H6O2 + 0.5 OH + H2O                                            ', &
     '      C3H6OOH --> HCHO + ALD + OH + HO2                                                             ', &
     '    C2H4 + OH --> 0.666667 C3H6O2                                                                   ', &
     '    C2H4 + O3 --> 0.54 HCOOH + 0.23 CO + HCHO + 0.12 OH + 0.22 HO2                                  ', &
     '   C4H10 + OH --> C4H9O2 + H2O                                                                      ', &
     '  C4H9O2 + NO --> 0.56 MEK + 0.16 ONIT + 0.84 ALD + 0.28 EtO2 + 0.84 NO2 + 0.56 HO2                 ', &
     ' C4H9O2 + HO2 --> C4H9OOH                                                                           ', &
     'C4H9O2 + MeO2 --> 0.88 MEK + 0.18 MeOH + 0.68 HCHO + 0.12 ALD + 0.12 EtO2 + 1.23 HO2                ', &
     ' C4H9OOH + OH --> 0.85 MEK + 0.15 C4H9O2 + 0.85 OH + 0.85 H2O                                       ', &
     '      C4H9OOH --> 0.67 MEK + 0.33 ALD + 0.33 EtO2 + OH + 0.67 HO2                                   ', &
     '          MEK --> EtO2 + PA                                                                         ', &
     '     MEK + OH --> MEKO2                                                                             ', &
     '   MEKO2 + NO --> 0.015 ONIT + 0.985 ALD + 0.985 PA + 0.985 NO2                                     ', &
     '  MEKO2 + HO2 --> MEKOOH                                                                            ', &
     '  MEKOOH + OH --> 0.8 MeCOCO + 0.2 MEKO2 + 0.8 OH                                                   ', &
     '       MEKOOH --> ALD + PA + OH                                                                     ', &
     '       MeCOCO --> 2 PA                                                                              ', &
     '    ONIT + OH --> MEK + NO2                                                                         ', &
     '         ONIT --> 0.67 MEK + 0.33 ALD + 0.33 EtO2 + NO2 + 0.67 HO2                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(145) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

! INLINED global variables

! End INLINED global variables


END MODULE nmhc9_Monitor
