! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbmz_bb_Monitor.f90
! Time                 : Thu Apr 14 13:13:30 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/cbmz_bb
! Equation file        : cbmz_bb.kpp
! Output root filename : cbmz_bb
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbmz_bb_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(58) :: SPC_NAMES = (/ &
     'H2SO4       ','HCl         ','NH3         ', &
     'HCOOH       ','RCOOH       ','O1D         ', &
     'SO2         ','ANOL        ','H2O2        ', &
     'PAN         ','TOL         ','N2O5        ', &
     'XYL         ','CH4         ','CRO         ', &
     'HNO4        ','C2H6        ','TO2         ', &
     'XPAR        ','CH3OOH      ','ETHOOH      ', &
     'HONO        ','C2H4        ','CH3OH       ', &
     'O3P         ','CRES        ','HNO3        ', &
     'CO          ','PAR         ','OPEN        ', &
     'ISOPN       ','ISOPP       ','ISOPO2      ', &
     'OLET        ','ISOP        ','HCHO        ', &
     'XO2         ','AONE        ','OLEI        ', &
     'ETHP        ','NAP         ','MGLY        ', &
     'ALD2        ','CH3O2       ','ISOPRD      ', &
     'ANO2        ','ROOH        ','RO2         ', &
     'ONIT        ','OH          ','O3          ', &
     'NO2         ','C2O3        ','NO3         ', &
     'HO2         ','NO          ','H2O         ', &
     'M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '         NO2 --> O3P + NO                                                                           ', &
     '         NO3 --> 0.89 O3P + 0.89 NO2 + 0.11 NO                                                      ', &
     '        HONO --> OH + NO                                                                            ', &
     '        HNO3 --> OH + NO2                                                                           ', &
     '        HNO4 --> NO2 + HO2                                                                          ', &
     '        N2O5 --> NO2 + NO3                                                                          ', &
     '          O3 --> O3P                                                                                ', &
     '          O3 --> O1D                                                                                ', &
     '        H2O2 --> 2 OH                                                                               ', &
     '        HCHO --> CO + 2 HO2                                                                         ', &
     '        HCHO --> CO                                                                                 ', &
     '      CH3OOH --> HCHO + OH + HO2                                                                    ', &
     '      ETHOOH --> ALD2 + OH + HO2                                                                    ', &
     '        ALD2 --> CO + CH3O2 + HO2                                                                   ', &
     '        AONE --> CH3O2 + C2O3                                                                       ', &
     '        MGLY --> CO + C2O3 + HO2                                                                    ', &
     '        OPEN --> CO + C2O3 + HO2                                                                    ', &
     '        ROOH --> 1.98 XPAR + 0.4 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + OH + 0.9 HO2               ', &
     '        ONIT --> 1.98 XPAR + 0.41 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + NO2 + 0.9 HO2             ', &
     '      ISOPRD --> 0.33 CO + 0.2 HCHO + 0.03 AONE + 0.07 ALD2 + 0.7 CH3O2 + 0.97 C2O3 + 0.33 HO2      ', &
     '     O1D + M --> O3P                                                                                ', &
     '   O1D + H2O --> 2 OH                                                                               ', &
     '     O3P + M --> O3                                                                                 ', &
     '    O3P + O3 --> 0.42 M                                                                             ', &
     '   O3P + NO2 --> NO                                                                                 ', &
     '   O3P + NO2 --> NO3                                                                                ', &
     '    O3P + NO --> NO2                                                                                ', &
     '     O3 + NO --> NO2                                                                                ', &
     '    O3 + NO2 --> NO3                                                                                ', &
     '     OH + O3 --> HO2                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '    O3 + HO2 --> OH                                                                                 ', &
     '      OH + M --> HO2 + H2O                                                                          ', &
     '     OH + NO --> HONO                                                                               ', &
     '    OH + NO2 --> HNO3                                                                               ', &
     '    OH + NO3 --> NO2 + HO2                                                                          ', &
     '   HONO + OH --> NO2                                                                                ', &
     '   HNO3 + OH --> NO3                                                                                ', &
     '   HNO4 + OH --> NO2                                                                                ', &
     '    OH + HO2 --> H2O + 0.21 M                                                                       ', &
     '   H2O2 + OH --> HO2                                                                                ', &
     '       2 HO2 --> H2O2                                                                               ', &
     ' 2 HO2 + H2O --> H2O2                                                                               ', &
     '    HO2 + NO --> OH + NO2                                                                           ', &
     '   NO2 + HO2 --> HNO4                                                                               ', &
     '   NO2 + HO2 --> HONO                                                                               ', &
     '        HNO4 --> NO2 + HO2                                                                          ', &
     '    NO3 + NO --> 2 NO2                                                                              ', &
     '   NO2 + NO3 --> NO2 + NO                                                                           ', &
     '   NO2 + NO3 --> N2O5                                                                               ', &
     '       2 NO3 --> 2 NO2                                                                              ', &
     '   NO3 + HO2 --> 0.3 HNO3 + 0.7 OH + 0.7 NO2                                                        ', &
     '  N2O5 + H2O --> 2 HNO3                                                                             ', &
     '        N2O5 --> NO2 + NO3                                                                          ', &
     '     CO + OH --> HO2                                                                                ', &
     '    SO2 + OH --> H2SO4 + HO2                                                                        ', &
     '    CH4 + OH --> CH3O2                                                                              ', &
     '   C2H6 + OH --> ETHP                                                                               ', &
     '    PAR + OH --> RO2                                                                                ', &
     '   HCHO + OH --> CO + HO2                                                                           ', &
     '  HCHO + NO3 --> HNO3 + CO + HO2                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '   ALD2 + OH --> C2O3                                                                               ', &
     '  ALD2 + NO3 --> HNO3 + C2O3                                                                        ', &
     '   AONE + OH --> ANO2                                                                               ', &
     '   MGLY + OH --> XO2 + C2O3                                                                         ', &
     '  MGLY + NO3 --> HNO3 + CO + C2O3                                                                   ', &
     '   C2H4 + O3 --> 0.52 HCOOH + 0.24 CO + HCHO + 0.12 OH + 0.22 HO2                                   ', &
     '   C2H4 + OH --> 1.56 HCHO + XO2 + 0.22 ALD2 + HO2                                                  ', &
     '   OLET + O3 --> 0.22 HCOOH + 0.09 RCOOH + 0.06 CH4 + 0.01 C2H6 + 1.06 XPAR + 0.03 CH3OH + 0.31 CO +', &
     '   OLEI + O3 --> 0.16 RCOOH + 0.08 CH4 + 0.01 C2H6 + 2.26 XPAR + 0.04 CH3OH + 0.3 CO + 0.07 AONE + 0', &
     '   OLET + OH --> XPAR + HCHO + XO2 + ALD2 + HO2                                                     ', &
     '   OLEI + OH --> 2.23 XPAR + XO2 + 0.23 AONE + 1.77 ALD2 + HO2                                      ', &
     '  OLET + NO3 --> NAP                                                                                ', &
     '  OLEI + NO3 --> NAP                                                                                ', &
     '    TOL + OH --> 0.8 TO2 + 0.12 CRES + 0.08 XO2 + 0.2 HO2                                           ', &
     '    XYL + OH --> 0.45 TO2 + 0.05 CRES + 1.1 PAR + 0.5 XO2 + 0.8 MGLY + 0.55 HO2                     ', &
     '    TO2 + NO --> 0.95 OPEN + 0.05 ONIT + 0.95 NO2 + 0.95 HO2                                        ', &
     '   CRES + OH --> 0.4 CRO + 0.3 OPEN + 0.6 XO2 + 0.6 HO2                                             ', &
     '  CRES + NO3 --> CRO + HNO3                                                                         ', &
     '   CRO + NO2 --> ONIT                                                                               ', &
     '   OPEN + OH --> 2 CO + HCHO + XO2 + C2O3 + 2 HO2                                                   ', &
     '   OPEN + O3 --> 0.69 CO + 0.7 HCHO + 0.03 XO2 + 0.2 MGLY + 0.03 ALD2 + 0.08 OH + 0.62 C2O3 + 0.76 H', &
     '   ISOP + OH --> ISOPP + 0.08 XO2                                                                   ', &
     '   ISOP + O3 --> 0.39 RCOOH + 0.07 CO + 0.6 HCHO + 0.2 XO2 + 0.15 ALD2 + 0.65 ISOPRD + 0.27 OH + 0.2', &
     '  ISOP + NO3 --> ISOPN                                                                              ', &
     ' ISOPRD + OH --> 0.5 ISOPO2 + 0.2 XO2 + 0.5 C2O3                                                    ', &
     ' ISOPRD + O3 --> 0.46 RCOOH + 0.16 CO + 0.15 HCHO + 0.07 XO2 + 0.09 AONE + 0.85 MGLY + 0.02 ALD2 + 0', &
     'ISOPRD + NO3 --> 0.07 HNO3 + 0.64 CO + 1.86 PAR + 0.28 HCHO + 0.93 XO2 + 0.28 ALD2 + 0.93 ONIT + 0.0', &
     '  ISOPP + NO --> 0.18 PAR + 0.63 HCHO + 0.91 ISOPRD + 0.09 ONIT + 0.91 NO2 + 0.91 HO2               ', &
     '  ISOPN + NO --> 1.6 PAR + 0.8 ALD2 + 0.2 ISOPRD + 0.8 ONIT + 1.2 NO2 + 0.8 HO2                     ', &
     ' ISOPO2 + NO --> 0.59 CO + 0.25 HCHO + 0.63 AONE + 0.34 MGLY + 0.55 ALD2 + NO2 + HO2                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     ' ISOPP + HO2 --> ROOH                                                                               ', &
     ' ISOPN + HO2 --> 2 PAR + ONIT                                                                       ', &
     'ISOPO2 + HO2 --> ROOH                                                                               ', &
     ' CH3OOH + OH --> 0.3 HCHO + 0.7 CH3O2 + 0.3 OH                                                      ', &
     ' ETHOOH + OH --> 0.7 ETHP + 0.3 ALD2 + 0.3 OH                                                       ', &
     '   ROOH + OH --> 0.42 XPAR + 0.19 MGLY + 0.04 ALD2 + 0.77 RO2 + 0.23 OH                             ', &
     '   ONIT + OH --> NAP                                                                                ', &
     '  NO2 + C2O3 --> PAN                                                                                ', &
     '         PAN --> NO2 + C2O3                                                                         ', &
     '  CH3OH + OH --> HCHO + HO2                                                                         ', &
     '  CH3O2 + NO --> HCHO + NO2 + HO2                                                                   ', &
     '   ETHP + NO --> ALD2 + NO2 + HO2                                                                   ', &
     '    RO2 + NO --> 1.68 XPAR + 0.34 XO2 + 0.62 AONE + 0.08 ETHP + 0.25 ALD2 + 0.16 ONIT + 0.84 NO2 + 0', &
     '   C2O3 + NO --> CH3O2 + NO2                                                                        ', &
     '   ANO2 + NO --> HCHO + NO2 + C2O3                                                                  ', &
     '    NAP + NO --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 1.5 NO2 + 0.5 HO2                          ', &
     '    XO2 + NO --> NO2                                                                                ', &
     ' CH3O2 + NO3 --> HCHO + NO2 + HO2                                                                   ', &
     '  ETHP + NO3 --> ALD2 + NO2 + HO2                                                                   ', &
     '   RO2 + NO3 --> 1.98 XPAR + 0.4 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + NO2 + 0.9 HO2              ', &
     '  C2O3 + NO3 --> CH3O2 + NO2                                                                        ', &
     '  ANO2 + NO3 --> HCHO + NO2 + C2O3                                                                  ', &
     '   NAP + NO3 --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 1.5 NO2 + 0.5 HO2                          ', &
     '   XO2 + NO3 --> NO2                                                                                ', &
     ' CH3O2 + HO2 --> CH3OOH                                                                             ', &
     '  ETHP + HO2 --> ETHOOH                                                                             ', &
     '   RO2 + HO2 --> ROOH                                                                               ', &
     '  C2O3 + HO2 --> 0.4 RCOOH + 0.4 O3                                                                 ', &
     '  ANO2 + HO2 --> ROOH                                                                               ', &
     '   NAP + HO2 --> ONIT                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(16) :: EQN_NAMES_4 = (/ &
     '   XO2 + HO2 -->                                                                                    ', &
     '   ANOL + OH --> ALD2 + HO2                                                                         ', &
     '  XPAR + PAR -->                                                                                    ', &
     '         HCl --> HCl                                                                                ', &
     '         NH3 --> NH3                                                                                ', &
     '       H2SO4 --> H2SO4                                                                              ', &
     '       CH3O2 --> 0.34 CH3OH + 0.66 HCHO + 0.32 HO2                                                  ', &
     '        ETHP --> 0.2 C2H6 + 0.8 ALD2 + 0.6 HO2                                                      ', &
     '         RO2 --> 1.25 XPAR + 0.24 XO2 + 0.57 AONE + 0.06 ETHP + 0.21 ALD2 + 0.54 HO2                ', &
     '        C2O3 --> CH3O2                                                                              ', &
     '        ANO2 --> 0.7 HCHO + 0.15 AONE + 0.15 MGLY + 0.7 C2O3                                        ', &
     '         NAP --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 0.5 NO2                                    ', &
     '       ISOPP --> ISOPRD                                                                             ', &
     '       ISOPN --> 2 PAR + ALD2 + ONIT                                                                ', &
     '      ISOPO2 --> 0.5 AONE + 0.5 ALD2                                                                ', &
     '         XO2 -->                                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(136) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

! INLINED global variables

! End INLINED global variables


END MODULE cbmz_bb_Monitor
