! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm4_LinearAlgebra.f90
! Time                 : Tue Apr 12 23:42:45 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/cbm4
! Equation file        : cbm4.kpp
! Output root filename : cbm4
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm4_LinearAlgebra

  USE cbm4_Parameters
  USE cbm4_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(3)
  XX(3) = X(3)/JVS(6)
  XX(4) = X(4)/JVS(9)
  XX(5) = X(5)/JVS(14)
  XX(6) = X(6)/JVS(16)
  XX(7) = X(7)/JVS(19)
  XX(8) = X(8)/JVS(21)
  XX(9) = X(9)/JVS(30)
  XX(10) = X(10)/JVS(34)
  XX(11) = X(11)/JVS(40)
  XX(12) = X(12)/JVS(44)
  XX(13) = (X(13)-JVS(22)*XX(8))/(JVS(51))
  XX(14) = (X(14)-JVS(10)*XX(4)-JVS(45)*XX(12))/(JVS(58))
  XX(15) = X(15)/JVS(63)
  XX(16) = X(16)/JVS(69)
  XX(17) = (X(17)-JVS(70)*XX(16))/(JVS(80))
  XX(18) = X(18)/JVS(91)
  XX(19) = (X(19)-JVS(64)*XX(15)-JVS(71)*XX(16)-JVS(92)*XX(18))/(JVS(107))
  XX(20) = (X(20)-JVS(23)*XX(8)-JVS(52)*XX(13)-JVS(93)*XX(18))/(JVS(114))
  XX(21) = (X(21)-JVS(46)*XX(12)-JVS(72)*XX(16))/(JVS(124))
  XX(22) = (X(22)-JVS(24)*XX(8)-JVS(65)*XX(15)-JVS(73)*XX(16)-JVS(81)*XX(17)-JVS(94)*XX(18)-JVS(115)*XX(20)-JVS(125)&
             &*XX(21))/(JVS(135))
  XX(23) = (X(23)-JVS(25)*XX(8)-JVS(74)*XX(16)-JVS(95)*XX(18)-JVS(116)*XX(20)-JVS(126)*XX(21))/(JVS(141))
  XX(24) = (X(24)-JVS(47)*XX(12)-JVS(75)*XX(16)-JVS(96)*XX(18)-JVS(127)*XX(21))/(JVS(152))
  XX(25) = (X(25)-JVS(2)*XX(1)-JVS(66)*XX(15)-JVS(76)*XX(16)-JVS(82)*XX(17)-JVS(97)*XX(18)-JVS(108)*XX(19)-JVS(117)&
             &*XX(20)-JVS(128)*XX(21)-JVS(136)*XX(22)-JVS(142)*XX(23)-JVS(153)*XX(24))/(JVS(163))
  XX(26) = (X(26)-JVS(7)*XX(3)-JVS(11)*XX(4)-JVS(17)*XX(6)-JVS(31)*XX(9)-JVS(35)*XX(10)-JVS(48)*XX(12)-JVS(53)*XX(13)&
             &-JVS(98)*XX(18)-JVS(118)*XX(20)-JVS(154)*XX(24)-JVS(164)*XX(25))/(JVS(185))
  XX(27) = (X(27)-JVS(4)*XX(2)-JVS(12)*XX(4)-JVS(15)*XX(5)-JVS(20)*XX(7)-JVS(26)*XX(8)-JVS(32)*XX(9)-JVS(36)*XX(10)&
             &-JVS(41)*XX(11)-JVS(49)*XX(12)-JVS(54)*XX(13)-JVS(59)*XX(14)-JVS(67)*XX(15)-JVS(77)*XX(16)-JVS(83)*XX(17)&
             &-JVS(99)*XX(18)-JVS(109)*XX(19)-JVS(119)*XX(20)-JVS(129)*XX(21)-JVS(137)*XX(22)-JVS(143)*XX(23)-JVS(155)&
             &*XX(24)-JVS(165)*XX(25)-JVS(186)*XX(26))/(JVS(211))
  XX(28) = (X(28)-JVS(5)*XX(2)-JVS(37)*XX(10)-JVS(100)*XX(18)-JVS(130)*XX(21)-JVS(166)*XX(25)-JVS(187)*XX(26)-JVS(212)&
             &*XX(27))/(JVS(236))
  XX(29) = (X(29)-JVS(27)*XX(8)-JVS(78)*XX(16)-JVS(84)*XX(17)-JVS(101)*XX(18)-JVS(120)*XX(20)-JVS(131)*XX(21)-JVS(138)&
             &*XX(22)-JVS(144)*XX(23)-JVS(156)*XX(24)-JVS(167)*XX(25)-JVS(188)*XX(26)-JVS(213)*XX(27)-JVS(237)*XX(28))&
             &/(JVS(251))
  XX(30) = (X(30)-JVS(13)*XX(4)-JVS(18)*XX(6)-JVS(28)*XX(8)-JVS(50)*XX(12)-JVS(60)*XX(14)-JVS(79)*XX(16)-JVS(102)*XX(18)&
             &-JVS(110)*XX(19)-JVS(121)*XX(20)-JVS(132)*XX(21)-JVS(139)*XX(22)-JVS(145)*XX(23)-JVS(157)*XX(24)-JVS(168)&
             &*XX(25)-JVS(189)*XX(26)-JVS(214)*XX(27)-JVS(238)*XX(28)-JVS(252)*XX(29))/(JVS(267))
  XX(31) = (X(31)-JVS(29)*XX(8)-JVS(33)*XX(9)-JVS(42)*XX(11)-JVS(61)*XX(14)-JVS(103)*XX(18)-JVS(111)*XX(19)-JVS(133)&
             &*XX(21)-JVS(158)*XX(24)-JVS(169)*XX(25)-JVS(190)*XX(26)-JVS(215)*XX(27)-JVS(239)*XX(28)-JVS(253)*XX(29)&
             &-JVS(268)*XX(30))/(JVS(286))
  XX(32) = (X(32)-JVS(8)*XX(3)-JVS(104)*XX(18)-JVS(134)*XX(21)-JVS(191)*XX(26)-JVS(216)*XX(27)-JVS(240)*XX(28)-JVS(254)&
             &*XX(29)-JVS(269)*XX(30)-JVS(287)*XX(31))/(JVS(300))
  XX(32) = XX(32)
  XX(31) = XX(31)-JVS(299)*XX(32)
  XX(30) = XX(30)-JVS(285)*XX(31)-JVS(298)*XX(32)
  XX(29) = XX(29)-JVS(266)*XX(30)-JVS(284)*XX(31)-JVS(297)*XX(32)
  XX(28) = XX(28)-JVS(250)*XX(29)-JVS(265)*XX(30)-JVS(283)*XX(31)-JVS(296)*XX(32)
  XX(27) = XX(27)-JVS(235)*XX(28)-JVS(249)*XX(29)-JVS(264)*XX(30)-JVS(282)*XX(31)-JVS(295)*XX(32)
  XX(26) = XX(26)-JVS(210)*XX(27)-JVS(234)*XX(28)-JVS(248)*XX(29)-JVS(263)*XX(30)-JVS(281)*XX(31)-JVS(294)*XX(32)
  XX(25) = XX(25)-JVS(184)*XX(26)-JVS(209)*XX(27)-JVS(233)*XX(28)-JVS(247)*XX(29)-JVS(262)*XX(30)-JVS(280)*XX(31)&
             &-JVS(293)*XX(32)
  XX(24) = XX(24)-JVS(183)*XX(26)-JVS(208)*XX(27)-JVS(232)*XX(28)-JVS(246)*XX(29)-JVS(261)*XX(30)-JVS(279)*XX(31)&
             &-JVS(292)*XX(32)
  XX(23) = XX(23)-JVS(151)*XX(24)-JVS(162)*XX(25)-JVS(182)*XX(26)-JVS(207)*XX(27)-JVS(231)*XX(28)-JVS(245)*XX(29)&
             &-JVS(260)*XX(30)-JVS(278)*XX(31)
  XX(22) = XX(22)-JVS(140)*XX(23)-JVS(150)*XX(24)-JVS(161)*XX(25)-JVS(181)*XX(26)-JVS(206)*XX(27)-JVS(230)*XX(28)&
             &-JVS(244)*XX(29)-JVS(259)*XX(30)-JVS(277)*XX(31)-JVS(291)*XX(32)
  XX(21) = XX(21)-JVS(205)*XX(27)-JVS(229)*XX(28)-JVS(243)*XX(29)-JVS(258)*XX(30)
  XX(20) = XX(20)-JVS(149)*XX(24)-JVS(180)*XX(26)-JVS(204)*XX(27)-JVS(228)*XX(28)-JVS(276)*XX(31)
  XX(19) = XX(19)-JVS(123)*XX(21)-JVS(148)*XX(24)-JVS(160)*XX(25)-JVS(179)*XX(26)-JVS(203)*XX(27)-JVS(227)*XX(28)&
             &-JVS(275)*XX(31)-JVS(290)*XX(32)
  XX(18) = XX(18)-JVS(178)*XX(26)-JVS(274)*XX(31)
  XX(17) = XX(17)-JVS(90)*XX(18)-JVS(122)*XX(21)-JVS(147)*XX(24)-JVS(159)*XX(25)-JVS(202)*XX(27)-JVS(226)*XX(28)&
             &-JVS(242)*XX(29)
  XX(16) = XX(16)-JVS(201)*XX(27)-JVS(225)*XX(28)
  XX(15) = XX(15)-JVS(68)*XX(16)-JVS(89)*XX(18)-JVS(200)*XX(27)-JVS(224)*XX(28)-JVS(289)*XX(32)
  XX(14) = XX(14)-JVS(88)*XX(18)-JVS(106)*XX(19)-JVS(177)*XX(26)-JVS(199)*XX(27)-JVS(223)*XX(28)-JVS(257)*XX(30)
  XX(13) = XX(13)-JVS(87)*XX(18)-JVS(113)*XX(20)-JVS(146)*XX(24)-JVS(176)*XX(26)-JVS(222)*XX(28)-JVS(273)*XX(31)
  XX(12) = XX(12)-JVS(198)*XX(27)-JVS(256)*XX(30)
  XX(11) = XX(11)-JVS(57)*XX(14)-JVS(105)*XX(19)-JVS(175)*XX(26)-JVS(221)*XX(28)-JVS(272)*XX(31)
  XX(10) = XX(10)-JVS(174)*XX(26)-JVS(197)*XX(27)-JVS(220)*XX(28)
  XX(9) = XX(9)-JVS(173)*XX(26)-JVS(196)*XX(27)-JVS(271)*XX(31)
  XX(8) = XX(8)-JVS(270)*XX(31)
  XX(7) = XX(7)-JVS(39)*XX(11)-JVS(56)*XX(14)-JVS(62)*XX(15)-JVS(86)*XX(18)-JVS(112)*XX(20)-JVS(195)*XX(27)-JVS(219)&
            &*XX(28)
  XX(6) = XX(6)-JVS(43)*XX(12)-JVS(172)*XX(26)-JVS(255)*XX(30)
  XX(5) = XX(5)-JVS(38)*XX(11)-JVS(55)*XX(14)-JVS(85)*XX(18)-JVS(194)*XX(27)-JVS(218)*XX(28)
  XX(4) = XX(4)-JVS(171)*XX(26)
  XX(3) = XX(3)-JVS(170)*XX(26)-JVS(288)*XX(32)
  XX(2) = XX(2)-JVS(193)*XX(27)-JVS(217)*XX(28)
  XX(1) = XX(1)-JVS(192)*XX(27)-JVS(241)*XX(29)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cbm4_LinearAlgebra

