! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc99_Monitor.f90
! Time                 : Thu Apr 14 13:14:33 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/saprc99
! Equation file        : saprc99.kpp
! Output root filename : saprc99
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc99_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(81) :: SPC_NAMES = (/ &
     'H2SO4       ','CO2         ','HCOOH       ', &
     'CCO_OH      ','RCO_OH      ','CCO_OOH     ', &
     'RCO_OOH     ','XN          ','XC          ', &
     'SO2         ','O1D         ','CH4         ', &
     'C2H6        ','BACL        ','PAN         ', &
     'PAN2        ','PBZN        ','MA_PAN      ', &
     'H2O2        ','C3H8        ','ETOH        ', &
     'N2O5        ','HONO        ','ALK3        ', &
     'TBU_O       ','ALK5        ','ARO2        ', &
     'MEOH        ','COOH        ','HOCOO       ', &
     'BZNO2_O     ','HNO4        ','ALK4        ', &
     'ARO1        ','DCB2        ','DCB3        ', &
     'CRES        ','DCB1        ','C2H2        ', &
     'NPHE        ','BALD        ','ROOH        ', &
     'PHEN        ','MGLY        ','CO          ', &
     'ACET        ','HNO3        ','ETHENE      ', &
     'GLY         ','C3H6        ','BZ_O        ', &
     'ISOPRENE    ','R2O2        ','TERP        ', &
     'METHACRO    ','OLE1        ','ISOPROD     ', &
     'OLE2        ','MVK         ','CCHO        ', &
     'HCHO        ','RNO3        ','O3P         ', &
     'RCHO        ','MEK         ','PROD2       ', &
     'O3          ','CCO_O2      ','RO2_N       ', &
     'MA_RCO3     ','OH          ','RCO_O2      ', &
     'NO          ','NO2         ','NO3         ', &
     'C_O2        ','RO2_R       ','HO2         ', &
     'BZCO_O2     ','H2O         ','M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              NO2 --> O3P + NO                                                                      ', &
     '          O3P + M --> O3                                                                            ', &
     '         O3P + O3 --> M                                                                             ', &
     '     O3P + NO + M --> NO2                                                                           ', &
     '        O3P + NO2 --> NO                                                                            ', &
     '        O3P + NO2 --> NO3                                                                           ', &
     '          O3 + NO --> NO2                                                                           ', &
     '         O3 + NO2 --> NO3                                                                           ', &
     '         NO + NO3 --> 2 NO2                                                                         ', &
     '         2 NO + M --> 2 NO2                                                                         ', &
     '        NO2 + NO3 --> N2O5                                                                          ', &
     '             N2O5 --> NO2 + NO3                                                                     ', &
     '       N2O5 + H2O --> 2 HNO3                                                                        ', &
     '        NO2 + NO3 --> NO + NO2                                                                      ', &
     '              NO3 --> NO                                                                            ', &
     '              NO3 --> O3P + NO2                                                                     ', &
     '               O3 --> O3P                                                                           ', &
     '               O3 --> O1D                                                                           ', &
     '        O1D + H2O --> 2 OH                                                                          ', &
     '          O1D + M --> O3P                                                                           ', &
     '          OH + NO --> HONO                                                                          ', &
     '             HONO --> OH + NO                                                                       ', &
     '             HONO --> NO2 + HO2                                                                     ', &
     '        HONO + OH --> NO2                                                                           ', &
     '         OH + NO2 --> HNO3                                                                          ', &
     '         OH + NO3 --> NO2 + HO2                                                                     ', &
     '        HNO3 + OH --> NO3                                                                           ', &
     '             HNO3 --> OH + NO2                                                                      ', &
     '          CO + OH --> HO2                                                                           ', &
     '          O3 + OH --> HO2                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '         NO + HO2 --> OH + NO2                                                                      ', &
     '        NO2 + HO2 --> HNO4                                                                          ', &
     '             HNO4 --> NO2 + HO2                                                                     ', &
     '             HNO4 --> 0.39 OH + 0.61 NO2 + 0.39 NO3 + 0.61 HO2                                      ', &
     '        HNO4 + OH --> NO2                                                                           ', &
     '         O3 + HO2 --> OH                                                                            ', &
     '            2 HO2 --> H2O2                                                                          ', &
     '      2 HO2 + H2O --> H2O2                                                                          ', &
     '        NO3 + HO2 --> 0.2 HNO3 + 0.8 OH + 0.8 NO2                                                   ', &
     '            2 NO3 --> 2 NO2                                                                         ', &
     '             H2O2 --> 2 OH                                                                          ', &
     '        H2O2 + OH --> HO2                                                                           ', &
     '         OH + HO2 --> H2O + M                                                                       ', &
     '         SO2 + OH --> H2SO4 + HO2                                                                   ', &
     '           OH + M --> HO2                                                                           ', &
     '        NO + C_O2 --> HCHO + NO2 + HO2                                                              ', &
     '       C_O2 + HO2 --> COOH                                                                          ', &
     '       NO3 + C_O2 --> HCHO + NO2 + HO2                                                              ', &
     '           2 C_O2 --> MEOH + HCHO                                                                   ', &
     '           2 C_O2 --> 2 HCHO + 2 HO2                                                                ', &
     '       NO + RO2_R --> NO2 + HO2                                                                     ', &
     '      RO2_R + HO2 --> ROOH                                                                          ', &
     '      NO3 + RO2_R --> NO2 + HO2                                                                     ', &
     '     C_O2 + RO2_R --> 0.25 MEOH + 0.75 HCHO + HO2                                                   ', &
     '          2 RO2_R --> HO2                                                                           ', &
     '        R2O2 + NO --> NO2                                                                           ', &
     '       R2O2 + HO2 --> HO2                                                                           ', &
     '       R2O2 + NO3 --> NO2                                                                           ', &
     '      R2O2 + C_O2 --> C_O2                                                                          ', &
     '     R2O2 + RO2_R --> RO2_R                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '           2 R2O2 --> 2 R2O2                                                                        ', &
     '       RO2_N + NO --> RNO3                                                                          ', &
     '      RO2_N + HO2 --> ROOH                                                                          ', &
     '     RO2_N + C_O2 --> 0.25 MEOH + 0.75 HCHO + 0.5 MEK + 0.5 PROD2 + HO2                             ', &
     '      RO2_N + NO3 --> MEK + NO2 + HO2                                                               ', &
     '    RO2_N + RO2_R --> 0.5 MEK + 0.5 PROD2 + HO2                                                     ', &
     '     R2O2 + RO2_N --> RO2_N                                                                         ', &
     '          2 RO2_N --> MEK + PROD2 + HO2                                                             ', &
     '     CCO_O2 + NO2 --> PAN                                                                           ', &
     '              PAN --> CCO_O2 + NO2                                                                  ', &
     '      CCO_O2 + NO --> NO2 + C_O2                                                                    ', &
     '     CCO_O2 + HO2 --> 0.25 CCO_OH + 0.75 CCO_OOH + 0.25 O3                                          ', &
     '     CCO_O2 + NO3 --> NO2 + C_O2                                                                    ', &
     '    CCO_O2 + C_O2 --> CCO_OH + HCHO                                                                 ', &
     '   CCO_O2 + RO2_R --> CCO_OH                                                                        ', &
     '    R2O2 + CCO_O2 --> CCO_O2                                                                        ', &
     '   CCO_O2 + RO2_N --> CCO_OH + PROD2                                                                ', &
     '         2 CCO_O2 --> 2 C_O2                                                                        ', &
     '     RCO_O2 + NO2 --> PAN2                                                                          ', &
     '             PAN2 --> RCO_O2 + NO2                                                                  ', &
     '      RCO_O2 + NO --> CCHO + NO2 + RO2_R                                                            ', &
     '     RCO_O2 + HO2 --> 0.25 RCO_OH + 0.75 RCO_OOH + 0.25 O3                                          ', &
     '     RCO_O2 + NO3 --> CCHO + NO2 + RO2_R                                                            ', &
     '    RCO_O2 + C_O2 --> RCO_OH + HCHO                                                                 ', &
     '   RCO_O2 + RO2_R --> RCO_OH                                                                        ', &
     '    R2O2 + RCO_O2 --> RCO_O2                                                                        ', &
     '   RO2_N + RCO_O2 --> RCO_OH + PROD2                                                                ', &
     '  CCO_O2 + RCO_O2 --> CCHO + C_O2 + RO2_R                                                           ', &
     '         2 RCO_O2 --> 2 CCHO + 2 RO2_R                                                              ', &
     '    NO2 + BZCO_O2 --> PBZN                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '             PBZN --> NO2 + BZCO_O2                                                                 ', &
     '     NO + BZCO_O2 --> BZ_O + R2O2 + NO2                                                             ', &
     '    HO2 + BZCO_O2 --> 0.25 RCO_OH + 0.75 RCO_OOH + 0.25 O3                                          ', &
     '    NO3 + BZCO_O2 --> BZ_O + R2O2 + NO2                                                             ', &
     '   C_O2 + BZCO_O2 --> RCO_OH + HCHO                                                                 ', &
     '  RO2_R + BZCO_O2 --> RCO_OH                                                                        ', &
     '   R2O2 + BZCO_O2 --> BZCO_O2                                                                       ', &
     '  RO2_N + BZCO_O2 --> RCO_OH + PROD2                                                                ', &
     ' CCO_O2 + BZCO_O2 --> BZ_O + R2O2 + C_O2                                                            ', &
     ' RCO_O2 + BZCO_O2 --> BZ_O + R2O2 + CCHO + RO2_R                                                    ', &
     '        2 BZCO_O2 --> 2 BZ_O + 2 R2O2                                                               ', &
     '    MA_RCO3 + NO2 --> MA_PAN                                                                        ', &
     '           MA_PAN --> MA_RCO3 + NO2                                                                 ', &
     '     MA_RCO3 + NO --> HCHO + CCO_O2 + NO2                                                           ', &
     '    MA_RCO3 + HO2 --> 0.25 RCO_OH + 0.75 RCO_OOH + 0.25 O3                                          ', &
     '    MA_RCO3 + NO3 --> HCHO + CCO_O2 + NO2                                                           ', &
     '   MA_RCO3 + C_O2 --> RCO_OH + HCHO                                                                 ', &
     '  MA_RCO3 + RO2_R --> RCO_OH                                                                        ', &
     '   R2O2 + MA_RCO3 --> MA_RCO3                                                                       ', &
     '  RO2_N + MA_RCO3 --> 2 RCO_OH                                                                      ', &
     ' CCO_O2 + MA_RCO3 --> HCHO + CCO_O2 + C_O2                                                          ', &
     ' MA_RCO3 + RCO_O2 --> CCHO + HCHO + CCO_O2 + RO2_R                                                  ', &
     'MA_RCO3 + BZCO_O2 --> BZ_O + R2O2 + HCHO + CCO_O2                                                   ', &
     '        2 MA_RCO3 --> 2 HCHO + 2 CCO_O2                                                             ', &
     '      TBU_O + NO2 --> RNO3                                                                          ', &
     '            TBU_O --> ACET + C_O2                                                                   ', &
     '       BZ_O + NO2 --> NPHE                                                                          ', &
     '       BZ_O + HO2 --> PHEN                                                                          ', &
     '             BZ_O --> PHEN                                                                          ', &
     '    BZNO2_O + NO2 --> 2 XN + 6 XC                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    BZNO2_O + HO2 --> NPHE                                                                          ', &
     '          BZNO2_O --> NPHE                                                                          ', &
     '             HCHO --> CO + 2 HO2                                                                    ', &
     '             HCHO --> CO                                                                            ', &
     '        HCHO + OH --> CO + HO2                                                                      ', &
     '       HCHO + HO2 --> HOCOO                                                                         ', &
     '            HOCOO --> HCHO + HO2                                                                    ', &
     '       HOCOO + NO --> HCOOH + NO2 + HO2                                                             ', &
     '       HCHO + NO3 --> CO + HNO3 + HO2                                                               ', &
     '        CCHO + OH --> CCO_O2                                                                        ', &
     '             CCHO --> CO + C_O2 + HO2                                                               ', &
     '       CCHO + NO3 --> HNO3 + CCO_O2                                                                 ', &
     '        RCHO + OH --> 0.034 CO + 0.034 CCHO + 0.001 RO2_N + 0.965 RCO_O2 + 0.034 RO2_R              ', &
     '             RCHO --> CO + CCHO + RO2_R + HO2                                                       ', &
     '       RCHO + NO3 --> HNO3 + RCO_O2                                                                 ', &
     '        ACET + OH --> R2O2 + HCHO + CCO_O2                                                          ', &
     '             ACET --> CCO_O2 + C_O2                                                                 ', &
     '         MEK + OH --> 0.616 R2O2 + 0.482 CCHO + 0.115 HCHO + 0.37 RCHO + 0.492 CCO_O2 + 0.042 RO2_N ', &
     '              MEK --> CCHO + CCO_O2 + RO2_R                                                         ', &
     '        MEOH + OH --> HCHO + HO2                                                                    ', &
     '        ETOH + OH --> 0.96 CCHO + 0.081 HCHO + 0.05 RO2_R + 0.95 HO2                                ', &
     '        COOH + OH --> 0.35 HCHO + 0.35 OH + 0.65 C_O2                                               ', &
     '             COOH --> HCHO + OH + HO2                                                               ', &
     '        ROOH + OH --> RCHO + 0.66 OH + 0.34 RO2_R                                                   ', &
     '             ROOH --> RCHO + OH + HO2                                                               ', &
     '              GLY --> 2 CO + 2 HO2                                                                  ', &
     '              GLY --> CO + HCHO                                                                     ', &
     '         GLY + OH --> 1.26 CO + 0.37 RCO_O2 + 0.63 HO2                                              ', &
     '        GLY + NO3 --> 1.26 CO + HNO3 + 0.37 RCO_O2 + 0.63 HO2                                       ', &
     '             MGLY --> CO + CCO_O2 + HO2                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '        MGLY + OH --> CO + CCO_O2                                                                   ', &
     '       MGLY + NO3 --> CO + HNO3 + CCO_O2                                                            ', &
     '             BACL --> 2 CCO_O2                                                                      ', &
     '        PHEN + OH --> 0.23 GLY + 0.24 BZ_O + 0.76 RO2_R                                             ', &
     '       PHEN + NO3 --> HNO3 + BZ_O                                                                   ', &
     '        CRES + OH --> 0.23 MGLY + 0.24 BZ_O + 0.76 RO2_R                                            ', &
     '       CRES + NO3 --> HNO3 + BZ_O                                                                   ', &
     '       NPHE + NO3 --> BZNO2_O + HNO3                                                                ', &
     '        BALD + OH --> BZCO_O2                                                                       ', &
     '             BALD --> 7 XC                                                                          ', &
     '       BALD + NO3 --> HNO3 + BZCO_O2                                                                ', &
     '    METHACRO + OH --> 0.084 MGLY + 0.416 CO + 0.084 HCHO + 0.416 MEK + 0.5 MA_RCO3 + 0.5 RO2_R      ', &
     '    METHACRO + O3 --> 0.333 HCOOH + 0.9 MGLY + 0.45 CO + 0.2 HCHO + 0.208 OH + 0.1 RCO_O2 + 0.1 RO2_', &
     '   METHACRO + NO3 --> 0.5 CO + 0.5 HNO3 + 0.5 MA_RCO3 + 0.5 RO2_R                                   ', &
     '   METHACRO + O3P --> RCHO                                                                          ', &
     '         METHACRO --> 0.67 CO + 0.67 HCHO + 0.67 CCO_O2 + 0.33 MA_RCO3 + 0.33 OH + 0.33 RO2_R + 0.34', &
     '         MVK + OH --> 0.3 MGLY + 0.675 R2O2 + 0.3 HCHO + 0.675 RCHO + 0.675 CCO_O2 + 0.025 RO2_N + 0', &
     '         MVK + O3 --> 0.351 HCOOH + 0.95 MGLY + 0.475 CO + 0.1 HCHO + 0.164 OH + 0.05 RCO_O2 + 0.05 ', &
     '        MVK + O3P --> 0.45 RCHO + 0.55 MEK                                                          ', &
     '              MVK --> 0.7 CO + 0.7 PROD2 + 0.3 MA_RCO3 + 0.3 C_O2                                   ', &
     '     ISOPROD + OH --> 0.174 MGLY + 0.336 CO + 0.15 GLY + 0.129 CCHO + 0.055 HCHO + 0.013 RCHO + 0.15', &
     '     ISOPROD + O3 --> 0.1 HCOOH + 0.372 RCO_OH + 0.742 MGLY + 0.498 CO + 0.023 GLY + 0.047 CCHO + 0.', &
     '    ISOPROD + NO3 --> 0.008 MGLY + 0.572 CO + 0.15 HNO3 + 0.227 HCHO + 0.572 RNO3 + 0.218 RCHO + 0.0', &
     '          ISOPROD --> 1.233 CO + 0.467 CCHO + 0.3 HCHO + 0.233 MEK + 0.467 CCO_O2 + 0.3 RCO_O2 + 1.2', &
     '       PROD2 + OH --> 0.084 CCHO + 0.213 HCHO + 0.558 RCHO + 0.115 MEK + 0.329 PROD2 + 0.029 CCO_O2 ', &
     '            PROD2 --> 0.515 R2O2 + 0.246 CCHO + 0.506 HCHO + 0.71 RCHO + 0.667 CCO_O2 + 0.04 RO2_N +', &
     '        RNO3 + OH --> 0.006 ACET + 0.596 R2O2 + 0.439 CCHO + 0.01 HCHO + 0.31 RNO3 + 0.213 RCHO + 0.', &
     '             RNO3 --> 0.02 ACET + 0.152 R2O2 + 0.431 CCHO + 0.134 HCHO + 0.147 RCHO + 0.243 MEK + 0.', &
     '        DCB1 + OH --> CO + RCHO + RO2_R                                                             ', &
     '        DCB1 + O3 --> 1.5 CO + GLY + 0.5 OH + 1.5 HO2                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '        DCB2 + OH --> R2O2 + RCHO + CCO_O2                                                          ', &
     '             DCB2 --> 0.5 MGLY + CO + 0.5 GLY + R2O2 + 0.5 CCO_O2 + RO2_R + 0.5 HO2                 ', &
     '        DCB3 + OH --> R2O2 + RCHO + CCO_O2                                                          ', &
     '             DCB3 --> 0.5 MGLY + CO + 0.5 GLY + R2O2 + 0.5 CCO_O2 + RO2_R + 0.5 HO2                 ', &
     '         CH4 + OH --> C_O2                                                                          ', &
     '      ETHENE + OH --> 0.195 CCHO + 1.61 HCHO + RO2_R                                                ', &
     '      ETHENE + O3 --> 0.37 HCOOH + 0.5 CO + HCHO + 0.12 OH + 0.12 HO2                               ', &
     '     ETHENE + NO3 --> RCHO + RO2_R                                                                  ', &
     '     ETHENE + O3P --> 0.491 CO + 0.009 GLY + 0.25 CCHO + 0.191 HCHO + 0.3 C_O2 + 0.2 RO2_R + 0.5 HO2', &
     '    ISOPRENE + OH --> 0.079 R2O2 + 0.23 METHACRO + 0.357 ISOPROD + 0.32 MVK + 0.624 HCHO + 0.093 RO2', &
     '    ISOPRENE + O3 --> 0.204 HCOOH + 0.15 RCO_OH + 0.275 CO + 0.126 R2O2 + 0.39 METHACRO + 0.16 MVK +', &
     '   ISOPRENE + NO3 --> 0.187 R2O2 + 0.936 ISOPROD + 0.064 RO2_N + 0.187 NO2 + 0.749 RO2_R            ', &
     '   ISOPRENE + O3P --> 0.24 R2O2 + 0.24 HCHO + 0.75 PROD2 + 0.01 RO2_N + 0.24 MA_RCO3 + 0.25 C_O2    ', &
     '        TERP + OH --> 0.5 R2O2 + 0.276 HCHO + 0.474 RCHO + 0.276 PROD2 + 0.25 RO2_N + 0.75 RO2_R    ', &
     '        TERP + O3 --> 0.103 HCOOH + 0.189 RCO_OH + 0.031 BACL + 0.157 CO + 0.13 ACET + 0.001 GLY + 0', &
     '       TERP + NO3 --> 0.75 R2O2 + 0.276 RNO3 + 0.474 RCHO + 0.25 RO2_N + 0.474 NO2 + 0.276 RO2_R    ', &
     '       TERP + O3P --> 0.147 RCHO + 0.853 PROD2                                                      ', &
     '        C2H6 + OH --> CCHO + RO2_R                                                                  ', &
     '        C3H8 + OH --> 0.704 ACET + 0.261 RCHO + 0.035 RO2_N + 0.965 RO2_R                           ', &
     '        C2H2 + OH --> 0.297 HCOOH + 0.393 CO + 0.607 GLY + 0.096 HCHO + 0.603 OH + 0.1 RO2_R + 0.297', &
     '        ALK3 + OH --> 0.236 TBU_O + 0.024 ACET + 0.559 R2O2 + 0.445 CCHO + 0.026 HCHO + 0.122 RCHO +', &
     '        ALK4 + OH --> 0.002 CO + 0.452 ACET + 0.936 R2O2 + 0.455 CCHO + 0.024 HCHO + 0.244 RCHO + 0.', &
     '        ALK5 + OH --> 0.072 ACET + 0.948 R2O2 + 0.099 CCHO + 0.026 HCHO + 0.204 RCHO + 0.089 MEK + 0', &
     '        ARO1 + OH --> 0.108 DCB2 + 0.051 DCB3 + 0.207 CRES + 0.491 DCB1 + 0.059 BALD + 0.017 PHEN + ', &
     '        ARO2 + OH --> 0.087 BACL + 0.099 DCB2 + 0.093 DCB3 + 0.187 CRES + 0.561 DCB1 + 0.05 BALD + 0', &
     '        OLE1 + OH --> 0.005 ACET + 0.205 R2O2 + 0.294 CCHO + 0.732 HCHO + 0.497 RCHO + 0.119 PROD2 +', &
     '        OLE1 + O3 --> 0.185 HCOOH + 0.05 CCO_OH + 0.119 RCO_OH + 0.345 CO + 0.001 ACET + 0.154 CCHO ', &
     '       OLE1 + NO3 --> 0.024 ACET + 0.488 R2O2 + 0.009 CCHO + 0.511 RNO3 + 0.037 RCHO + 0.176 RO2_N +', &
     '       OLE1 + O3P --> 0.45 RCHO + 0.437 MEK + 0.113 PROD2                                           ', &
     '        OLE2 + OH --> 0.061 BALD + 0.127 ACET + 0.001 R2O2 + 0.025 METHACRO + 0.025 ISOPROD + 0.732 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(15) :: EQN_NAMES_7 = (/ &
     '        OLE2 + O3 --> 0.073 HCOOH + 0.129 CCO_OH + 0.247 RCO_OH + 0.042 BALD + 0.265 CO + 0.045 ACET', &
     '       OLE2 + NO3 --> 0.015 BALD + 0.102 ACET + 0.711 R2O2 + 0.048 MVK + 0.507 CCHO + 0.079 HCHO + 0', &
     '       OLE2 + O3P --> 0.012 CO + 0.012 METHACRO + 0.069 RCHO + 0.659 MEK + 0.259 PROD2 + 0.001 RO2_N', &
     '        C2H2 + O3 --> 0.5 CO2 + 1.5 CO + 0.5 OH + 1.5 HO2                                           ', &
     '        C3H6 + OH --> 0.048 XC + 0.984 CCHO + 0.984 HCHO + 0.016 RO2_N + 0.984 RO2_R                ', &
     '        C3H6 + O3 --> 0.135 CO2 + 0.185 HCOOH + 0.17 CCO_OH + 0.07 XC + 0.51 CO + 0.5 CCHO + 0.5 HCH', &
     '       C3H6 + NO3 --> XN + 2.693 XC + 0.051 RO2_N + 0.949 RO2_R                                     ', &
     '       C3H6 + O3P --> 0.55 XC + 0.45 RCHO + 0.55 MEK                                                ', &
     '              SO2 --> H2SO4                                                                         ', &
     '              HO2 -->                                                                               ', &
     '              SO2 -->                                                                               ', &
     '            H2SO4 -->                                                                               ', &
     '             HNO3 -->                                                                               ', &
     '             H2O2 -->                                                                               ', &
     '              CO2 -->                                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(225) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7 /)

! INLINED global variables

! End INLINED global variables


END MODULE saprc99_Monitor
