























MODULE racm_soa_vbs_het_Parameters

  USE racm_soa_vbs_het_Precision
  PUBLIC
  SAVE



  INTEGER, PARAMETER :: NSPEC = 99 

  INTEGER, PARAMETER :: NVAR = 97 

  INTEGER, PARAMETER :: NVARACT = 91 

  INTEGER, PARAMETER :: NFIX = 2 

  INTEGER, PARAMETER :: NREACT = 280 

  INTEGER, PARAMETER :: NVARST = 1 

  INTEGER, PARAMETER :: NFIXST = 98 

  INTEGER, PARAMETER :: NONZERO = 1115 

  INTEGER, PARAMETER :: LU_NONZERO = 1307 

  INTEGER, PARAMETER :: CNVAR = 98 

  INTEGER, PARAMETER :: NLOOKAT = 0 

  INTEGER, PARAMETER :: NMONITOR = 0 

  INTEGER, PARAMETER :: NMASS = 1 

  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 




  INTEGER, PARAMETER :: ind_SULF = 1 
  INTEGER, PARAMETER :: ind_CO2 = 2 
  INTEGER, PARAMETER :: ind_ORA1 = 3 
  INTEGER, PARAMETER :: ind_ORA2 = 4 
  INTEGER, PARAMETER :: ind_CVASOA1 = 5 
  INTEGER, PARAMETER :: ind_CVASOA2 = 6 
  INTEGER, PARAMETER :: ind_CVASOA3 = 7 
  INTEGER, PARAMETER :: ind_CVASOA4 = 8 
  INTEGER, PARAMETER :: ind_CVBSOA1 = 9 
  INTEGER, PARAMETER :: ind_CVBSOA2 = 10 
  INTEGER, PARAMETER :: ind_CVBSOA3 = 11 
  INTEGER, PARAMETER :: ind_CVBSOA4 = 12 
  INTEGER, PARAMETER :: ind_CL2 = 13 
  INTEGER, PARAMETER :: ind_O1D = 14 
  INTEGER, PARAMETER :: ind_SO2 = 15 
  INTEGER, PARAMETER :: ind_ISHP = 16 
  INTEGER, PARAMETER :: ind_N2O5 = 17 
  INTEGER, PARAMETER :: ind_CLNO2 = 18 
  INTEGER, PARAMETER :: ind_HOCL = 19 
  INTEGER, PARAMETER :: ind_MAHP = 20 
  INTEGER, PARAMETER :: ind_UDD = 21 
  INTEGER, PARAMETER :: ind_NALD = 22 
  INTEGER, PARAMETER :: ind_TOL = 23 
  INTEGER, PARAMETER :: ind_XYL = 24 
  INTEGER, PARAMETER :: ind_OP1 = 25 
  INTEGER, PARAMETER :: ind_MPAN = 26 
  INTEGER, PARAMETER :: ind_HNO4 = 27 
  INTEGER, PARAMETER :: ind_HACE = 28 
  INTEGER, PARAMETER :: ind_HONO = 29 
  INTEGER, PARAMETER :: ind_O3P = 30 
  INTEGER, PARAMETER :: ind_PHO = 31 
  INTEGER, PARAMETER :: ind_CLO = 32 
  INTEGER, PARAMETER :: ind_H2O2 = 33 
  INTEGER, PARAMETER :: ind_HCL = 34 
  INTEGER, PARAMETER :: ind_CH4 = 35 
  INTEGER, PARAMETER :: ind_FMCL = 36 
  INTEGER, PARAMETER :: ind_HKET = 37 
  INTEGER, PARAMETER :: ind_ADDT = 38 
  INTEGER, PARAMETER :: ind_ADDX = 39 
  INTEGER, PARAMETER :: ind_ADDC = 40 
  INTEGER, PARAMETER :: ind_HC5 = 41 
  INTEGER, PARAMETER :: ind_ISON = 42 
  INTEGER, PARAMETER :: ind_SESQ = 43 
  INTEGER, PARAMETER :: ind_HNO3 = 44 
  INTEGER, PARAMETER :: ind_PAA = 45 
  INTEGER, PARAMETER :: ind_HC8 = 46 
  INTEGER, PARAMETER :: ind_API = 47 
  INTEGER, PARAMETER :: ind_PAN = 48 
  INTEGER, PARAMETER :: ind_HC3 = 49 
  INTEGER, PARAMETER :: ind_ETH = 50 
  INTEGER, PARAMETER :: ind_LIM = 51 
  INTEGER, PARAMETER :: ind_CO = 52 
  INTEGER, PARAMETER :: ind_ETE = 53 
  INTEGER, PARAMETER :: ind_MBO = 54 
  INTEGER, PARAMETER :: ind_DIEN = 55 
  INTEGER, PARAMETER :: ind_MACP = 56 
  INTEGER, PARAMETER :: ind_CSL = 57 
  INTEGER, PARAMETER :: ind_TPAN = 58 
  INTEGER, PARAMETER :: ind_ISO = 59 
  INTEGER, PARAMETER :: ind_GLY = 60 
  INTEGER, PARAMETER :: ind_OLTP = 61 
  INTEGER, PARAMETER :: ind_ETEP = 62 
  INTEGER, PARAMETER :: ind_LIMP = 63 
  INTEGER, PARAMETER :: ind_MACR = 64 
  INTEGER, PARAMETER :: ind_APIP = 65 
  INTEGER, PARAMETER :: ind_KET = 66 
  INTEGER, PARAMETER :: ind_ISOP = 67 
  INTEGER, PARAMETER :: ind_CSLP = 68 
  INTEGER, PARAMETER :: ind_MGLY = 69 
  INTEGER, PARAMETER :: ind_OLIP = 70 
  INTEGER, PARAMETER :: ind_TOLP = 71 
  INTEGER, PARAMETER :: ind_XYLP = 72 
  INTEGER, PARAMETER :: ind_HCHO = 73 
  INTEGER, PARAMETER :: ind_TCO3 = 74 
  INTEGER, PARAMETER :: ind_ONIT = 75 
  INTEGER, PARAMETER :: ind_HC5P = 76 
  INTEGER, PARAMETER :: ind_HC8P = 77 
  INTEGER, PARAMETER :: ind_ALD = 78 
  INTEGER, PARAMETER :: ind_DCB = 79 
  INTEGER, PARAMETER :: ind_XO2 = 80 
  INTEGER, PARAMETER :: ind_OLI = 81 
  INTEGER, PARAMETER :: ind_OLT = 82 
  INTEGER, PARAMETER :: ind_OLNN = 83 
  INTEGER, PARAMETER :: ind_OLND = 84 
  INTEGER, PARAMETER :: ind_O3 = 85 
  INTEGER, PARAMETER :: ind_HC3P = 86 
  INTEGER, PARAMETER :: ind_KETP = 87 
  INTEGER, PARAMETER :: ind_CL = 88 
  INTEGER, PARAMETER :: ind_HO2 = 89 
  INTEGER, PARAMETER :: ind_MO2 = 90 
  INTEGER, PARAMETER :: ind_HO = 91 
  INTEGER, PARAMETER :: ind_OP2 = 92 
  INTEGER, PARAMETER :: ind_ACO3 = 93 
  INTEGER, PARAMETER :: ind_NO = 94 
  INTEGER, PARAMETER :: ind_NO2 = 95 
  INTEGER, PARAMETER :: ind_NO3 = 96 
  INTEGER, PARAMETER :: ind_ETHP = 97 




  INTEGER, PARAMETER :: ind_H2O = 98 
  INTEGER, PARAMETER :: ind_M = 99 




  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE racm_soa_vbs_het_Parameters

