























MODULE cbmz_mosaic_Parameters

  USE cbmz_mosaic_Precision
  PUBLIC
  SAVE



  INTEGER, PARAMETER :: NSPEC = 68 

  INTEGER, PARAMETER :: NVAR = 66 

  INTEGER, PARAMETER :: NVARACT = 56 

  INTEGER, PARAMETER :: NFIX = 2 

  INTEGER, PARAMETER :: NREACT = 142 

  INTEGER, PARAMETER :: NVARST = 1 

  INTEGER, PARAMETER :: NFIXST = 67 

  INTEGER, PARAMETER :: NONZERO = 560 

  INTEGER, PARAMETER :: LU_NONZERO = 626 

  INTEGER, PARAMETER :: CNVAR = 67 

  INTEGER, PARAMETER :: NLOOKAT = 0 

  INTEGER, PARAMETER :: NMONITOR = 0 

  INTEGER, PARAMETER :: NMASS = 1 

  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 




  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_HCl = 2 
  INTEGER, PARAMETER :: ind_NH3 = 3 
  INTEGER, PARAMETER :: ind_HCOOH = 4 
  INTEGER, PARAMETER :: ind_RCOOH = 5 
  INTEGER, PARAMETER :: ind_ARO1 = 6 
  INTEGER, PARAMETER :: ind_ARO2 = 7 
  INTEGER, PARAMETER :: ind_ALK1 = 8 
  INTEGER, PARAMETER :: ind_OLE1 = 9 
  INTEGER, PARAMETER :: ind_API1 = 10 
  INTEGER, PARAMETER :: ind_API2 = 11 
  INTEGER, PARAMETER :: ind_LIM1 = 12 
  INTEGER, PARAMETER :: ind_LIM2 = 13 
  INTEGER, PARAMETER :: ind_SO2 = 14 
  INTEGER, PARAMETER :: ind_O1D = 15 
  INTEGER, PARAMETER :: ind_ANOL = 16 
  INTEGER, PARAMETER :: ind_H2O2 = 17 
  INTEGER, PARAMETER :: ind_PAN = 18 
  INTEGER, PARAMETER :: ind_TOL = 19 
  INTEGER, PARAMETER :: ind_N2O5 = 20 
  INTEGER, PARAMETER :: ind_XYL = 21 
  INTEGER, PARAMETER :: ind_CH4 = 22 
  INTEGER, PARAMETER :: ind_CRO = 23 
  INTEGER, PARAMETER :: ind_API = 24 
  INTEGER, PARAMETER :: ind_LIM = 25 
  INTEGER, PARAMETER :: ind_HNO4 = 26 
  INTEGER, PARAMETER :: ind_TO2 = 27 
  INTEGER, PARAMETER :: ind_C2H6 = 28 
  INTEGER, PARAMETER :: ind_XPAR = 29 
  INTEGER, PARAMETER :: ind_ETHOOH = 30 
  INTEGER, PARAMETER :: ind_HONO = 31 
  INTEGER, PARAMETER :: ind_CH3OOH = 32 
  INTEGER, PARAMETER :: ind_C2H4 = 33 
  INTEGER, PARAMETER :: ind_CH3OH = 34 
  INTEGER, PARAMETER :: ind_CRES = 35 
  INTEGER, PARAMETER :: ind_O3P = 36 
  INTEGER, PARAMETER :: ind_HNO3 = 37 
  INTEGER, PARAMETER :: ind_CO = 38 
  INTEGER, PARAMETER :: ind_ISOPN = 39 
  INTEGER, PARAMETER :: ind_PAR = 40 
  INTEGER, PARAMETER :: ind_OPEN = 41 
  INTEGER, PARAMETER :: ind_ISOPP = 42 
  INTEGER, PARAMETER :: ind_ISOPO2 = 43 
  INTEGER, PARAMETER :: ind_OLET = 44 
  INTEGER, PARAMETER :: ind_ISOP = 45 
  INTEGER, PARAMETER :: ind_HCHO = 46 
  INTEGER, PARAMETER :: ind_XO2 = 47 
  INTEGER, PARAMETER :: ind_AONE = 48 
  INTEGER, PARAMETER :: ind_OLEI = 49 
  INTEGER, PARAMETER :: ind_MGLY = 50 
  INTEGER, PARAMETER :: ind_ETHP = 51 
  INTEGER, PARAMETER :: ind_NAP = 52 
  INTEGER, PARAMETER :: ind_ALD2 = 53 
  INTEGER, PARAMETER :: ind_CH3O2 = 54 
  INTEGER, PARAMETER :: ind_ISOPRD = 55 
  INTEGER, PARAMETER :: ind_ROOH = 56 
  INTEGER, PARAMETER :: ind_ANO2 = 57 
  INTEGER, PARAMETER :: ind_RO2 = 58 
  INTEGER, PARAMETER :: ind_ONIT = 59 
  INTEGER, PARAMETER :: ind_NO3 = 60 
  INTEGER, PARAMETER :: ind_NO = 61 
  INTEGER, PARAMETER :: ind_NO2 = 62 
  INTEGER, PARAMETER :: ind_OH = 63 
  INTEGER, PARAMETER :: ind_O3 = 64 
  INTEGER, PARAMETER :: ind_HO2 = 65 
  INTEGER, PARAMETER :: ind_C2O3 = 66 




  INTEGER, PARAMETER :: ind_H2O = 67 
  INTEGER, PARAMETER :: ind_M = 68 




  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE cbmz_mosaic_Parameters

