























MODULE mozart_mosaic_4bin_aq_Parameters

  USE mozart_mosaic_4bin_aq_Precision
  PUBLIC
  SAVE



  INTEGER, PARAMETER :: NSPEC = 142 

  INTEGER, PARAMETER :: NVAR = 140 

  INTEGER, PARAMETER :: NVARACT = 135 

  INTEGER, PARAMETER :: NFIX = 2 

  INTEGER, PARAMETER :: NREACT = 346 

  INTEGER, PARAMETER :: NVARST = 1 

  INTEGER, PARAMETER :: NFIXST = 141 

  INTEGER, PARAMETER :: NONZERO = 1353 

  INTEGER, PARAMETER :: LU_NONZERO = 1515 

  INTEGER, PARAMETER :: CNVAR = 141 

  INTEGER, PARAMETER :: NLOOKAT = 0 

  INTEGER, PARAMETER :: NMONITOR = 0 

  INTEGER, PARAMETER :: NMASS = 1 

  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 




  INTEGER, PARAMETER :: ind_HONO = 1 
  INTEGER, PARAMETER :: ind_SO4 = 2 
  INTEGER, PARAMETER :: ind_NUME = 3 
  INTEGER, PARAMETER :: ind_DEN = 4 
  INTEGER, PARAMETER :: ind_CVASOAX = 5 
  INTEGER, PARAMETER :: ind_CVASOA1 = 6 
  INTEGER, PARAMETER :: ind_CVASOA2 = 7 
  INTEGER, PARAMETER :: ind_CVASOA3 = 8 
  INTEGER, PARAMETER :: ind_CVASOA4 = 9 
  INTEGER, PARAMETER :: ind_CVBSOAX = 10 
  INTEGER, PARAMETER :: ind_CVBSOA1 = 11 
  INTEGER, PARAMETER :: ind_CVBSOA2 = 12 
  INTEGER, PARAMETER :: ind_CVBSOA3 = 13 
  INTEGER, PARAMETER :: ind_CVBSOA4 = 14 
  INTEGER, PARAMETER :: ind_NH3 = 15 
  INTEGER, PARAMETER :: ind_C2H6 = 16 
  INTEGER, PARAMETER :: ind_C3H8 = 17 
  INTEGER, PARAMETER :: ind_BIGENE = 18 
  INTEGER, PARAMETER :: ind_N2O = 19 
  INTEGER, PARAMETER :: ind_SO2 = 20 
  INTEGER, PARAMETER :: ind_PBZNIT = 21 
  INTEGER, PARAMETER :: ind_H2O2 = 22 
  INTEGER, PARAMETER :: ind_C2H2 = 23 
  INTEGER, PARAMETER :: ind_BENZENE = 24 
  INTEGER, PARAMETER :: ind_BEPOMUC = 25 
  INTEGER, PARAMETER :: ind_PHENOL = 26 
  INTEGER, PARAMETER :: ind_TOLUENE = 27 
  INTEGER, PARAMETER :: ind_CRESOL = 28 
  INTEGER, PARAMETER :: ind_XOOH = 29 
  INTEGER, PARAMETER :: ind_EO = 30 
  INTEGER, PARAMETER :: ind_PHENOOH = 31 
  INTEGER, PARAMETER :: ind_C6H5OOH = 32 
  INTEGER, PARAMETER :: ind_BENZOOH = 33 
  INTEGER, PARAMETER :: ind_BIGALD2 = 34 
  INTEGER, PARAMETER :: ind_TEPOMUC = 35 
  INTEGER, PARAMETER :: ind_BZOOH = 36 
  INTEGER, PARAMETER :: ind_BZALD = 37 
  INTEGER, PARAMETER :: ind_XYLOLOOH = 38 
  INTEGER, PARAMETER :: ind_XYLENOOH = 39 
  INTEGER, PARAMETER :: ind_N2O5 = 40 
  INTEGER, PARAMETER :: ind_XYLENES = 41 
  INTEGER, PARAMETER :: ind_XYLOL = 42 
  INTEGER, PARAMETER :: ind_DMS = 43 
  INTEGER, PARAMETER :: ind_BIGALD4 = 44 
  INTEGER, PARAMETER :: ind_C2H5OH = 45 
  INTEGER, PARAMETER :: ind_BIGALD3 = 46 
  INTEGER, PARAMETER :: ind_BIGALD1 = 47 
  INTEGER, PARAMETER :: ind_C2H5OOH = 48 
  INTEGER, PARAMETER :: ind_C3H7OOH = 49 
  INTEGER, PARAMETER :: ind_ROOH = 50 
  INTEGER, PARAMETER :: ind_ENEO2 = 51 
  INTEGER, PARAMETER :: ind_MEKOOH = 52 
  INTEGER, PARAMETER :: ind_CH3OOH = 53 
  INTEGER, PARAMETER :: ind_MACROOH = 54 
  INTEGER, PARAMETER :: ind_H2 = 55 
  INTEGER, PARAMETER :: ind_HO2NO2 = 56 
  INTEGER, PARAMETER :: ind_HYDRALD = 57 
  INTEGER, PARAMETER :: ind_BIGALK = 58 
  INTEGER, PARAMETER :: ind_C2H4 = 59 
  INTEGER, PARAMETER :: ind_EO2 = 60 
  INTEGER, PARAMETER :: ind_TOLOOH = 61 
  INTEGER, PARAMETER :: ind_PHENO2 = 62 
  INTEGER, PARAMETER :: ind_PHENO = 63 
  INTEGER, PARAMETER :: ind_BZOO = 64 
  INTEGER, PARAMETER :: ind_HOCH2OO = 65 
  INTEGER, PARAMETER :: ind_MEK = 66 
  INTEGER, PARAMETER :: ind_CH3COOH = 67 
  INTEGER, PARAMETER :: ind_CH3COOOH = 68 
  INTEGER, PARAMETER :: ind_TERPOOH = 69 
  INTEGER, PARAMETER :: ind_BENZO2 = 70 
  INTEGER, PARAMETER :: ind_ONIT = 71 
  INTEGER, PARAMETER :: ind_POOH = 72 
  INTEGER, PARAMETER :: ind_PAN = 73 
  INTEGER, PARAMETER :: ind_XYLOLO2 = 74 
  INTEGER, PARAMETER :: ind_HNO3 = 75 
  INTEGER, PARAMETER :: ind_HMPROPO2 = 76 
  INTEGER, PARAMETER :: ind_CH4 = 77 
  INTEGER, PARAMETER :: ind_ACBZO2 = 78 
  INTEGER, PARAMETER :: ind_MBOOOH = 79 
  INTEGER, PARAMETER :: ind_ISOPOOH = 80 
  INTEGER, PARAMETER :: ind_MPAN = 81 
  INTEGER, PARAMETER :: ind_HCOOH = 82 
  INTEGER, PARAMETER :: ind_TERP2OOH = 83 
  INTEGER, PARAMETER :: ind_O1D_CB4 = 84 
  INTEGER, PARAMETER :: ind_C6H5O2 = 85 
  INTEGER, PARAMETER :: ind_BPIN = 86 
  INTEGER, PARAMETER :: ind_APIN = 87 
  INTEGER, PARAMETER :: ind_ALKOOH = 88 
  INTEGER, PARAMETER :: ind_MEKO2 = 89 
  INTEGER, PARAMETER :: ind_PO2 = 90 
  INTEGER, PARAMETER :: ind_MALO2 = 91 
  INTEGER, PARAMETER :: ind_MBO = 92 
  INTEGER, PARAMETER :: ind_TOLO2 = 93 
  INTEGER, PARAMETER :: ind_XYLENO2 = 94 
  INTEGER, PARAMETER :: ind_DICARBO2 = 95 
  INTEGER, PARAMETER :: ind_O = 96 
  INTEGER, PARAMETER :: ind_C3H7O2 = 97 
  INTEGER, PARAMETER :: ind_MDIALO2 = 98 
  INTEGER, PARAMETER :: ind_GLYOXAL = 99 
  INTEGER, PARAMETER :: ind_CH3OH = 100 
  INTEGER, PARAMETER :: ind_BIGALD = 101 
  INTEGER, PARAMETER :: ind_C2H5O2 = 102 
  INTEGER, PARAMETER :: ind_ISOPNO3 = 103 
  INTEGER, PARAMETER :: ind_LIMON = 104 
  INTEGER, PARAMETER :: ind_MBONO3O2 = 105 
  INTEGER, PARAMETER :: ind_HMPROP = 106 
  INTEGER, PARAMETER :: ind_MYRC = 107 
  INTEGER, PARAMETER :: ind_ISOP = 108 
  INTEGER, PARAMETER :: ind_BCARY = 109 
  INTEGER, PARAMETER :: ind_CH3COCH3 = 110 
  INTEGER, PARAMETER :: ind_CO = 111 
  INTEGER, PARAMETER :: ind_GLYALD = 112 
  INTEGER, PARAMETER :: ind_C3H6 = 113 
  INTEGER, PARAMETER :: ind_CH3CHO = 114 
  INTEGER, PARAMETER :: ind_TERPROD2 = 115 
  INTEGER, PARAMETER :: ind_MBOO2 = 116 
  INTEGER, PARAMETER :: ind_ALKO2 = 117 
  INTEGER, PARAMETER :: ind_TERP2O2 = 118 
  INTEGER, PARAMETER :: ind_TERPO2 = 119 
  INTEGER, PARAMETER :: ind_ONITR = 120 
  INTEGER, PARAMETER :: ind_RO2 = 121 
  INTEGER, PARAMETER :: ind_NTERPO2 = 122 
  INTEGER, PARAMETER :: ind_MACR = 123 
  INTEGER, PARAMETER :: ind_TERPROD1 = 124 
  INTEGER, PARAMETER :: ind_HYAC = 125 
  INTEGER, PARAMETER :: ind_CH3COCHO = 126 
  INTEGER, PARAMETER :: ind_XO2 = 127 
  INTEGER, PARAMETER :: ind_MVK = 128 
  INTEGER, PARAMETER :: ind_MACRO2 = 129 
  INTEGER, PARAMETER :: ind_CH2O = 130 
  INTEGER, PARAMETER :: ind_ISOPO2 = 131 
  INTEGER, PARAMETER :: ind_MCO3 = 132 
  INTEGER, PARAMETER :: ind_NO3 = 133 
  INTEGER, PARAMETER :: ind_OH = 134 
  INTEGER, PARAMETER :: ind_HO2 = 135 
  INTEGER, PARAMETER :: ind_O3 = 136 
  INTEGER, PARAMETER :: ind_CH3CO3 = 137 
  INTEGER, PARAMETER :: ind_NO2 = 138 
  INTEGER, PARAMETER :: ind_NO = 139 
  INTEGER, PARAMETER :: ind_CH3O2 = 140 




  INTEGER, PARAMETER :: ind_H2O = 141 
  INTEGER, PARAMETER :: ind_M = 142 




  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE mozart_mosaic_4bin_aq_Parameters

