























MODULE saprc99_mosaic_4bin_vbs2_Parameters

  USE saprc99_mosaic_4bin_vbs2_Precision
  PUBLIC
  SAVE



  INTEGER, PARAMETER :: NSPEC = 102 

  INTEGER, PARAMETER :: NVAR = 100 

  INTEGER, PARAMETER :: NVARACT = 85 

  INTEGER, PARAMETER :: NFIX = 2 

  INTEGER, PARAMETER :: NREACT = 250 

  INTEGER, PARAMETER :: NVARST = 1 

  INTEGER, PARAMETER :: NFIXST = 101 

  INTEGER, PARAMETER :: NONZERO = 1038 

  INTEGER, PARAMETER :: LU_NONZERO = 1123 

  INTEGER, PARAMETER :: CNVAR = 101 

  INTEGER, PARAMETER :: NLOOKAT = 0 

  INTEGER, PARAMETER :: NMONITOR = 0 

  INTEGER, PARAMETER :: NMASS = 1 

  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 




  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_CO2 = 2 
  INTEGER, PARAMETER :: ind_PCG1_B_C = 3 
  INTEGER, PARAMETER :: ind_PCG1_B_O = 4 
  INTEGER, PARAMETER :: ind_PCG1_F_C = 5 
  INTEGER, PARAMETER :: ind_PCG1_F_O = 6 
  INTEGER, PARAMETER :: ind_HCOOH = 7 
  INTEGER, PARAMETER :: ind_CCO_OH = 8 
  INTEGER, PARAMETER :: ind_RCO_OH = 9 
  INTEGER, PARAMETER :: ind_CCO_OOH = 10 
  INTEGER, PARAMETER :: ind_RCO_OOH = 11 
  INTEGER, PARAMETER :: ind_XN = 12 
  INTEGER, PARAMETER :: ind_XC = 13 
  INTEGER, PARAMETER :: ind_NUME = 14 
  INTEGER, PARAMETER :: ind_DEN = 15 
  INTEGER, PARAMETER :: ind_ANT1_c = 16 
  INTEGER, PARAMETER :: ind_ANT1_o = 17 
  INTEGER, PARAMETER :: ind_BIOG1_c = 18 
  INTEGER, PARAMETER :: ind_BIOG1_o = 19 
  INTEGER, PARAMETER :: ind_PSD1 = 20 
  INTEGER, PARAMETER :: ind_PSD2 = 21 
  INTEGER, PARAMETER :: ind_OPCG1_B_O = 22 
  INTEGER, PARAMETER :: ind_PCG2_B_O = 23 
  INTEGER, PARAMETER :: ind_OPCG1_F_O = 24 
  INTEGER, PARAMETER :: ind_PCG2_F_O = 25 
  INTEGER, PARAMETER :: ind_O1D = 26 
  INTEGER, PARAMETER :: ind_PCG2_B_C = 27 
  INTEGER, PARAMETER :: ind_OPCG1_B_C = 28 
  INTEGER, PARAMETER :: ind_PCG2_F_C = 29 
  INTEGER, PARAMETER :: ind_OPCG1_F_C = 30 
  INTEGER, PARAMETER :: ind_CH4 = 31 
  INTEGER, PARAMETER :: ind_SO2 = 32 
  INTEGER, PARAMETER :: ind_C2H6 = 33 
  INTEGER, PARAMETER :: ind_PAN = 34 
  INTEGER, PARAMETER :: ind_PAN2 = 35 
  INTEGER, PARAMETER :: ind_PBZN = 36 
  INTEGER, PARAMETER :: ind_MA_PAN = 37 
  INTEGER, PARAMETER :: ind_H2O2 = 38 
  INTEGER, PARAMETER :: ind_C3H8 = 39 
  INTEGER, PARAMETER :: ind_BACL = 40 
  INTEGER, PARAMETER :: ind_ETOH = 41 
  INTEGER, PARAMETER :: ind_N2O5 = 42 
  INTEGER, PARAMETER :: ind_HONO = 43 
  INTEGER, PARAMETER :: ind_ALK3 = 44 
  INTEGER, PARAMETER :: ind_TBU_O = 45 
  INTEGER, PARAMETER :: ind_ALK5 = 46 
  INTEGER, PARAMETER :: ind_COOH = 47 
  INTEGER, PARAMETER :: ind_HOCOO = 48 
  INTEGER, PARAMETER :: ind_BZNO2_O = 49 
  INTEGER, PARAMETER :: ind_ARO2 = 50 
  INTEGER, PARAMETER :: ind_HNO4 = 51 
  INTEGER, PARAMETER :: ind_MEOH = 52 
  INTEGER, PARAMETER :: ind_ALK4 = 53 
  INTEGER, PARAMETER :: ind_ARO1 = 54 
  INTEGER, PARAMETER :: ind_DCB2 = 55 
  INTEGER, PARAMETER :: ind_DCB3 = 56 
  INTEGER, PARAMETER :: ind_CRES = 57 
  INTEGER, PARAMETER :: ind_DCB1 = 58 
  INTEGER, PARAMETER :: ind_C2H2 = 59 
  INTEGER, PARAMETER :: ind_ROOH = 60 
  INTEGER, PARAMETER :: ind_NPHE = 61 
  INTEGER, PARAMETER :: ind_BALD = 62 
  INTEGER, PARAMETER :: ind_PHEN = 63 
  INTEGER, PARAMETER :: ind_MGLY = 64 
  INTEGER, PARAMETER :: ind_CO = 65 
  INTEGER, PARAMETER :: ind_HNO3 = 66 
  INTEGER, PARAMETER :: ind_ETHENE = 67 
  INTEGER, PARAMETER :: ind_ACET = 68 
  INTEGER, PARAMETER :: ind_C3H6 = 69 
  INTEGER, PARAMETER :: ind_BZ_O = 70 
  INTEGER, PARAMETER :: ind_ISOPRENE = 71 
  INTEGER, PARAMETER :: ind_OLE1 = 72 
  INTEGER, PARAMETER :: ind_R2O2 = 73 
  INTEGER, PARAMETER :: ind_METHACRO = 74 
  INTEGER, PARAMETER :: ind_SESQ = 75 
  INTEGER, PARAMETER :: ind_TERP = 76 
  INTEGER, PARAMETER :: ind_GLY = 77 
  INTEGER, PARAMETER :: ind_ISOPROD = 78 
  INTEGER, PARAMETER :: ind_CCHO = 79 
  INTEGER, PARAMETER :: ind_OLE2 = 80 
  INTEGER, PARAMETER :: ind_MVK = 81 
  INTEGER, PARAMETER :: ind_HCHO = 82 
  INTEGER, PARAMETER :: ind_RNO3 = 83 
  INTEGER, PARAMETER :: ind_O3P = 84 
  INTEGER, PARAMETER :: ind_RCHO = 85 
  INTEGER, PARAMETER :: ind_MEK = 86 
  INTEGER, PARAMETER :: ind_PROD2 = 87 
  INTEGER, PARAMETER :: ind_O3 = 88 
  INTEGER, PARAMETER :: ind_CCO_O2 = 89 
  INTEGER, PARAMETER :: ind_RO2_R = 90 
  INTEGER, PARAMETER :: ind_RO2_N = 91 
  INTEGER, PARAMETER :: ind_NO2 = 92 
  INTEGER, PARAMETER :: ind_NO3 = 93 
  INTEGER, PARAMETER :: ind_C_O2 = 94 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 95 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 96 
  INTEGER, PARAMETER :: ind_HO2 = 97 
  INTEGER, PARAMETER :: ind_OH = 98 
  INTEGER, PARAMETER :: ind_RCO_O2 = 99 
  INTEGER, PARAMETER :: ind_NO = 100 




  INTEGER, PARAMETER :: ind_H2O = 101 
  INTEGER, PARAMETER :: ind_M = 102 




  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE saprc99_mosaic_4bin_vbs2_Parameters

