
MODULE saprc99_mosaic_4bin_vbs2_Precision






  INTEGER, PARAMETER :: sp = SELECTED_REAL_KIND(6,30)

  INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(14,300)

  INTEGER, PARAMETER :: qp = SELECTED_REAL_KIND(18,400)

END MODULE saprc99_mosaic_4bin_vbs2_Precision


