! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mozart_mosaic_4bin_Monitor.f90
! Time                 : Thu Apr 14 13:13:48 2022
! Working directory    : /network/rit/lab/lulab/chinan/WRF/WRFV4.0/WRF/chem/KPP/mechanisms/mozart_mosaic_4bin
! Equation file        : mozart_mosaic_4bin.kpp
! Output root filename : mozart_mosaic_4bin
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mozart_mosaic_4bin_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'HONO        ','SO4         ','NUME        ', &
     'DEN         ','BIOG1_c     ','BIOG1_o     ', &
     'SMPA        ','VOCA        ','SMPBB       ', &
     'VOCBB       ','NH3         ','C2H6        ', &
     'C3H8        ','BIGENE      ','N2O         ', &
     'SO2         ','PBZNIT      ','H2O2        ', &
     'C2H2        ','BENZENE     ','BEPOMUC     ', &
     'PHENOL      ','EO          ','TOLUENE     ', &
     'CRESOL      ','XOOH        ','PHENOOH     ', &
     'C6H5OOH     ','BENZOOH     ','BIGALD2     ', &
     'TEPOMUC     ','BZOOH       ','BZALD       ', &
     'XYLOLOOH    ','XYLENOOH    ','N2O5        ', &
     'XYLENES     ','XYLOL       ','DMS         ', &
     'BIGALD4     ','C2H5OH      ','BIGALD3     ', &
     'BIGALD1     ','H2          ','C2H5OOH     ', &
     'C3H7OOH     ','ROOH        ','ENEO2       ', &
     'MEKOOH      ','CH3OOH      ','MACROOH     ', &
     'HO2NO2      ','HYDRALD     ','BIGALK      ', &
     'C2H4        ','HOCH2OO     ','TOLOOH      ', &
     'PHENO2      ','PHENO       ','EO2         ', &
     'BZOO        ','MEK         ','CH3COOH     ', &
     'CH3COOOH    ','TERPOOH     ','BENZO2      ', &
     'ONIT        ','PAN         ','XYLOLO2     ', &
     'POOH        ','HNO3        ','CH4         ', &
     'HMPROPO2    ','ACBZO2      ','ISOPOOH     ', &
     'MBOOOH      ','MPAN        ','HCOOH       ', &
     'TERP2OOH    ','O1D_CB4     ','C6H5O2      ', &
     'APIN        ','BPIN        ','ALKOOH      ', &
     'MEKO2       ','PO2         ','MALO2       ', &
     'TOLO2       ','MBO         ','XYLENO2     ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(48) :: SPC_NAMES_1 = (/ &
     'DICARBO2    ','O           ','C3H7O2      ', &
     'MDIALO2     ','CH3OH       ','GLYOXAL     ', &
     'C2H5O2      ','BIGALD      ','ISOPNO3     ', &
     'BCARY       ','LIMON       ','MBONO3O2    ', &
     'HMPROP      ','MYRC        ','CH3COCH3    ', &
     'ISOP        ','CO          ','GLYALD      ', &
     'C3H6        ','TERPROD1    ','MBOO2       ', &
     'CH3CHO      ','ALKO2       ','TERPROD2    ', &
     'MACR        ','ONITR       ','CH3COCHO    ', &
     'TERPO2      ','NTERPO2     ','TERP2O2     ', &
     'RO2         ','HYAC        ','XO2         ', &
     'MVK         ','MACRO2      ','CH2O        ', &
     'ISOPO2      ','CH3CO3      ','CH3O2       ', &
     'MCO3        ','HO2         ','O3          ', &
     'NO          ','NO2         ','NO3         ', &
     'OH          ','H2O         ','M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(138) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              M --> 2 O                                                                             ', &
     '             O3 --> O1D_CB4                                                                         ', &
     '             O3 --> O                                                                               ', &
     '            N2O --> O1D_CB4                                                                         ', &
     '            NO2 --> O + NO                                                                          ', &
     '           N2O5 --> NO2 + NO3                                                                       ', &
     '           HNO3 --> NO2 + OH                                                                        ', &
     '            NO3 --> 0.89 O3 + 0.11 NO + 0.89 NO2                                                    ', &
     '         HO2NO2 --> 0.66 HO2 + 0.66 NO2 + 0.33 NO3 + 0.33 OH                                        ', &
     '         CH3OOH --> CH2O + HO2 + OH                                                                 ', &
     '           CH2O --> CO + 2 HO2                                                                      ', &
     '           CH2O --> H2 + CO                                                                         ', &
     '           H2O2 --> 2 OH                                                                            ', &
     '         CH3CHO --> CO + CH3O2 + HO2                                                                ', &
     '           POOH --> CH3CHO + CH2O + HO2 + OH                                                        ', &
     '       CH3COOOH --> CH3O2 + OH                                                                      ', &
     '            PAN --> 0.6 CH3CO3 + 0.4 CH3O2 + 0.6 NO2 + 0.4 NO3                                      ', &
     '           MPAN --> MCO3 + NO2                                                                      ', &
     '           MACR --> 0.67 CO + 0.67 CH2O + 0.67 CH3CO3 + 0.33 MCO3 + 0.67 HO2 + 0.33 OH              ', &
     '            MVK --> 0.7 CO + 0.7 C3H6 + 0.3 CH3CO3 + 0.3 CH3O2                                      ', &
     '        C2H5OOH --> CH3CHO + HO2 + OH                                                               ', &
     '        C3H7OOH --> 0.82 CH3COCH3 + HO2 + OH                                                        ', &
     '           ROOH --> CH2O + CH3CO3 + OH                                                              ', &
     '       CH3COCH3 --> CH3CO3 + CH3O2                                                                  ', &
     '       CH3COCHO --> CO + CH3CO3 + HO2                                                               ', &
     '           XOOH --> OH                                                                              ', &
     '          ONITR --> CO + CH2O + HO2 + NO2                                                           ', &
     '        ISOPOOH --> 0.288 MACR + 0.402 MVK + 0.69 CH2O + HO2                                        ', &
     '           HYAC --> CH2O + CH3CO3 + HO2                                                             ', &
     '         GLYALD --> CO + CH2O + 2 HO2                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '            MEK --> C2H5O2 + CH3CO3                                                                 ', &
     '         BIGALD --> 0.13 GLYOXAL + 0.45 CO + 0.18 CH3COCHO + 0.13 CH3CO3 + 0.56 HO2                 ', &
     '        GLYOXAL --> 2 CO + 2 HO2                                                                    ', &
     '         ALKOOH --> 0.8 MEK + 0.25 CH3COCH3 + 0.4 CH3CHO + 0.1 CH2O + 0.9 HO2 + OH                  ', &
     '         MEKOOH --> CH3CHO + CH3CO3 + OH                                                            ', &
     '         TOLOOH --> 0.45 GLYOXAL + 0.9 BIGALD + 0.45 CH3COCHO + OH                                  ', &
     '        BIGALD1 --> 0.6 MALO2 + HO2                                                                 ', &
     '        BEPOMUC --> BIGALD1 + 1.5 CO + 1.5 HO2                                                      ', &
     '        TEPOMUC --> 1.5 CO + 0.5 CH3CO3 + HO2                                                       ', &
     '        BIGALD2 --> 0.6 DICARBO2 + 0.6 HO2                                                          ', &
     '        BIGALD3 --> 0.6 MDIALO2 + 0.6 CO + 0.6 HO2                                                  ', &
     '        BIGALD4 --> CO + CH3COCHO + CH3CO3 + HO2                                                    ', &
     '         MBOOOH --> 0.33 HMPROP + 0.67 CH3COCH3 + 0.67 GLYALD + 0.33 CH2O + HO2 + OH                ', &
     '         HMPROP --> CH3COCH3 + CO + 2 HO2                                                           ', &
     '       TERPROD1 --> CO + TERPROD2 + HO2                                                             ', &
     '       TERPROD2 --> 0.5 CH3COCH3 + 1.7 CO + 0.15 RO2 + 0.68 CH2O + 0.65 CH3CO3 + 1.2 HO2            ', &
     '        TERPOOH --> 0.05 CH3COCH3 + TERPROD1 + 0.4 CH2O + HO2 + OH                                  ', &
     '       TERP2OOH --> 0.3 CH3COCH3 + 0.25 CO + 0.25 GLYALD + TERPROD2 + 0.375 CH2O + HO2 + OH         ', &
     '           HONO --> NO + OH                                                                         ', &
     '          O + M --> O3                                                                              ', &
     '         O + O3 --> M                                                                               ', &
     '    O1D_CB4 + M --> O                                                                               ', &
     '  O1D_CB4 + H2O --> 2 OH                                                                            ', &
     '   H2 + O1D_CB4 --> HO2 + OH                                                                        ', &
     '        H2 + OH --> HO2 + H2O                                                                       ', &
     '         O + OH --> HO2                                                                             ', &
     '        O + HO2 --> OH                                                                              ', &
     '        O3 + OH --> HO2                                                                             ', &
     '       HO2 + O3 --> OH                                                                              ', &
     '    2 HO2 + H2O --> H2O2                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '      H2O2 + OH --> HO2 + H2O                                                                       ', &
     '       HO2 + OH --> H2O                                                                             ', &
     '           2 OH --> O + H2O                                                                         ', &
     '           2 OH --> H2O2                                                                            ', &
     '  N2O + O1D_CB4 --> 2 NO                                                                            ', &
     '  N2O + O1D_CB4 --> M                                                                               ', &
     '       HO2 + NO --> NO2 + OH                                                                        ', &
     '        O3 + NO --> NO2                                                                             ', &
     '        O + NO2 --> NO                                                                              ', &
     '       O3 + NO2 --> NO3                                                                             ', &
     '      HO2 + NO3 --> NO2 + OH                                                                        ', &
     '      NO2 + NO3 --> N2O5                                                                            ', &
     '           N2O5 --> NO2 + NO3                                                                       ', &
     '       NO2 + OH --> HNO3                                                                            ', &
     '      HNO3 + OH --> NO3 + H2O                                                                       ', &
     '       NO + NO3 --> 2 NO2                                                                           ', &
     '      HO2 + NO2 --> HO2NO2                                                                          ', &
     '    HO2NO2 + OH --> NO2 + H2O                                                                       ', &
     '         HO2NO2 --> HO2 + NO2                                                                       ', &
     '       N2O5 + M --> 2 HNO3                                                                          ', &
     '            NO3 --> HNO3                                                                            ', &
     '            NO2 --> 0.5 HNO3 + 0.5 NO + 0.5 OH                                                      ', &
     '       CH4 + OH --> CH3O2 + H2O                                                                     ', &
     '  CH4 + O1D_CB4 --> 0.05 H2 + 0.25 CH2O + 0.75 CH3O2 + 0.4 HO2 + 0.75 OH                            ', &
     '     CH3O2 + NO --> NUME + CH2O + HO2 + NO2                                                         ', &
     '        2 CH3O2 --> DEN + 2 CH2O + 2 HO2                                                            ', &
     '        2 CH3O2 --> DEN + CH3OH + CH2O                                                              ', &
     '    CH3O2 + HO2 --> DEN + CH3OOH                                                                    ', &
     '    CH3OOH + OH --> 0.3 CH2O + 0.7 CH3O2 + 0.3 OH + H2O                                             ', &
     '     CH2O + NO3 --> HNO3 + CO + HO2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '      CH2O + OH --> CO + HO2 + H2O                                                                  ', &
     '        CO + OH --> HO2                                                                             ', &
     '      C2H4 + OH --> 0.75 EO2 + 0.5 CH2O + 0.25 HO2                                                  ', &
     '      C2H4 + O3 --> 0.5 HCOOH + 0.5 CO + CH2O + 0.12 HO2 + 0.12 OH                                  ', &
     '       SO2 + OH --> SO4                                                                             ', &
     '   GLYOXAL + OH --> CO + HO2                                                                        ', &
     '       EO2 + NO --> NUME + EO + NO2                                                                 ', &
     '         EO + M --> GLYALD + HO2                                                                    ', &
     '             EO --> 2 CH2O + HO2                                                                    ', &
     '      C2H6 + OH --> C2H5O2                                                                          ', &
     '    C2H5O2 + NO --> NUME + CH3CHO + HO2 + NO2                                                       ', &
     '   C2H5O2 + HO2 --> DEN + C2H5OOH                                                                   ', &
     ' C2H5O2 + CH3O2 --> DEN + 0.2 C2H5OH + 0.3 CH3OH + 0.8 CH3CHO + 0.7 CH2O + HO2                      ', &
     '   C2H5OOH + OH --> 0.5 C2H5O2 + 0.5 CH3CHO + 0.5 OH                                                ', &
     '      C3H6 + OH --> PO2                                                                             ', &
     '      C3H6 + O3 --> 0.25 CH3COOH + 0.08 CH4 + 0.56 CO + 0.5 CH3CHO + 0.54 CH2O + 0.31 CH3O2 + 0.19 H', &
     '     C3H6 + NO3 --> ONIT                                                                            ', &
     '       PO2 + NO --> NUME + CH3CHO + CH2O + HO2 + NO2                                                ', &
     '      PO2 + HO2 --> DEN + POOH                                                                      ', &
     '      POOH + OH --> 0.5 PO2 + 0.5 HYAC + 0.5 OH                                                     ', &
     '    CH3CHO + OH --> CH3CO3                                                                          ', &
     '   CH3CHO + NO3 --> HNO3 + CH3CO3                                                                   ', &
     '    CH3CO3 + NO --> NUME + CH3O2 + NO2                                                              ', &
     '   CH3CO3 + NO2 --> PAN                                                                             ', &
     '   CH3CO3 + HO2 --> DEN + 0.25 CH3COOH + 0.75 CH3COOOH + 0.25 O3                                    ', &
     ' CH3CO3 + CH3O2 --> DEN + 0.1 CH3COOH + CH2O + 0.9 CH3O2 + 0.9 HO2                                  ', &
     '  CH3COOOH + OH --> 0.5 CH2O + 0.5 CH3CO3                                                           ', &
     '            PAN --> CH3CO3 + NO2                                                                    ', &
     '       2 CH3CO3 --> DEN + 2 CH3O2                                                                   ', &
     '      C3H8 + OH --> C3H7O2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    C3H7O2 + NO --> NUME + 0.82 CH3COCH3 + 0.27 CH3CHO + HO2 + NO2                                  ', &
     '   C3H7O2 + HO2 --> DEN + C3H7OOH                                                                   ', &
     ' C3H7O2 + CH3O2 --> DEN + 0.82 CH3COCH3 + CH2O + HO2                                                ', &
     '   C3H7OOH + OH --> C3H7O2                                                                          ', &
     '  CH3COCH3 + OH --> RO2                                                                             ', &
     '       RO2 + NO --> NUME + CH2O + CH3CO3 + NO2                                                      ', &
     '      RO2 + HO2 --> DEN + ROOH                                                                      ', &
     '    RO2 + CH3O2 --> DEN + 0.5 CH3OH + 0.5 CH3COCHO + 0.2 HYAC + 0.8 CH2O + 0.3 CH3CO3 + 0.3 HO2     ', &
     '      ROOH + OH --> RO2                                                                             ', &
     '    BIGENE + OH --> ENEO2                                                                           ', &
     '     ENEO2 + NO --> NUME + 0.5 CH3COCH3 + CH3CHO + 0.5 CH2O + HO2 + NO2                             ', &
     '    BIGALK + OH --> ALKO2                                                                           ', &
     '     ALKO2 + NO --> NUME + 0.75 MEK + 0.1 ONIT + 0.25 CH3COCH3 + 0.4 CH3CHO + 0.1 CH2O + 0.9 HO2 + 0', &
     '    ALKO2 + HO2 --> DEN + ALKOOH                                                                    ', &
     '    ALKOOH + OH --> ALKO2                                                                           ', &
     '      ONIT + OH --> CH3COCHO + NO2                                                                  ', &
     '       MEK + OH --> MEKO2                                                                           ', &
     '     MEKO2 + NO --> NUME + CH3CHO + CH3CO3 + NO2                                                    ', &
     '    MEKO2 + HO2 --> DEN + MEKOOH                                                                    ', &
     '    MEKOOH + OH --> MEKO2                                                                           ', &
     '    TOLO2 + HO2 --> DEN + TOLOOH                                                                    ', &
     '    TOLOOH + OH --> TOLO2                                                                           ', &
     '      ISOP + OH --> ISOPO2                                                                          ', &
     '      ISOP + O3 --> 0.2 CH3COOH + 0.3 CO + 0.07 C3H6 + 0.4 MACR + 0.2 MVK + 0.6 CH2O + 0.2 MCO3 + 0.', &
     '    ISOPO2 + NO --> NUME + 0.33 HYDRALD + 0.02 GLYOXAL + 0.02 GLYALD + 0.23 MACR + 0.08 ONITR + 0.02', &
     '   ISOPO2 + NO3 --> 0.36 HYDRALD + 0.02 GLYOXAL + 0.02 GLYALD + 0.25 MACR + 0.02 CH3COCHO + 0.02 HYA', &
     '   ISOPO2 + HO2 --> DEN + ISOPOOH                                                                   ', &
     '   ISOPOOH + OH --> 0.5 XO2 + 0.5 ISOPO2                                                            ', &
     ' ISOPO2 + CH3O2 --> DEN + 0.3 HYDRALD + 0.25 CH3OH + 0.19 MACR + 0.26 MVK + 1.2 CH2O + HO2          ', &
     'ISOPO2 + CH3CO3 --> DEN + 0.4 HYDRALD + 0.25 MACR + 0.35 MVK + 0.6 CH2O + CH3O2 + HO2               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '       MVK + OH --> MACRO2                                                                          ', &
     '       MVK + O3 --> 0.05 CO + 0.04 CH3CHO + 0.95 CH3COCHO + 0.8 CH2O + 0.06 HO2 + 0.2 O3 + 0.08 OH  ', &
     '      MACR + OH --> 0.5 MACRO2 + 0.5 MCO3                                                           ', &
     '      MACR + O3 --> 0.2 CO + 0.8 CH3COCHO + 0.7 CH2O + 0.275 HO2 + 0.2 O3 + 0.215 OH                ', &
     '    MACRO2 + NO --> NUME + 0.22 CO + 0.53 GLYALD + 0.25 CH3COCHO + 0.22 HYAC + 0.25 CH2O + 0.53 CH3C', &
     '    MACRO2 + NO --> NUME + 0.8 ONITR                                                                ', &
     '   MACRO2 + NO3 --> 0.22 CO + 0.53 GLYALD + 0.25 CH3COCHO + 0.22 HYAC + 0.25 CH2O + 0.53 CH3CO3 + 0.', &
     '   MACRO2 + HO2 --> DEN + MACROOH                                                                   ', &
     ' MACRO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.11 CO + 0.26 GLYALD + 0.24 CH3COCHO + 0.23 HYAC + 0.88 CH2O', &
     'MACRO2 + CH3CO3 --> DEN + 0.22 CO + 0.53 GLYALD + 0.25 CH3COCHO + 0.22 HYAC + 0.25 CH2O + 0.53 CH3CO', &
     '   MACROOH + OH --> 0.2 MACRO2 + 0.5 MCO3 + 0.2 HO2 + 0.1 OH                                        ', &
     '      MCO3 + NO --> NUME + CH2O + CH3CO3 + NO2                                                      ', &
     '     MCO3 + NO3 --> CH2O + CH3CO3 + NO2                                                             ', &
     '     MCO3 + HO2 --> DEN + 0.25 CH3COOH + 0.75 CH3COOOH + 0.25 O3                                    ', &
     '   CH3O2 + MCO3 --> DEN + 2 CH2O + CH3CO3 + HO2                                                     ', &
     '  CH3CO3 + MCO3 --> DEN + CH2O + CH3CO3 + CH3O2                                                     ', &
     '         2 MCO3 --> DEN + 2 CH2O + 2 CH3CO3                                                         ', &
     ' MCO3 + NO2 + M --> MPAN                                                                            ', &
     '       MPAN + M --> MCO3 + NO2                                                                      ', &
     '   BENZENE + OH --> 0.12 BEPOMUC + 0.53 PHENOL + 0.35 BENZO2 + 0.65 HO2                             ', &
     '    PHENOL + OH --> 0.14 PHENO2 + 0.06 PHENO + 0.8 HO2                                              ', &
     '    PHENO2 + NO --> NUME + 0.7 GLYOXAL + HO2 + NO2                                                  ', &
     '   PHENO2 + HO2 --> DEN + PHENOOH                                                                   ', &
     '   PHENOOH + OH --> PHENO2                                                                          ', &
     '    PHENO + NO2 --> M                                                                               ', &
     '     PHENO + O3 --> C6H5O2                                                                          ', &
     '    C6H5O2 + NO --> NUME + PHENO + NO2                                                              ', &
     '   C6H5O2 + HO2 --> DEN + C6H5OOH                                                                   ', &
     '   C6H5OOH + OH --> C6H5O2                                                                          ', &
     '    BENZO2 + NO --> NUME + 0.5 BIGALD1 + GLYOXAL + HO2 + NO2                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '   BENZO2 + HO2 --> DEN + BENZOOH                                                                   ', &
     '   BENZOOH + OH --> BENZO2                                                                          ', &
     '    MALO2 + NO2 --> M                                                                               ', &
     '     MALO2 + NO --> NUME + 0.4 GLYOXAL + 0.4 CO + 0.4 HO2                                           ', &
     '    MALO2 + HO2 --> DEN + 0.16 GLYOXAL + 0.16 CO + 0.16 HO2                                         ', &
     '   TOLUENE + OH --> 0.18 CRESOL + 0.1 TEPOMUC + 0.07 BZOO + 0.65 TOLO2 + 0.28 HO2                   ', &
     '    CRESOL + OH --> 0.2 PHENO2 + 0.07 PHENO + 0.73 HO2                                              ', &
     '     BZOO + HO2 --> DEN + BZOOH                                                                     ', &
     '     BZOOH + OH --> BZOO                                                                            ', &
     '      BZOO + NO --> NUME + BZALD + HO2 + NO2                                                        ', &
     '     BZALD + OH --> ACBZO2                                                                          ', &
     '   ACBZO2 + NO2 --> PBZNIT                                                                          ', &
     '         PBZNIT --> ACBZO2 + NO2                                                                    ', &
     '    ACBZO2 + NO --> NUME + C6H5O2 + NO2                                                             ', &
     '   ACBZO2 + HO2 --> DEN + 0.4 C6H5O2 + 0.4 OH                                                       ', &
     '     TOLO2 + NO --> NUME + 0.2 BIGALD2 + 0.2 BIGALD3 + 0.2 BIGALD1 + 0.6 GLYOXAL + 0.4 CH3COCHO + HO', &
     ' DICARBO2 + HO2 --> DEN + 0.07 CO + 0.07 CH3COCHO + 0.33 CH3O2 + 0.07 HO2 + 0.4 OH                  ', &
     '  DICARBO2 + NO --> NUME + 0.17 CO + 0.17 CH3COCHO + 0.83 CH3O2 + 0.17 HO2 + NO2                    ', &
     '  MDIALO2 + HO2 --> DEN + 0.07 GLYOXAL + 0.14 CO + 0.07 CH3COCHO + 0.07 CH3O2 + 0.33 HO2 + 0.4 OH   ', &
     '   MDIALO2 + NO --> NUME + 0.17 GLYOXAL + 0.35 CO + 0.17 CH3COCHO + 0.17 CH3O2 + 0.83 HO2 + NO2     ', &
     ' DICARBO2 + NO2 --> M                                                                               ', &
     '  MDIALO2 + NO2 --> M                                                                               ', &
     '   XYLENES + OH --> 0.23 TEPOMUC + 0.15 XYLOL + 0.06 BZOO + 0.56 XYLENO2 + 0.38 HO2                 ', &
     '     XYLOL + OH --> 0.07 PHENO + 0.3 XYLOLO2 + 0.63 HO2                                             ', &
     '   XYLOLO2 + NO --> NUME + 0.17 GLYOXAL + 0.51 CH3COCHO + HO2 + NO2                                 ', &
     '  XYLOLO2 + HO2 --> DEN + XYLOLOOH                                                                  ', &
     '  XYLOLOOH + OH --> XYLOLO2                                                                         ', &
     '  XYLENO2 + HO2 --> DEN + XYLENOOH                                                                  ', &
     '  XYLENOOH + OH --> XYLENO2                                                                         ', &
     '   XYLENO2 + NO --> NUME + 0.2 BIGALD2 + 0.21 BIGALD4 + 0.15 BIGALD3 + 0.06 BIGALD1 + 0.34 GLYOXAL +' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '      APIN + OH --> TERPO2                                                                          ', &
     '      BPIN + OH --> TERPO2                                                                          ', &
     '     LIMON + OH --> TERPO2                                                                          ', &
     '      MYRC + OH --> TERPO2                                                                          ', &
     '     BCARY + OH --> TERPO2                                                                          ', &
     '      APIN + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.33 TERPROD1 ', &
     '      BPIN + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.33 TERPROD1 ', &
     '     LIMON + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.33 TERPROD1 ', &
     '      MYRC + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.33 TERPROD1 ', &
     '     BCARY + O3 --> 0.05 BIGALK + 0.05 HCOOH + 0.1 BIGALD + 0.52 CH3COCH3 + 0.23 CO + 0.33 TERPROD1 ', &
     '    LIMON + NO3 --> NTERPO2                                                                         ', &
     '     MYRC + NO3 --> NTERPO2                                                                         ', &
     '    BCARY + NO3 --> NTERPO2                                                                         ', &
     '    TERPO2 + NO --> NUME + 0.045 CH3COCH3 + 0.9 TERPROD1 + 0.1 ONITR + 0.36 CH2O + 0.9 HO2 + 0.9 NO2', &
     '   TERPO2 + HO2 --> DEN + TERPOOH                                                                   ', &
     ' TERPO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.025 CH3COCH3 + TERPROD1 + 0.95 CH2O + HO2                  ', &
     '   TERPOOH + OH --> TERPO2                                                                          ', &
     '  TERP2OOH + OH --> TERP2O2                                                                         ', &
     '  TERPROD1 + OH --> TERP2O2                                                                         ', &
     ' TERPROD1 + NO3 --> 0.5 NTERPO2 + 0.5 TERP2O2                                                       ', &
     '   TERP2O2 + NO --> NUME + 0.27 CH3COCH3 + 0.225 CO + 0.225 GLYALD + 0.9 TERPROD2 + 0.1 ONITR + 0.34', &
     '  TERP2O2 + HO2 --> DEN + TERP2OOH                                                                  ', &
     'TERP2O2 + CH3O2 --> DEN + 0.25 CH3OH + 0.15 CH3COCH3 + 0.125 CO + 0.125 GLYALD + TERPROD2 + 0.93 CH2', &
     '  TERPROD2 + OH --> 0.5 CH3COCH3 + 0.7 CO + 0.15 RO2 + 0.68 CH2O + 0.65 CH3CO3 + 0.2 HO2            ', &
     '   NTERPO2 + NO --> NUME + 0.9 TERPROD1 + 0.1 ONITR + 1.9 NO2                                       ', &
     '  NTERPO2 + HO2 --> DEN + ONITR                                                                     ', &
     'NTERPO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.5 TERPROD1 + 0.5 ONITR + 0.75 CH2O + 0.5 HO2 + 0.5 NO2     ', &
     '  NTERPO2 + NO3 --> TERPROD1 + 2 NO2                                                                ', &
     '   CH3COOH + OH --> CH3O2                                                                           ', &
     '     ISOP + NO3 --> ISOPNO3                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '   ISOPNO3 + NO --> NUME + 0.167 MACR + 0.794 ONITR + 0.039 MVK + 0.072 CH2O + 0.794 HO2 + 1.206 NO2', &
     '  ISOPNO3 + NO3 --> 0.167 MACR + 0.794 ONITR + 0.039 MVK + 0.072 CH2O + 0.794 HO2 + 1.206 NO2       ', &
     '  ISOPNO3 + HO2 --> DEN + 0.167 MACR + 0.794 ONITR + 0.039 MVK + 0.206 CH2O + 0.206 NO2 + 0.206 OH  ', &
     '  CH3COCHO + OH --> CO + CH3CO3                                                                     ', &
     ' CH3COCHO + NO3 --> HNO3 + CO + CH3CO3                                                              ', &
     '     ONITR + OH --> HYDRALD + HO2 + 0.4 NO2                                                         ', &
     '    ONITR + NO3 --> HYDRALD + HO2 + NO2                                                             ', &
     '   HYDRALD + OH --> XO2                                                                             ', &
     '       XO2 + NO --> NUME + 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 CH3COCHO + 0.25 HYAC + 0.25 C', &
     '      XO2 + NO3 --> 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 CH3COCHO + 0.25 HYAC + 0.25 CH2O + H', &
     '      XO2 + HO2 --> DEN + XOOH                                                                      ', &
     '    XO2 + CH3O2 --> DEN + 0.3 CH3OH + 0.1 GLYOXAL + 0.2 CO + 0.1 GLYALD + 0.1 CH3COCHO + 0.1 HYAC + ', &
     '   XO2 + CH3CO3 --> DEN + 0.25 GLYOXAL + 0.25 CO + 0.25 GLYALD + 0.25 CH3COCHO + 0.25 HYAC + 0.25 CH', &
     '      XOOH + OH --> XO2                                                                             ', &
     '      XOOH + OH --> OH                                                                              ', &
     '     CH3OH + OH --> CH2O + HO2                                                                      ', &
     '    C2H5OH + OH --> CH3CHO + HO2                                                                    ', &
     '      MPAN + OH --> 0.5 HYAC + 0.5 CH2O + 0.5 HO2 + 0.5 NO3                                         ', &
     '       PAN + OH --> CH2O + NO3                                                                      ', &
     '      HYAC + OH --> CH3COCHO + HO2                                                                  ', &
     '    GLYALD + OH --> 0.2 GLYOXAL + 0.8 CH2O + HO2                                                    ', &
     '       DMS + OH --> SO2                                                                             ', &
     '       DMS + OH --> 0.5 SO2 + 0.5 HO2                                                               ', &
     '      DMS + NO3 --> SO2 + HNO3                                                                      ', &
     '       NH3 + OH --> M                                                                               ', &
     '            HO2 --> 0.5 H2O2                                                                        ', &
     '       2 C2H5O2 --> DEN + 0.4 C2H5OH + 1.6 CH3CHO + 1.2 HO2                                         ', &
     '       MBO + OH --> MBOO2                                                                           ', &
     '     MBOO2 + NO --> NUME + 0.33 HMPROP + 0.67 CH3COCH3 + 0.67 GLYALD + 0.33 CH2O + HO2 + NO2        ', &
     '  MBOO2 + CH3O2 --> DEN + 0.25 CH3OH + 0.167 HMPROP + 0.333 CH3COCH3 + 0.333 GLYALD + 0.917 CH2O + H' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(22) :: EQN_NAMES_9 = (/ &
     '    HMPROP + OH --> HMPROPO2                                                                        ', &
     '  HMPROPO2 + NO --> NUME + CH3COCH3 + HO2 + NO2                                                     ', &
     ' HMPROPO2 + HO2 --> DEN + 0.4 CH3COCH3 + 0.4 HO2 + 0.4 OH                                           ', &
     '    MBOO2 + HO2 --> DEN + MBOOOH                                                                    ', &
     '    MBOOOH + OH --> 0.5 MBOO2 + 0.5 OH                                                              ', &
     '       MBO + O3 --> 0.25 HCOOH + 0.9 HMPROP + 0.1 CH3COCH3 + 0.35 CO + 0.5 CH2O + 0.06 HO2 + 0.06 OH', &
     '      MBO + NO3 --> MBONO3O2                                                                        ', &
     ' MBONO3O2 + HO2 --> DEN                                                                             ', &
     '  MBONO3O2 + NO --> NUME + 0.75 ONIT + 0.25 HMPROP + 0.75 CH3COCH3 + 0.25 CH2O + 0.75 HO2 + 1.25 NO2', &
     ' MBONO3O2 + NO3 --> 0.75 ONIT + 0.25 HMPROP + 0.75 CH3COCH3 + 0.25 CH2O + 0.75 HO2 + 1.25 NO2       ', &
     '      C2H2 + OH --> 0.35 HCOOH + 0.65 GLYOXAL + 0.35 CO + 0.35 HO2 + 0.65 OH                        ', &
     '     HCOOH + OH --> HO2 + H2O                                                                       ', &
     '     CH2O + HO2 --> HOCH2OO                                                                         ', &
     '        HOCH2OO --> CH2O + HO2                                                                      ', &
     '   HOCH2OO + NO --> NUME + HCOOH + HO2 + NO2                                                        ', &
     '  HOCH2OO + HO2 --> DEN + HCOOH                                                                     ', &
     '      VOCA + OH --> SMPA + OH                                                                       ', &
     '     VOCBB + OH --> SMPBB + OH                                                                      ', &
     '      ISOP + OH --> BIOG1_c + ISOP + OH                                                             ', &
     '      APIN + OH --> BIOG1_o + APIN + OH                                                             ', &
     '      BPIN + OH --> BIOG1_o + BPIN + OH                                                             ', &
     '     LIMON + OH --> BIOG1_o + LIMON + OH                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(292) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9 /)

! INLINED global variables

! End INLINED global variables


END MODULE mozart_mosaic_4bin_Monitor
